### ISSUE TITLE
Time out exception while calling long running WCF service from .net core

### ISSUE THREAD

**Issue by sshaikh1** [dotnet/core#1185]
Time out exception while calling long running WCF service from .net core

Getting a System.Net.Http.WinHttpException (0x80072EE2): The operation timed out... exception is occurring when calling a long running WCF service from .net core 2 web api / console application. Service operation takes around a minute to execute and return a response. Is there away I can set the higher operation timeout, so that it doesn't times out.

Same service operation works fine with .net framework 4.5 console app.

at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at XXXXXXXXXXXXXXX
in D:\XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   .cs:line 28

Inner Exception :

InnerException = {System.Net.Http.WinHttpException (0x80072EE2): The operation timed out
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
at System.Net.Http.WinHttpHandler.<StartRequest...

Thanks.

**Comment by rahul-raut** [comment]
I am also facing the same issue.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/wcf #2588](https://github.com/dotnet/wcf/issues/2588) via [**ZenHub**](https://www.zenhub.com/)
