### ISSUE TITLE
Name clash between own name and library name on dotnet core 2.0

### ISSUE THREAD

**Issue by gregorybleiker** [dotnet/core#1192]
If you create a console app via
dotnet new console 
in a directory named "websocket", you will receive a websocket.csproj
Putting the code below in the Main method will cause the error below. Is this the expected behaviour?

```
var webSocket = new ClientWebSocket();
CancellationToken token = new CancellationToken();
webSocket.ConnectAsync(uri: new Uri(@"ws://172.16.100.163:8080"), cancellationToken: token).Wait();
Console.Write($"task result {webSocket.State}");
```
No matter what the Uri (I have tried several, and I can't even see any outgoing connection in wireshark)
this is the result:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to connect to the remote server) ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.Http.WinHttpException: Not enough storage is available to process this command
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at websocket.Program.Main(String[] args) in C:\Users\gregorybleiker\work\websocket\Program.cs:line 16
```

**Comment by benaadams** [comment]
`System.Net.Http.WinHttpException: Not enough storage is available to process this command`

That's a pretty weird exception

**Comment by benaadams** [comment]
Similar message https://github.com/dotnet/corefx/issues/24139

Seems to be a [`ERROR_NOT_ENOUGH_MEMORY`](https://github.com/dotnet/coreclr/blob/24f1153adfc1a83e490d8d22ee353b322aba1e33/src/pal/src/misc/errorstrings.cpp#L41) message; probably should say that rather than storage.

Though that's an aside...

**Comment by gregorybleiker** [comment]
I certainly have enough free memory (16GB machine, 7GB free)

**Comment by gregorybleiker** [comment]
btw. I should have said that I am running the code above in a dotnet core console app in the Main section... could there be some references missing?

**Comment by gregorybleiker** [comment]
OK, I found out what the problem was: I was using websocket.csproj as my project name. That must have led to a name clash with the "other" websocket...

**Comment by benaadams** [comment]
Might want to add that to description and leave open?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8838](https://github.com/dotnet/cli/issues/8838) via [**ZenHub**](https://www.zenhub.com/)
