### ISSUE TITLE
Segmentation fault (core dumped) on docker with microsoft/aspnetcore:2.0

### ISSUE THREAD

**Issue by Jarlotee** [dotnet/core#1397]
# Issue Title

Segmentation fault (core dumped) on docker with microsoft/aspnetcore:2.0

# General

I have an application that creates two new background threads to process messages from RabbitMQ using the following method.

[Example](https://gist.github.com/Jarlotee/84dc75ba905a0a96d6aafd54b10ee278)

Upon starting a 2nd queue listener a Segmentation Fault is generated

```bash
root@demo:/app# gdb --args dotnet sampleApp.dll process-queue
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from dotnet...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/dotnet sampleApp.dll process-queue
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4932700 (LWP 796)]
[New Thread 0x7ffff4131700 (LWP 797)]
[New Thread 0x7ffff3930700 (LWP 798)]
[New Thread 0x7ffff312f700 (LWP 799)]
[New Thread 0x7ffff292e700 (LWP 800)]
[New Thread 0x7ffff1db4700 (LWP 801)]
[New Thread 0x7fffe2582700 (LWP 802)]
[New Thread 0x7fffe1d81700 (LWP 803)]
[New Thread 0x7fffe1580700 (LWP 804)]
[New Thread 0x7ffff0496700 (LWP 805)]
[New Thread 0x7fffe0d7f700 (LWP 806)]
[New Thread 0x7ffff0455700 (LWP 807)]
[New Thread 0x7fffe057e700 (LWP 808)]
[New Thread 0x7fffdf960700 (LWP 809)]
[New Thread 0x7fffdf15f700 (LWP 810)]
[New Thread 0x7fffde95e700 (LWP 811)]
[New Thread 0x7fff57ffd700 (LWP 812)]
[New Thread 0x7fff577fc700 (LWP 813)]
Thread 10 "dotnet" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1580700 (LWP 804)]
0x00007ffff627cfd0 in EventPipeConfiguration::RegisterProvider(EventPipeProvider&) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/libcoreclr.so
(gdb) Quit
(gdb) backtrace
#0  0x00007ffff627cfd0 in EventPipeConfiguration::RegisterProvider(EventPipeProvider&) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/libcoreclr.so
#1  0x00007ffff627c61b in EventPipeInternal::CreateProvider(_GUID, void (*)(_GUID const*, unsigned int, unsigned char, unsigned long, unsigned long, void*, void*)) ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/libcoreclr.so
#2  0x00007fff7cc67bd1 in ?? ()
#3  0xffffffffffffffff in ?? ()
#4  0x000000005e004aa3 in ?? ()
#5  0x00007ffff67b1488 in vtable for InlinedCallFrame () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/libcoreclr.so
#6  0x00007fffe157e500 in ?? ()
#7  0x00007fff7c7198b8 in ?? ()
#8  0x00007fff7c7198b8 in ?? ()
#9  0x00007fffe157df60 in ?? ()
#10 0x00007fff7cc67bd1 in ?? ()
#11 0x00007fffe157e010 in ?? ()
#12 0x00007fff7c7198b8 in ?? ()
#13 0x00007fff58232460 in ?? ()
#14 0x4b9649b235167f8e in ?? ()
#15 0x5e6b33595b4386ab in ?? ()
#16 0x4b9649b235167f8e in ?? ()
#17 0x5e6b33595b4386ab in ?? ()
#18 0x4b9649b235167f8e in ?? ()
#19 0x5e6b33595b4386ab in ?? ()
#20 0x00007fff58232448 in ?? ()
#21 0x00007fff58232460 in ?? ()
#22 0x00007fff5822bbc8 in ?? ()
#23 0x00007fff58232408 in ?? ()
#24 0x0000000000000000 in ?? ()
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit
A debugging session is active.

        Inferior 1 [process 792] will be killed.

Quit anyway? (y or n) y
```

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/coreclr #17362](https://github.com/dotnet/coreclr/issues/17362) via [**ZenHub**](https://www.zenhub.com/)
