### ISSUE TITLE
Sockets not listening on dual-sockets by default

### ISSUE THREAD

**Issue by FlyingWraptor** [dotnet/core#1469]
# Sockets not listening right Internet Protocol in Net classes

Currently the (tested) sockets wrappers won't use IPv6 alongside IPv4 in dual-stack.
Meaning out of the box connections on SmtpClient, TcpClient and MySql connector require modifications at the Socket for functioning on IPv6. 

In .NET Standard this isn't the issue at all because it determines the right protocol by the given input string already.
Source:
https://blogs.msdn.microsoft.com/webdev/2013/01/08/dual-mode-sockets-never-create-an-ipv4-socket-again/

This SHOULD be in .NET core aswell as this might prevent starting or even experienced developers from using IPv6 over all as IPv4 'Just works'.

# Environment

Version: .NET-Core v2.1.105
Project: WebAPI
Platform: Windows 10 Pro x86-x64
      Build: 16299.371

# Testing
## SmtpClient
Code:
```c#
SmtpClient smtpClient= new SmtpClient();
smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;

smtpClient.Port = 587;
smtpClient.Host = "fd00::8:23";
smtpClient.EnableSsl = true;

smtpClient.UseDefaultCredentials = false;
smtpClient.Credentials = new NetworkCredential("username", "password");

MailMessage mmMail = new MailMessage("valid_sender", "valid_receiver");
mmMail.Subject = "Subject";
mmMail.Body = "Message";

smtpClient.SendMailAsync(Mail);
```
Resulting in:
```
System.Net.Mail.SmtpException: Failure sending mail. ---> System.ArgumentException: None of the discovered or specified addresses match the socket address family.
Parameter name: context
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
```
Doing this synchronically using:
```c#
smtpClient.Send(Mail);
```
Results:
```
System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
```

## MySQL
Using a simple custom (working wrapper) with the following querystring
```c#
this.connectionString = "Server=fd00::8:21;Port=3306;Uid=Username;Pwd=password;Allow User Variables=True;Connection Timeout=1;";
```
I get the following error:
```
System.NotSupportedException: This protocol version is not supported.
   at System.Net.Sockets.Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_0(String targetHost, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Sockets.TcpClient.ConnectAsync(String host, Int32 port)
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
```

## Plain TcpClient
Leading me to do some testing using a TcpClient:
```c#
TcpClient tcpClient = new TcpClient();
IPAddress ipaAddress = IPAddress.Parse("fd00::8:23");
tcpClient.Connect(ipaAddress, 587);
```
Result:
```
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException
  HResult=0x80004005
  Message=An address incompatible with the requested protocol was used [fd00::8:23]:587
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
```

If I set the AddressFamily however the code works:
```c#
TcpClient tcpClient = new TcpClient(AddressFamily.InterNetworkV6);
tcpClient.Client.DualMode = true;
```

**Comment by FlyingWraptor** [comment]
Moved to https://github.com/dotnet/corefx/issues/29414
