### ISSUE TITLE
"System.Net.Http.WinHttpException" after migrating to .net Core

### ISSUE THREAD

**Issue by Ramin2c** [dotnet/core#1515]
I am having a strange issue after the our .net 4 based code is being migrated to .net core 2.0. We are calling some enterprise but simple (and not long running) web services in our code. The part of the code which fetches the result from the task object fails to work when we run the .net core code from VS 2017 with the following exception:

{System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.ServiceModelHttpMessageHandler.<SendAsync>d__41.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)}
		
		{System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
		   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
		   --- End of inner exception stack trace ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.ServiceModel.Channels.ServiceModelHttpMessageHandler.<SendAsync>d__41.MoveNext()
		   --- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
		   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
		   --- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()}
				
				{System.Net.Http.WinHttpException (0x80072EE2): The operation timed out
				   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
				   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
				   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()}

We are running the code on a corporation pc which I guess is behind the proxy but the thing is that the legacy code from the same computer but run within VS 2015 works just as expected. 
It became even more confusing when we tested the same code (.net core 2.0) in VS Code on a cloud (AWS) based computer and it worked! 
Putting these all together I guess(ed) the new VS or .net core 2.0 runtime is somehow blocked by some firewall policy and tried different options like enabling a proxy for the app we are working with or for the whole VS 2017 (devenv process) and disabling some firewall domains (those that we could) but neither one worked. 
My assumption is that .net Core runtime is somehow blocked from connecting to the internet.
Yet another observation: 
I tested the following code on a local machine (behind the company firwall) on .net core 2.0 and from VS 2017 and it also worked fine:

`        public static async Task<byte[]> DownloadFile(string url)
        {
            using (var client = new HttpClient())
            {
                using (var result = await client.GetAsync(url))
                {
                    if (result.IsSuccessStatusCode)
                    {
                        return await result.Content.ReadAsByteArrayAsync();
                    }

                }
            }
            return null;
        }
`
So looks like it is only the outgoing requests that are blocked.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #31037](https://github.com/dotnet/corefx/issues/31037) via [**ZenHub**](https://www.zenhub.com/)
