### ISSUE TITLE
dotnet core 1.1 project - System.core 4.0.0.0 could not load file 

### ISSUE THREAD

**Issue by Meenakshise** [dotnet/core#1531]
# Issue Title
 
Could not load file System.core 4.0.0.0

# General 

We have a dot net core 1.1 console application which was running perfectly in our deployed server. All of a sudden our 2 dot net core application stopped working. 

When i checked i realized one of developer has upgraded one of the project to use netcoreapp2.0 from netcoreapp1.1 to make use of windows active directory support.  So I installed dotnet 2 download from the below link in our deployed server. It has fixed the issue of the project which had upgraded to netcoreapp2.0. But my other application is still in netcoreapp1.1 which is rendering any output on the site. it just gives the below error 
[](https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.200-windows-x86-installer). 

Application startup exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at VitalPAC.FEWS.Startup..ctor(IHostingEnvironment env) in C:\BuildAgent\work\7566eaf1022bd34c\FObs\src\Startup.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: C:\Octopus\Applications\VAYU\Bangalore_3.6\FlexibleEarlyWarningScore\3.6.0.266
Now listening on: http://localhost:7392
Application started. Press Ctrl+C to shut down.

**Comment by leecow** [comment]
@muratg @natemcmaster, PTAL.

**Comment by natemcmaster** [comment]
@Meenakshise Can you share the .csproj file of the netcoreapp1.1 application that is failing? Also, if you can, please share your NuGet assets file, which is found in "(project directory)/obj/project.assets.json". It will help us diagnose exactly which dependencies your application is using.

**Comment by Meenakshise** [comment]
@natemcmaster 

Thanks for the reply. Please find the files attached which you were asking for.. 

[csproj.txt](https://github.com/dotnet/core/files/1993974/csproj.txt)
[project.assets.txt](https://github.com/dotnet/core/files/1993975/project.assets.txt)

**Comment by Meenakshise** [comment]
@natemcmaster 
Also I have attached the screen shot of SDK explorer of my current project with the Nugget explorer as well. Under nugget I see System.Core not loaded with an yellow color warning. And under SDK system.core is missing. But as part of the project.assets.json you will see System.Core is present as shown below. 

 "System.Core": {
            "target": "Package",
            "version": "[4.0.0, )"
          },

![currentproject-sdkscreenshot](https://user-images.githubusercontent.com/5516586/39907025-d837beee-5503-11e8-8c2a-eb2e563ab468.png)
![currentproject-nugetscreenshot](https://user-images.githubusercontent.com/5516586/39907027-d9890e2e-5503-11e8-9ba0-b3abf4e624c1.png)


**I created a new sample console app dot net core project. There i could see System.Core loaded perfectly under SDK.**
![newconsoleappsdkscreenshot](https://user-images.githubusercontent.com/5516586/39907012-be2e0a58-5503-11e8-9f17-f1d53f43cfd5.png)

**Comment by natemcmaster** [comment]
Try removing these line from your csproj file:
```diff
-  <PackageReference Include="System.Core" Version="4.0.0">		  
-  </PackageReference>
```
I think this is actually the source of the problem. You don't need this PackageReference in .NET Core projects.

**Comment by Meenakshise** [comment]
I directly removed it from the Nugget explorer. But still my deployment gives the same error.. 
@natemcmaster

**Comment by Meenakshise** [comment]
[csproj.txt](https://github.com/dotnet/core/files/1994158/csproj.txt)
Attached the latest csproj file 
@natemcmaster

**Comment by Meenakshise** [comment]
I looked at the history of my csproj file it looks like the System.core was not there only. Not sure how it came when i was checking now. Probably if i tried installing something i am not sure. 
But still the deployment fails with the same error. 

Attached the files that are generated in the deployment server. I don't see anything related to System.Core

[src.runtimeconfig.txt](https://github.com/dotnet/core/files/1994213/src.runtimeconfig.txt)
[src.deps.txt](https://github.com/dotnet/core/files/1994214/src.deps.txt)

**Comment by natemcmaster** [comment]
How are you deploying? Is the System.Core.dll file still present in your app? You may need to clean first or delete all files in your deployment output.

**Comment by Meenakshise** [comment]
It is built and deployed by teamcity and octopus

**Comment by Meenakshise** [comment]
If i add a nuget package it modifies which file how do i know my nuget package is committed?

**Comment by Meenakshise** [comment]
Even if i try to add System.Core 4.0 also it is just showing 3.5 version. I thought of installing 3.5 but that too failed. Could you please help me..  I am unable to figure out the issue.. 

![image](https://user-images.githubusercontent.com/5516586/39915105-ae329198-5524-11e8-8de5-8c880b56d34e.png)
![image](https://user-images.githubusercontent.com/5516586/39915255-11b8afd6-5525-11e8-9a44-7ee7be7866ad.png)

**Comment by Meenakshise** [comment]
I fixed the issue. I found in our project they are calling another project to feed the database that has reference to system. Core. Since that project dll was referenced in our nuspec file it created this issue. For I have commented out that code.

But how will we ensure to load all the dlls referenced by that project as well
