### ISSUE TITLE
OSX NamedPipeClientStream.get_NumberOfServerInstances() PlatformNotSupportedException

### ISSUE THREAD

**Issue by WG-Com** [dotnet/core#156]
error:
```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.IO.Pipes.NamedPipeClientStream.get_NumberOfServerInstances()
   at ConsoleApplication.Program.Main(String[] args)

[1]    15107 abort      ./bin/Debug/netcoreapp1.0/osx.10.11-x64/cli
```

document :
https://docs.microsoft.com/en-us/dotnet/core/api/system.io.pipes.namedpipeclientstream#System_IO_Pipes_NamedPipeClientStream_NumberOfServerInstances

```
using System;
using System.IO;
using System.IO.Pipes;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            NamedPipeClientStream pipeClient =
            new NamedPipeClientStream(".", "testpipe", PipeDirection.In);
              // Connect to the pipe or wait until the pipe is available.
            Console.Write("Attempting to connect to pipe...");
            pipeClient.Connect();

            Console.WriteLine("Connected to pipe.");
            Console.WriteLine(pipeClient.NumberOfServerInstances);
            
            
        }
    }
}

```

```
using System;
using System.IO;
using System.IO.Pipes;
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
         Console.Write("Waiting for client connection...");
            
           NamedPipeServerStream pipeServer =
            new NamedPipeServerStream("testpipe", PipeDirection.Out);
            pipeServer.WaitForConnection();

            Console.WriteLine("Client connected.");
            try
            {
                // Read user input and send that to the client process.
                using (StreamWriter sw = new StreamWriter(pipeServer))
                {
                    sw.AutoFlush = true;
                    Console.Write("Enter text: ");
                    sw.WriteLine(Console.ReadLine());
                }
            }
            // Catch the IOException that is raised if the pipe is broken
            // or disconnected.
            catch (IOException e)
            {
                Console.WriteLine("ERROR: {0}", e.Message);
            }
            
        }
    }

}


```

**Comment by stephentoub** [comment]
Yes, it isn't supported on Unix.
