### ISSUE TITLE
Kestrel ListenUnixSocket throws `Only ListenType.IPEndPoint is supported` as of 2.1 RC

### ISSUE THREAD

**Issue by sdb-dev** [dotnet/core#1599]
# Issue
Kestrel ListenUnixSocket throws `Only ListenType.IPEndPoint is supported` as of 2.1 RC

# General

After upgrading to .NET Core 2.1 RC, I am no longer able to use kestrel's 'ListenUnixSocket' feature to use unix sockets instead of TCP sockets.

## Stack Trace
```
Unhandled Exception: System.ArgumentException: Only ListenType.IPEndPoint is supported.
Parameter name: endPointInformation
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.Create(IEndPointInformation endPointInformation, IConnectionDispatcher dispatcher)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at SampleNamespace.Website.Program.Main(String[] args) in C:\BuildAgent.VSTS\_work\26\s\SampleNamespace.Website\Program.cs:line 18
```

## Code
```CSharp
  WebHost.CreateDefaultBuilder(args)
#if DEBUG
                .UseEnvironment("Development")
#elif STAGING
                .UseEnvironment("Staging")
#else
                .UseEnvironment("Production")
                .UseApplicationInsights()
#endif
                .UseStartup<Startup>()
                .UseKestrel(options =>
                {
                    if (Environment.OSVersion.Platform == PlatformID.Unix)
                    {
                        options.ListenUnixSocket("/tmp/kestrel.sock");
                    }
                    //options.Listen(IPAddress.Loopback, 8080);
                })
                .Build();
```

## Extra Info
**OS:** Ubuntu 16.04.4
**.NET Core Version:** 2.1.300-rc1-008673
**Project Packages:** All updated to v2.1.0-rc1-final

Would this have anything to do with Kestrel's update in 2.1 where HTTPs is the default while debugging?

**Comment by sdb-dev** [comment]
Wrong project
