### ISSUE TITLE
.NET Core 2.1 RSA Disposal and JWT

### ISSUE THREAD

**Issue by kmanev073** [dotnet/core#1688]
# Unable To Dispose RSA Key before JWT creation.
# General
Hi guys!
Today I updated my project to .NET Core 2.1 and I ran into some issues which I think should be fixed. Basically I have an API that generates JWT tokens igned with RSA. That **was** my code:        
```
using (RSA publicRsa = RSA.Create())
{
            publicRsa.EdoFromXmlString(_options.PublicKey);
            _issuerSigningKey = new RsaSecurityKey(publicRsa);
}
using (RSA privateRsa = RSA.Create())
{
            _privateRsa.EdoFromXmlString(_options.PrivateKey);
            RsaSecurityKey privateKey = new RsaSecurityKey(_privateRsa);
            _signingCredentials = new SigningCredentials(privateKey, SecurityAlgorithms.RsaSha256);
}
_jwtHeader = new JwtHeader(_signingCredentials);
```
Basically, created my RSAs in usings statements, used them and they were auto disposed. Now after upgrading to 2.1 this code was broken and was throwing exceptions on both sides, when creating the JWT and when trying to read it.

I use **Microsoft.AspNetCore.Authentication.JwtBearer** and that's how I create the token. 

```
JwtSecurityTokenHandler _jwtSecurityTokenHandler = new JwtSecurityTokenHandler();
_jwtSecurityTokenHandler.WriteToken(new JwtSecurityToken(_jwtHeader, payload));
```
I use the _jwtHeader generated above and the payload is not that important. 

That is the exeption:
```
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Crypto.RsaSize(SafeRsaHandle rsa)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Boolean allocateSignature, Int32& bytesWritten, Byte[]& signature)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Sign(Byte[] input)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at APIGateway.Auth.JwtHandler.CreateUserToken(User user, List`1 roles) in /home/kaloyanmanev/Projects/edotailor/APIGateway/Auth/JwtHandler.cs:line 64
   at APIGateway.Services.UserService.AuthenticateUserAsync(String username, String password) in /home/kaloyanmanev/Projects/edotailor/APIGateway/Services/UserService.cs:line 27
   at APIGateway.Controllers.UserController.AuthenticateUser(String Username, String Password) in /home/kaloyanmanev/Projects/edotailor/APIGateway/Controllers/UserController.cs:line 46
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
After I saw the exeption I changed my code to:
```
_publicRsa = RSA.Create();
_publicRsa.EdoFromXmlString(_options.PublicKey);
_issuerSigningKey = new RsaSecurityKey(_publicRsa);
            
_privateRsa = RSA.Create();
_privateRsa.EdoFromXmlString(_options.PrivateKey);
RsaSecurityKey privateKey = new RsaSecurityKey(_privateRsa);
_signingCredentials = new SigningCredentials(privateKey, SecurityAlgorithms.RsaSha256);
            
_jwtHeader = new JwtHeader(_signingCredentials);

//payload generation

string result = _jwtSecurityTokenHandler.WriteToken(new JwtSecurityToken(_jwtHeader, payload));
_publicRsa.Dispose();
_privateRsa.Dispose();
```
As you can see I removed the using statements and I dispose the RSAs myself and it now works. (Had to do this on both sides, when creating the token and when validating it).
I am not sure if this is an issue or feature but to me it seems that my old should still be working. 
This only appears when I run the app from the CLI, if I am debugging the application no such problems occur and the token is generated without problems. Really strange...

This is my first time ever writing something like this and I hope that I am now wasting your time and also that someone might find this useful.

Regards!

**Comment by bartonjs** [comment]
Seems like it would be due to a change in JwtSecurityTokenHandler.  Nothing in corefx changed how disposability worked.

So, probably https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/?  (I don't know if we can move items from here to there)

**Comment by kmanev073** [comment]
Should I close the issue and post it there?

**Comment by Petermarcu** [comment]
That's probably the best option. I'm going to close this here and let you open the new one there.
