### ISSUE TITLE
BrotliStream crashes trying to decompress ~2000000 int32 array

### ISSUE THREAD

**Issue by fontmaniac** [dotnet/core#1718]
# Issue Title

BrotliStream in Decompress Mode crashes when trying to decompress large-ish array. We originally encountered the problem when working with binary data (~40Mb when compressed), here is a minimal example with just 2000000 int32 array of random values. 
Exceptions thrown in this example vary between "Unable to read beyond the end of the stream." and "Decoder ran into invalid data.", depending on the CompressionLevel used. In real code (F#-based) we've also seen some other failure modes, including OutOfMemory exception (see stack trace at the bottom) and silently dying without logging an exception.

# General

NET Core 2.1, Windows 10, console application.

## Project file

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.1</TargetFramework>
      </PropertyGroup>
    </Project>

## Code example:
    class Program
    {
        static Int32[] ReadFile(string fileName, Func<FileStream, Stream> createStream)
        {
            using (var file = new FileStream(fileName, FileMode.Open, FileAccess.Read))
            using (var zip = createStream(file))
            using (var br = new BinaryReader(zip))
            {
                var count = br.ReadInt32();
                var result = (int[])Array.CreateInstance(typeof(Int32), count);
                for (var i = 0; i < count; ++i)
                    result[i] = br.ReadInt32();

                return result;
            }
        }

        static void WriteFile(string fileName, Func<FileStream, Stream> createStream, int[] data)
        {
            using (var file = new FileStream(fileName, FileMode.Create))
            using (var zip = createStream(file))
            using (var br = new BinaryWriter(zip))
            {
                br.Write(data.Length);
                for (var i = 0; i < data.Length; ++i)
                    br.Write(data[i]);

            }
        }

        static int[] GetData(int length)
        {
            var rnd = new Random(42);
            var result = (int[])Array.CreateInstance(typeof(Int32), length);
            for (var i = 0; i < length; ++i)
                result[i] = rnd.Next();

            return result;

        }

        static Stream DecompressGZip(FileStream file)   { return new GZipStream(file, CompressionMode.Decompress); }
        static Stream DecompressBrotli(FileStream file) { return new BrotliStream(file, CompressionMode.Decompress); }
        static Stream CompressGZip(FileStream file)     { return new GZipStream(file, CompressionLevel.Optimal); }
        static Stream CompressBrotli(FileStream file)   { return new BrotliStream(file, CompressionLevel.Fastest); }
        static Stream CompressNone(FileStream file)     { return file; }

        static bool CompareArrays(int[] a, int[] b)
        {
            if (a.Length != b.Length) return false;
            for (var i = 0; i < a.Length; ++i)
                if (a[i] != b[i]) return false;
            return true;
        }

        static void Main(string[] args)
        {
            var rootLoc = @".\";
            var uncompressedRaw     = Path.Combine(rootLoc, "uncompressedRaw.bin");
            var compressedGZip      = Path.Combine(rootLoc, "compressedGZip.bin");
            var unCompressedGZip    = Path.Combine(rootLoc, "unCompressedGZip.bin");
            var compressedBrotli    = Path.Combine(rootLoc, "compressedBrotli.bin");
            var unCompressedBrotli  = Path.Combine(rootLoc, "unCompressedBrotli.bin");

            for (var i = 1; i <= 7; ++i)
            {
                var length = 2 * (int)Math.Pow(10, i);
                var data = GetData(length);
                WriteFile(uncompressedRaw,  CompressNone,   data);
                WriteFile(compressedGZip,   CompressGZip,   data);
                WriteFile(compressedBrotli, CompressBrotli, data);

                var dataGz = ReadFile(compressedGZip, DecompressGZip);
                if (CompareArrays(data, dataGz))
                    Console.WriteLine("{0} elements: GZip compression is correct", length);
                else
                    Console.WriteLine("{0} elements: GZip compression FAILURE", length);

                var dataBr = ReadFile(compressedBrotli, DecompressBrotli);
                if (CompareArrays(data, dataBr))
                    Console.WriteLine("{0} elements: Brotli compression is correct", length);
                else
                    Console.WriteLine("{0} elements: Brotli compression FAILURE", length);
            }
        }
    }

## Infinite Recursion
FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_AccessViolationException

   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.Reflection.AssemblyName.nInit(System.Reflection.RuntimeAssembly ByRef, Boolean)
   at System.Reflection.AssemblyName..ctor(System.String)
   at System.Resources.ManifestBasedResourceGroveler.CanUseDefaultResourceClasses(System.String, System.String)
   at System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(System.IO.Stream, System.Reflection.Assembly)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.AccessViolationException..ctor()
   at System.SR..cctor()
   at System.SR.get_ResourceManager()
   at System.SR.GetResourceString(System.String, System.String)
   at System.IO.Compression.BrotliStream.Read(System.Span`1<Byte>)
   at System.IO.Compression.BrotliStream.Read(Byte[], Int32, Int32)
   at System.IO.BinaryReader.FillBuffer(Int32)
   at System.IO.BinaryReader.ReadInt32()
   at Program.readFile[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Core.FSharpFunc`2<System.IO.FileStream,System.__Canon>, System.String)
   at Program.main(System.String[])

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #30584](https://github.com/dotnet/corefx/issues/30584) via [**ZenHub**](https://www.zenhub.com/)
