### ISSUE TITLE
X509Certicate2 error open pfx file without password on Mac OSX

### ISSUE THREAD

**Issue by ficnar** [dotnet/core#1813]
### X509Certicate2 error open pfx file without password on Mac OSX

Creating a X509Certificate2 instance from a byte array from pfx/p12 file that not secure by password, throw exception:

Interop+AppleCrypto+AppleCommonCryptoCryptographicException: MAC verification failed during PKCS12 import (wrong password?)
   at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)

This problem occurs only on Mac OSX. On Windows and Linux work fine.
I try it on .NET Core 2.0.0.

**Comment by joshfree** [comment]
Hi @ficnar, I've moved this issue to the dotnet/corefx repo where System.Security.Cryptography lives.  The new issue is https://github.com/dotnet/corefx/issues/31328.  Thanks
