### ISSUE TITLE
Access to the path 'C:\WINDOWS\system32\config\systemprofile' is denied.

### ISSUE THREAD

**Issue by ZackTech** [dotnet/core#1890]
Access to the path 'C:\WINDOWS\system32\config\systemprofile' is denied.

I had .net Core 2.0 running on our server. I have just installed .Net Core 2.1 and redeployed my WebApi and on IIS and now I get the following in a Log File:

System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\config\systemprofile' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSentinel.Create()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

How do I fix this?

**Comment by ZackTech** [comment]
I gave IIS_IUSRS  Read/Write access to: 'C:\WINDOWS\system32\config\systemprofile' 
now in the log file I get:

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
No executable found matching command "dotnet-.\Crm.WebApi.dll"

I have run the command  'dotnet dev-certs https --trust'  and the certificate is already installed.

Everytime I try to get the Web Api to run I get No executable found matching command "dotnet-.\Crm.WebApi.dll"

**Comment by Petermarcu** [comment]
This looks like the first run experience that write some sentinel files to know whether it has run before. Moving to the CLI repo.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #9941](https://github.com/dotnet/cli/issues/9941) via [**ZenHub**](https://www.zenhub.com/)
