### ISSUE TITLE
2.1 Web publish to Azure does not see Data Contexts or support EF migrations

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/core#1911]
# Issue Title
2.1 Web publish to Azure does not see Data Contexts or support EF migrations

# General
I have MVC app that targets netcoreapp2.0 and publishes to Azure.  Opening the Publish -> Configure -> Settings, it searches for Data Contexts, finds them, and presents me the option to apply EF migrations, per Data Context, and supply the respective connection string.

I updated the app to target netcoreapp2.1.  I open Publish -> Configure and change the Target Framework to netcoreapp2.1.  Going to settings, it does not find any Data Contexts.  If I manually edit ... - Web Deploy.pubxml.user and add the previous <ItemGroup> with <EFMigrations>, the publish fails, with the following error:

System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

===================

**Comment by Eilon** [comment]
@vijayrkn - any idea where this issue should go?
