### ISSUE TITLE
Issue with transactions in weird conditions

### ISSUE THREAD

**Issue by ctrl-alt-d** [dotnet/core#1950]
# Issue with transactions in weird conditions

When, into a transaction, you query a model with no data and the result is chained through union with other enum, the reader don't ends and commit transaction raises error:

>Error: System.Data.SqlClient.SqlException (0x80131904): The transaction operation cannot be performed because there are pending requests working on this transaction.

## The code snipped:
```
int q = 5;
var values = context
            .MyModels
            .Where(x=>x.MyProperty<q)
            .Select(x => x.MyProperty)
            //.ToArray()
            .Union(new int[] { 1 })                    // <-- this
            ;
foreach (var v in values)
{
    //
}
context.SaveChanges();
transaction.Commit();
```

# General

## Steps to reproduce:

* Download and unzip [tx.zip](https://github.com/dotnet/core/files/2400314/tx.zip) code and fix connection string (hardcoded for twice)
* Update database `dotnet ef database update`
* Run `dotnet run`

Notice it runs if you insert a single value on database or just if you comment out the union (`.Union(new int[] { 1 })`).

## Versions:
```
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.3" />
```

## Full trace error:
```
$ dotnet run
Error: System.Data.SqlClient.SqlException (0x80131904): The transaction operation cannot be performed because there are pending requests working on this transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   at System.Data.SqlClient.SqlInternalTransaction.Commit()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at tx.Program.Main(String[] args) in /home/dani/tmp/tx/Program.cs:line 69
ClientConnectionId:a3de2e0d-bb2e-42d7-b4b7-869e2ee511db
Error Number:3981,State:1,Class:16
```
##Workaround
Force execute query:
```
var values = context
            .MyModels
            .Where(x=>x.MyProperty<q)
            .Select(x => x.MyProperty)
            .ToArray()     // <-- this
            .Union(new int[] { 1 })                    
            ;
```

**Comment by ctrl-alt-d** [comment]
My bad, it's a [EF Core issue](https://github.com/aspnet/EntityFrameworkCore/issues/13377)
