### ISSUE TITLE
Cannot assign requested address exception

### ISSUE THREAD

**Issue by gstrit** [dotnet/core#2008]
# Issue Title

"Cannot assign requested address" during communication between two services.

# General

I have a set of services (core 2.1.5) which are launched with Docker Swarm. For two of them, I have communication issue after some time after startup.
I don't have issues the others services.
So basically, I have : 
Service A -> Service B
At startup, everything is fine.
After some hours, I receive this exception.
If I restart the Service container, it works during few hours...

# Exception

```json
{
  "Depth": 0,
  "ClassName": "",
  "Message": "Cannot assign requested address",
  "Source": "System.Net.Http",
  "StackTraceString": "   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
at System.Threading.Tasks.ValueTask`1.get_Result()
at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Threading.Tasks.ValueTask`1.get_Result()
at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
at System.Threading.Tasks.ValueTask`1.get_Result()
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at ServiceClients.TransportProcessingServiceClient.TransportProcessingServiceClient.PostFileAsync(FileContentViewModel fileContentViewModel, Guid transportConfigurationId, Guid retailerId, Guid contextId, CancellationToken cancellationToken, ILogger logger)
at TriggerManagementService.Infrastructure.Executors.ExportTradeItemImageActionExecutor.DoExecute(ExportTradeItemImageAction action) in /src/TriggerManagementService/Infrastructure/Executors/ExportTradeItemImageActionExecutor.cs:line 92
at TriggerManagementService.Infrastructure.Executors.ActionExecutor`2.Execute(T action, Dictionary`2 parameters) in /src/TriggerManagementService/Infrastructure/Executors/ActionExecutor.cs:line 49",
  "RemoteStackTraceString": "",
  "RemoteStackIndex": -1,
  "HResult": -2147467259,
  "HelpURL": null
},
{
  "Depth": 1,
  "ClassName": "",
  "Message": "Cannot assign requested address",
  "Source": "System.Private.CoreLib",
  "StackTraceString": "   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)",
  "RemoteStackTraceString": "",
  "RemoteStackIndex": -1,
  "HResult": -2147467259,
  "HelpURL": null
}
```

**Comment by karelz** [comment]
Which OS do you run on?
It seems like there are no available ports on the system. Can you check the OS stats at the point of failure? Can you check your container configuration?
Once it happens (after few hours) - does it happen once / all the time / most of the time?

**Comment by gstrit** [comment]
Sorry my mistake I found the issue. The service sent a stream as a response and I did not close it.
