### ISSUE TITLE
The Uri string is too long (netcore2.0)

### ISSUE THREAD

**Issue by liuweizzuie** [dotnet/core#2055]
hello  there, 
I'm back again.

I hate to write the params in url, but some evil servers require me to.

here's the server's doc:
```
POST https://api.netease.im/nimserver/msg/upload.action HTTP/1.1
Content-Type:application/x-www-form-urlencoded;charset=utf-8
```

it's really, really evil to upload a file with urlencoded. 

I wondered if  I can put the stream in the http body, but the server returned 400 and say the content is empty.

I don't have other choice but to put the file in the url.

![image](https://user-images.githubusercontent.com/2696315/48457544-17b13900-e7fe-11e8-97f8-f5d710a305c1.png)

it says you can upload a file max to 15M, my God!

I tried to upload a small file no more than 5K, it works fine, but when the file is bigger,  HttpClient throws an exception as follows:

```
$exception	{System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.Net.Http.HttpClient.CreateUri(String uri)
   at System.Net.Http.HttpClient.PostAsync(String requestUri, HttpContent content)
```

```
HttpClient client = new HttpClient();
client.BaseAddress = new Uri(this.BaseAddress);
HttpContent httpContent = BuildContent(headers, body);
Task<HttpResponseMessage> tsk = client.PostAsync(relativeUrl, httpContent);
```

so I need a little help to put a stream max to 15M in the url,  it sounds crazy, but  it's real.

**Comment by liuweizzuie** [comment]
I find the solution in [StackOverflow](https://stackoverflow.com/questions/38440631/httpclient-the-uri-string-is-too-long).

because I build a StreamContent, It can't work. then I build a StringContent, it works fine.

thanks.
