### ISSUE TITLE
Unable to dotnet restore from a private VSTS feed w/ SDK 2.1.500

### ISSUE THREAD

**Issue by jarz** [dotnet/core#2057]
# Unable to dotnet restore from a private VSTS feed

In Azure DevOps (VSTS) I'm unable to use the latest SDK (2.1.500) to build my project, as it relies upon a package in my private feed. However, if I use SDK 2.1.403 the build succeeds.

I see a `401 Unauthorized` in the log. My account has the _Package Management_ license assigned (and it'd be a `402 Payment Required` if I didn't).

I use the .NET Core Installer task at the beginning of my build pipeline.

Log: https://gist.github.com/jarz/56d3ec2b0e3c1417a1c01168408d32bd

**Comment by karelz** [comment]
What is the Azure DevOps environment? Are you able to reproduce it in isolation / locally?
Is there any proxy set up there?

If you don't know the answer or if you are unable to isolate the repro to local environment, I would suggest to contact Azure DevOps support first.

**Comment by jarz** [comment]
`dotnet restore` works fine locally. 

Considering the build works if I use 2.1.403 instead of 2.1.500, there must be a breaking change somewhere...

**Comment by karelz** [comment]
Possibly (there could be some misconfiguration which just "happened to work by accident").
The key is narrowing down what triggers the problem. Without that information it is not actionable :(

**Comment by jemmfi** [comment]
I have the same problem. "dotnet restore" fails, if my .NET Core Tool Installers installs Core SDK 2.1.500 (this is in Azure DevOps / cloud).

When I change the Code SDK version to  2.1.403, the same pipeline works with no other changes. This happens in two different build pipelines that I have tried. However, nuget.org -packages are restored normally.

The error with 2.1.500:
2018-11-16T05:21:02.3133383Z        (Restore target) -> 
2018-11-16T05:21:02.3133631Z          C:\hostedtoolcache\windows\dncs\2.1.500\x64\sdk\2.1.500\NuGet.targets(114,5): error : Unable to load the service index for source **{private feed}**/nuget/v3/index.json. 
2018-11-16T05:21:02.3133798Z        C:\hostedtoolcache\windows\dncs\2.1.500\x64\sdk\2.1.500\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). 

Stack trace:
2018-11-16T05:21:02.3017453Z          NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source {private feed}/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
2018-11-16T05:21:02.3018087Z             at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2018-11-16T05:21:02.3018510Z             at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
2018-11-16T05:21:02.3018970Z          --- End of stack trace from previous location where exception was thrown ---
2018-11-16T05:21:02.3019302Z             at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
2018-11-16T05:21:02.3019667Z             at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
2018-11-16T05:21:02.3020025Z             at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
2018-11-16T05:21:02.3020355Z             --- End of inner exception stack trace ---
2018-11-16T05:21:02.3020683Z             at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
2018-11-16T05:21:02.3021031Z             at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
2018-11-16T05:21:02.3023988Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
2018-11-16T05:21:02.3024143Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
2018-11-16T05:21:02.3024853Z             at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
2018-11-16T05:21:02.3025091Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
2018-11-16T05:21:02.3025466Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
2018-11-16T05:21:02.3025570Z             at NuGet.Commands.SourceRepositoryDependencyProvider.EnsureResource()
2018-11-16T05:21:02.3025680Z             at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
2018-11-16T05:21:02.3025808Z             at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
2018-11-16T05:21:02.3025915Z          --- End of stack trace from previous location where exception was thrown ---
2018-11-16T05:21:02.3026047Z             at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
2018-11-16T05:21:02.3026178Z             at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass7_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
2018-11-16T05:21:02.3026271Z          --- End of stack trace from previous location where exception was thrown ---
2018-11-16T05:21:02.3026380Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryFromSourcesAsync(LibraryRange libraryRange, IEnumerable`1 providers, Func`2 action)
2018-11-16T05:21:02.3026499Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryByVersionAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 providers, SourceCacheContext cacheContext, ILogger logger, CancellationToken token)
2018-11-16T05:21:02.3026733Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, GraphEdge`1 outerEdge, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, IEnumerable`1 projectProviders, IDictionary`2 lockFileLibraries, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
2018-11-16T05:21:02.3026909Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryEntryAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, GraphEdge`1 outerEdge, RemoteWalkContext context, CancellationToken cancellationToken)
2018-11-16T05:21:02.3027038Z             at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge)
2018-11-16T05:21:02.3027188Z             at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge)
2018-11-16T05:21:02.3027331Z             at NuGet.Commands.ProjectRestoreCommand.WalkDependenciesAsync(LibraryRange projectRange, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, RemoteDependencyWalker walker, RemoteWalkContext context, CancellationToken token)
2018-11-16T05:21:02.3027493Z             at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable`1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity)
2018-11-16T05:21:02.3027655Z             at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
2018-11-16T05:21:02.3028163Z             at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
2018-11-16T05:21:02.3028348Z             at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2018-11-16T05:21:02.3028465Z             at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2018-11-16T05:21:02.3028558Z             at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
2018-11-16T05:21:02.3028671Z             at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
2018-11-16T05:21:02.3028781Z             at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
2018-11-16T05:21:02.3028882Z             at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)
