### ISSUE TITLE
Linked files in Resource-files don't seem to work on Linux hosts or in Docker

### ISSUE THREAD

**Issue by tomeo** [dotnet/core#2061]
I am on Windows 10 (10.0.17134 N/A Build 17134) and dotnet Version: 2.1.5, Commit:  290303f510.

I have published a small git repository which details my problem 
https://github.com/tomeo/dotnet-core-resource-files-example

In essence I am trying to grab the contents from a JSON-file which I have placed in a Resource file. This works fine when I run dotnet on Windows. However as soon as I run my application through Docker or on a Linux host it does not work.

Steps to reproduce:
1. On Windows Run
```
dotnet run --project ResourceFilesExample\ResourceFilesExample.csproj
```
which has, what I consider, the correct output
```
Resource file test
{
  "test": "test"
}
```
2. Then run the same application via Docker
```
docker build -t rfe .
docker run rfe
```
which has, what I consider, incorrect output
```
Resource file test

Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Byte[]'.
   at ResourceFilesExample.Resource.get_example() in /app/ResourceFilesExample/Resource.Designer.cs:line 68
   at ResourceFilesExample.Program.Main(String[] args) in /app/ResourceFilesExample/Program.cs:line 10
```

Please advise if there is any further information I could provide that would be helpful. Thanks!

**Comment by karelz** [comment]
Related code:

https://github.com/tomeo/dotnet-core-resource-files-example/blob/master/ResourceFilesExample/Resource.Designer.cs#L66-L71
```c#
        internal static byte[] example {
            get {
                object obj = ResourceManager.GetObject("example", resourceCulture);
                return ((byte[])(obj));
            }
        }
```

https://github.com/tomeo/dotnet-core-resource-files-example/blob/master/ResourceFilesExample/Resource.resx#L120-L123
```xml
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="example" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>example.json;System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
```

@tarekgh @ViktorHofer can you please help me route it? Is System.Windows.Forms available on Linux?

**Comment by tarekgh** [comment]
@nguerrera is this related to Microsoft/msbuild#2221?

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/issues/12565

**Comment by tarekgh** [comment]
@nguerrera could you please answer the question https://github.com/dotnet/core/issues/2061#issuecomment-439537179? thank you!

**Comment by tarekgh** [comment]
@rainersigwald this issue is the same https://github.com/Microsoft/msbuild/issues/2221, right? do you know when this will be fixed in msbuild?

**Comment by karelz** [comment]
Duplicate of https://github.com/Microsoft/msbuild/issues/2221

**Comment by karelz** [comment]
FYI: See the syntax above which GitHub recognizes for duplicates ;) (unfortunately any other comment in that post will break it :()

**Comment by tarekgh** [comment]
CC @maryamariyan
