### ISSUE TITLE
DllNotFoundException with incorrect dll name

### ISSUE THREAD

**Issue by no1melman** [dotnet/core#2096]
# Issue Title

DllNotFound Exception trying to load a dylib, the exception shows `dlopen` with incorrect library name.

I don't know if this is the write place for this, but it is using .NET Core on MacOS (see .NET core information below)

See this [issue](https://github.com/confluentinc/confluent-kafka-dotnet/issues/688) for repro. I ended up cloning the project and running the consumer example (you don't need kafka at all, unless you get past the dll load stage).

# General

It seems when using `[DLLImport(DllName, CallingConvention.Cdecl)]` there is an exception thrown:

```
System.DllNotFoundException: Unable to load shared library 'librdkafka' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibrdkafka, 1): image not found
   at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_err2str(ErrorCode err)
   at Confluent.Kafka.Impl.Librdkafka.SetDelegates(Type nativeMethodsClass) in /code/confluent-kafka-dotnet/src/Confluent.Kafka/Impl/LibRdKafka.cs:line 297
```

You can see in that `dlopen(liblibrdkafka, 1): image not found`, why is it liblibrdkafka when the `public const string DllName = "librdkafka"`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by no1melman** [comment]
So the only thing left that is relevant here is the `dlopen(liblibrdkafka, 1): image not found`

**Comment by karelz** [comment]
@no1melman I am a bit confused - what exactly is it you're expecting vs. what happens today?

cc @janvorli @jeffschwMSFT

**Comment by no1melman** [comment]
I was using the kafka dotnet library, and it has to import the librdkafka dll using `[DLLImport(DllName, CallingConvention.Cdecl)]` however, due to some other issues it couldn't load the dll giving this error `dlopen(liblibrdkafka, 1): image not found` clearly that is incorrect `liblibrdkafka` it should just be `librdkafka` so I think there is a bug somewhere. The fact the dll wasn't loading is irrelevant now, I got that working. It is just interesting to see the error message somehow incorrectly displaying library name

**Comment by karelz** [comment]
I believe there are a few prefixes and suffixes we try for `DllImport` on Linux, incl. "lib" prefix and ".so" suffix.
@janvorli @jeffschwMSFT may know more.

**Comment by karelz** [comment]
@janvorli @jeffschwMSFT post holidays ping ...

**Comment by dancojocaru2000** [comment]
Hello! I have a similar issue.

I have a library called `libATESTAT_dtdb.dylib` on macOS.  
If I use this name, the error I get is `dlopen(liblibATESTAT_dtdb.dylib.dylib, 1): image not found"`

If I try different combinations, whenever I add `lib` at the beginning, it gets doubled. Whenever I add `.dylib` at the end, it gets doubled. However, if I just import `ATESTAT_dtdb`, it doesn't add `lib` nor `.dylib` and also fails.

**Comment by Andrey1994** [comment]
It seems like I have the same issue - https://github.com/brainflow-dev/brainflow/issues/683, I doubt that its correct to try to add "lib" or "dylib" if its manually specified(like in my case) or at least error message can be improved.

I still dont understand did it try to load correct lib as specified in DllImport or tried to load smth with extra words appended automatically. This says https://learn.microsoft.com/en-us/dotnet/standard/native-interop/native-library-loading that should try all combinations but error msg doesnt look so

**Comment by Andrey1994** [comment]
I gor it working on linux by specifing it like %libname%.so and it adds "lib" automatically and works, but on macos it either adds .so instead dylib either doubles "lib"
