### ISSUE TITLE
HttpClient Unhandled Exception, Centos 7, .NET CORE 2.2

### ISSUE THREAD

**Issue by logwlogw** [dotnet/core#2103]
# HttpClient Unhandled Exception

An error even in try catch with 

1. ONLY with one site indianetzone.com
2. win10 - works 
3. AppContext.SetSwitch ("System.Net.Http.UseSocketsHttpHandler", false); - works

What could be a problem, thank you.

# Simple Code
------------
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace ConsoleApp18
{
    class Program
    {
        static async Task Main(string[] args)
        {

            using (var http = new HttpClient())
            {
                try
                {
                    var data =await http.GetStringAsync("http://indianetzone.com");
                    Console.WriteLine(data.Length);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }

            Console.ReadLine();
        }
    }
}
-------------

[root@server publish]# dotnet ConsoleApp18.dll

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException
                          : Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted

**Comment by logwlogw** [comment]
**For WebAPI, Example**

using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AllSubmitterServer.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class CrachController : ControllerBase
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public CrachController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public async Task<ActionResult> Get()
        {
            var client = _httpClientFactory.CreateClient();

            try
            {
                string result = await client.GetStringAsync("http://indianetzone.com");
                return Ok(result);
            }
            catch (Exception e)
            {
                return Ok(e.Message);
            }

            
        }

    }
}

**Comment by logwlogw** [comment]
https://github.com/dotnet/corefx/issues/33857
