### ISSUE TITLE
Issue: 'Exception has occurred: CLR/System.Net.Sockets.SocketException'

### ISSUE THREAD

**Issue by johnmelodyme** [dotnet/core#2137]
I am planning of deploy my API to my server and error happen.

My source: 

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace johnTestBO
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            //Open to loop back localhost
            //  .UseKestrel(options =>
            // {
            //    options.Listen(IPAddress.Loopback, 5001);       
                .UseStartup<Startup>();
            // })
    }
}
```
![sdfgj](https://user-images.githubusercontent.com/44691957/49858885-18ef7900-fe31-11e8-89e3-1892e57d7bd6.png)

The error after I run it in ssh and visual.

```
Exception has occurred: CLR/System.Net.Sockets.SocketException
An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.Private.CoreLib.dll: 'Cannot assign requested address'
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.<BindAsync>d__43.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.<BindAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StartAsync>d__21`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at johnTestBO.Program.Main(String[] args) in /home/sabrina/Downloads/example/johnTestBO/Program.cs:line 18
```

With screenshot attached:
Any idea? Because I am not so familiar with C#.
btw , I'm ubuntu 18 user

**Comment by karelz** [comment]
@tmds @wfurt can you please help here?

**Comment by wfurt** [comment]
Does it happen only when running in visual studio @johnmelodyme? Check that you don't have another copy running in background.

**Comment by johnmelodyme** [comment]
> Does it happen only when running in visual studio @johnmelodyme? Check that you don't have another copy running in background.


No sir, there's nothing running in the background.

**Comment by johnmelodyme** [comment]
@karelz (More info)

First when I deploy the API to the localhost:5001, all work fine until I put everything together in the server. I did `dotnet publish` the project. before this I `sudo scp - r` the (all files) relevant project to the server's `/home` . `dotnet build && dotnet run`, and all work fine. I  came to mind that that wasn't a good idea for uploading all files without compounding it. Then I did only upload the 'Publish' folder which had already a 'compound' . As soon as I `dotnet build && dotnet run` it in my Visual prompted this error.



Sources: 

From the server(using Termius(no longer using puTTY)-Ubuntu):
![12367890-](https://user-images.githubusercontent.com/44691957/49910054-41708500-febc-11e8-9c2e-513125fe2b1a.png)


From My Visual Code Studio:
![2](https://user-images.githubusercontent.com/44691957/49910346-4e41a880-febd-11e8-9699-4e03cd5e4e44.png)

I clicked Debug anyway
then this prompt came.

![3](https://user-images.githubusercontent.com/44691957/49910350-5994d400-febd-11e8-9032-81e91164b566.png)


Thank you.

**Comment by johnmelodyme** [comment]
> @karelz @wfurt @radical @shanselman
> 
> First when I deploy the API to the localhost:5001, all work fine until I put everything together in the server. I did `dotnet publish` the project. before this I `sudo scp - r` the (all files) relevant project to the server's `/home` . `dotnet build && dotnet run`, and all work fine. I came to mind that that wasn't a good idea for uploading all files without compounding it. Then I did only upload the 'Publish' folder which had already a 'compound' . As soon as I `dotnet build && dotnet run` it in my Visual prompted this error.
> 
> Sources:
> 
> From the server(using Termius(no longer using puTTY)-Ubuntu):
> ![12367890-](https://user-images.githubusercontent.com/44691957/49910054-41708500-febc-11e8-9c2e-513125fe2b1a.png)
> and also prompted
> 
> > "MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file."
> 
> From My Visual Code Studio:
> ![2](https://user-images.githubusercontent.com/44691957/49910346-4e41a880-febd-11e8-9699-4e03cd5e4e44.png)
> 
> I clicked Debug anyway
> then this prompt came.
> 
> ![3](https://user-images.githubusercontent.com/44691957/49910350-5994d400-febd-11e8-9032-81e91164b566.png)
> 
> Thank you.

I'm sorry my bad. I didn't see there's something after the `{` tag.

**Comment by tmds** [comment]
@johnmelodyme an example:

Create a web webapplication
```
dotnet new web -o webapp
cd webapp
```
Publish it:
```
dotnet publish -c Release
```
Copy the publish folder to your server (`/tmp/myserver` represents a folder on the server):
```
cp -r bin/Release/netcoreapp2.2/publish /tmp/myserver
```
On the server:
```
cd /tmp/myserver
ASPNETCORE_URLS=http://*:8080 dotnet webapp.dll
```

* you mustn't use `dotnet run` on your server, that command is for development.
* use the `ASPNETCORE_URLS` environment variable to configure the binding address

**Comment by johnmelodyme** [comment]
Thanks for the help sir.

**Comment by johnmelodyme** [comment]
@tmds thanks for the tutorial sir.

**Comment by johnmelodyme** [comment]
![11111](https://user-images.githubusercontent.com/44691957/49929473-836deb00-fefd-11e8-976c-3d6ae8cceee8.png)



It worked sir, but my supervisor, accidentally did something to my script. 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace johnTestBO.Controllers{
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            Console.WriteLine("asdf");
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            return "value";
        }

        // POST api/values
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}




''According to visual i got 136 error in just this code. OMG"

**Comment by tmds** [comment]
> It worked sir

Great!

> ''According to visual i got 136 error in just this code. OMG"

Take some time to learn to understand the IDE and compiler. Start from a working version and see when it starts to fail. Version control can be helpful to help you keep track of things that work.

Can you close the issue?

**Comment by johnmelodyme** [comment]
Sure.
