### ISSUE TITLE
.NET Core 3.0 Preview 1 makes app fail to start

### ISSUE THREAD

**Issue by godrose** [dotnet/core#2160]
# Issue Title

Using latest version of .NET Core 3.0.0 SDK (009812) introduces regression into an existing app

# General

Upgrading to the preview version and using it instead of 2.2.0 results in the following exception during app start:
```
Application startup exception: System.InvalidOperationException: Scheme already exists: ASOS
   at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action1 configureBuilder)
   at Microsoft.Extensions.Options.OptionsFactory1.Create(String name)
   at System.Lazy1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy1.CreateValue()
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions1 options, IDictionary2 schemes)
```

**Comment by godrose** [comment]
I'm using OpenId.Connect in my app
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/210

**Comment by karelz** [comment]
Do you have a minimal repro for ASP.NET team?

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetCore#5700
