### ISSUE TITLE
Why does DisablePrivateReflection attribute not work on .net core 2.1, but works perfectly on .net core 2.0?

### ISSUE THREAD

**Issue by monokot** [dotnet/core#2225]
Hello!

Why does `DisablePrivateReflection` attribute not work on .net core 2.1, but works perfectly on .net core 2.0?

I have a class with private fields. The class is in assembly marked with a `DisablePrivateReflection` attribute.

The following test will be passed successfully on .net core 2.0

```csharp
var field = typeof(MonLicenseManager).GetField("_licenses", BindingFlags.NonPublic | 
BindingFlags.Static);

Assert.IsNotNull(field);

try
{
    var value = field.GetValue(null);
    Assert.Fail("FieldAccessException must be thrown");
}
catch (FieldAccessException)
{

}
```

but on .net core 2.1, `FieldAccessException` will never be thrown

Thanks

**Comment by karelz** [comment]
That seems like the attribute actually does not work on 2.0, but works correctly ans as expected in 2.1.
That seems like by design technical breaking change to me.

@steveharter cc @joshfree

**Comment by steveharter** [comment]
I verified that it did work in 2.0.

It appears that there used to be a call to `PerformVisibilityCheckOnField` which was removed with https://github.com/dotnet/coreclr/pull/13241. That PR appears to address part of CAS removal issue https://github.com/dotnet/coreclr/issues/9321.

In 2.0, the call stack would look like this:
```
Unhandled Exception: System.FieldAccessException: Attempt by method 'test.Program.Main(System.String[])' to access field 'test.Foo.i' failed.
   at System.Reflection.RtFieldInfo.PerformVisibilityCheckOnField(IntPtr field, Object target, RuntimeType declaringType, FieldAttributes attr, UInt32 invocationFlags)
   at System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
```

@jkotas @danmosemsft is this expected per the removal of the CAS issue?

**Comment by jkotas** [comment]
This was not expected. We should keep respecting the `DisablePrivateReflection` attribute.
