### ISSUE TITLE
Can't create new project in proot system

### ISSUE THREAD

**Issue by YadominJinta** [dotnet/core#2271]
I am using fedora installed in termux on Android with [Atilo](https://github.com/YadominJinta/atilo). I fellow the instructions and installed the dotnet core 3.0 preview 2.  

After solved the dependencies , it runed successfully,but when I run `dotnet new Hello`,it returned no enough storage error.

``` bash
dotnet new Hello

System.IO.IOException: Not enough storage is available to process this command. : '5cb26fd1-32db-4f4c-b3dc-49cfd61633d2-dotnetcli-v3.0.100-preview-010184'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.TemplateEngine.Cli.New3Command.EnsureEntryMutex(String hivePath, ITemplateEngineHost host)
   at Microsoft.TemplateEngine.Cli.New3Command.Run(String commandName, ITemplateEngineHost host, ITelemetryLogger telemetryLogger, Action`2 onFirstRun, String[] args, String hivePath)
   at Microsoft.TemplateEngine.Cli.New3Command.Run(String commandName, ITemplateEngineHost host, ITelemetryLogger telemetryLogger, Action`2 onFirstRun, String[] args)
   at Microsoft.DotNet.Tools.New.NewCommandShim.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
However,the space is enough.
``` bash 
df -h
Filesystem       Size  Used Avail Use% Mounted on
/dev/block/dm-0   25G   13G   12G  53% /data
tmpfs            1.4G  136K  1.4G   1% /dev
none             1.4G     0  1.4G   0% /sys/fs/cgroup
```
Could you tell me why? I really want to use dotnet core on my Android device.

**Comment by omajid** [comment]
If there's a chroot involved, a `strace` log of `dotnet new console` would be really nice to have. We have seen failures involving a chroot before, such as https://github.com/dotnet/coreclr/issues/18634

**Comment by leecow** [comment]
re termux support - there's no work planned to specifically support the environment.

**Comment by john-peterson** [comment]
when I searched for dotnet proot io exception I found this page and I will post my solution here if anyone else has the same question 

the following three sections  are solutions for everyone that use  Ubuntu proot


- []  missing /etc/passwd crash temp folder creation 
- []  respect virtual memory limit in proot
- []  don't disable \e[A terminal key 


some bugs might  be fixed in version ten this applies to version eight in Ubuntu noble with updates disabled 

~~~
vim /etc/apt/sources.list.d/ubuntu.sources
URIs: http://ports.ubuntu.com/ubuntu-ports
Suites: noble  noble-backports
# Suites: noble noble-updates noble-backports noble-security
~~~


# don't fail on missing /etc/passwd when creating temp folder 

the solution is to create /etc/passwd file 

~~~
vim /etc/passwd
u0_a204:x:10204:10204::/home:/bin/bash
~~~

user info is from id command 

~~~
id
uid=10204(u0_a204) gid=10204 groups=10204,1007,1077,1079,3003,9997,20204,50204
~~~

useradd doesn't work in proot

~~~
useradd -u 10204 u0_a204
Cannot open audit interface - aborting.
~~~


you can also bypass this bug by running /data/data/com.termux/ubuntu/bin/dotnet from termux glibc proot . in that root it works without any passwd file


this happens in Ubuntu proot when /etc/passwd is missing 

~~~
dotnet build /v:diag
02:07:04.438     0>Process = "/data/data/com.termux/files/usr/libexec/proot/loader"
MSBuild executable path = "/usr/lib/dotnet/sdk/8.0.111/MSBuild.dll"
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Unhandled exception: System.IO.IOException: No such file or directory
   at Interop.Sys.TryGetUserNameFromPasswd(UInt32 uid, Byte* buf, Int32 bufLen, String& username)
   at Interop.Sys.GetUserNameFromPasswd(UInt32 uid)
   at System.Environment.get_UserName()
   at Microsoft.Build.Shared.FileUtilities.CreateFolderUnderTemp() in /_/src/msbuild/artifacts/source-build/self/src/src/Shared/TempFileUtilities.cs:line 39
~~~



# respect  proot virtual memory limit  

this is also necessary in Ubuntu proot 

~~~
export DOTNET_GCHeapHardLimit=40000000
~~~

otherwise it fails with not enough memory 

~~~
GC heap initialization failed with error 0x8007000E
~~~



# dotnet disable bash readline up key \e[A 

this happens in my  Ubuntu proot in termux in tmux 

the solution is to bind both up key versions 

~~~
vim ~/.inputrc
"\e[A": history-search-backward
"\eOA": history-search-backward
~~~

dotnet completely disable the first form . any attempt to bind it again fail

~~~
bind '"\e[A": history-search-backward'
~~~

any dotnet app or command has this effect for example dotnet help or any compiled app 

the only way to get it back is reset command
