### ISSUE TITLE
Introduce Http over arbitrary streams

### ISSUE THREAD

**Issue by simonferquel** [dotnet/core#2312]
# Summary

This issue is about contributing back support for HTTP over arbitrary streams (named pipe, unix socket, ...) that we use internally for Docker Desktop to .net core libraries.

# Context

I am part of the team building Docker Desktop, and we are in the process of refactoring it to share as much code as possible between Mac and Windows. To align with the company practices, we are using golang for all shared components, and use HTTP over Unix sockets (on Mac) or Named Pipes (on Windows) for IPC. We have extensive experience with Golang for this development model, and so far it has been a success: as an example, Docker Engine API is an HTTP/REST API that can be exposed to clients trough TCP/TLS, Unix sockets, Named pipes (and in the context of Docker Desktop, even trough v-socks or Hyper-V Sockets).

As part of this ongoing Docker Desktop refactoring, I wrote both an HttpClient MessageHandler (for the client side) and a ASP.Net core host (for server side) to support this architecture in C#. You can see an early version of that work here: https://github.com/simonferquel/HttpOverStream/tree/master/src

# What I want to do with it ?

I think support for this kind of architecture directly in the .net Core library would make for a great addition. 
- Users could use it easily for local IPC
- Could also be used for speeding up Unit Tests in large projects (with http clients/server using Http over an in-process Pipe)
- By having access to .net core internal classes, these components will have an improved behavior consistency compared to traditional HTTP/TCP case (if you have a look at https://github.com/simonferquel/HttpOverStream/tree/master/src/HttpOverStream, you'll see much code duplication coming from .net core and CoreFX internal classes, that is not easy to keep in sync with upstream versions).

As an interesting side effect, it would make things easier to build a .net Docker Client library, working with every kind of transport we support.

From the Docker Point of view, it would also be very interesting in term of maintenance costs: every time a bug fix or performance improvement is introduced in internal components shared with the current TCP-focused implementation (mainly the whole HTTP grammar handling), the arbitrary-stream handlers would get it for free (compared to the current model where we have to constantly watch for changes in this part of the code base - which we honestly don't do). Exposure to a broader developer audience and set of use cases would also help us making it more robust (both for us, and other developers).

# Questions to resolve

Where to write PRs:
- I suppose the client side should go there: https://github.com/dotnet/corefx/tree/master/src/System.Net.Http/src/System/Net/Http
- Server side support, I am not completely sure. We could ever make it as a separate server, or make it a new Kestrel feature
- I'd like also to have end-to-end tests, and validate things with cross-language tests: testing client interaction with a golang http server and testing the server with a golang client. Those end-to-end tests could easily be implemented using docker (so we don't require contributors to install a golang toolchain locally), but I have no idea were it could live in the .net core code base.

ping @karelz

**Comment by leecow** [comment]
@Eilon and @muratg for possible input on the server-side question.

**Comment by muratg** [comment]
+ @davidfowl for his opinions here.

**Comment by Eilon** [comment]
And cc @DamianEdwards

**Comment by davidfowl** [comment]
You can already do this on the server side with Kestrel, the custom transport. We already have support today via libuv for named pipes/unix sockets. We could add this support natively to the socket transport or write a named pipe transport.

**Comment by simonferquel** [comment]
That is actually really interesting. I will have a look at it.
Does Kestrel still run on .net Framework full btw? (Asking for docker desktop)

**Comment by simonferquel** [comment]
I guess I should only focus on the client side then

**Comment by muratg** [comment]
Kestrel 2.x is supported on .NET Framework ("full framework").
Kestrel 3.x will be only on .NET Core.

**Comment by karelz** [comment]
For client-side we can discuss with @geoffkizer @davidsh @wfurt @rmkerr @caesar1995 @stephentoub

**Comment by stephentoub** [comment]
On the client side, I see a few approaches:
1. You can do what you're already doing and write a custom HttpMessageHandler. That lets consumers use the HttpClient APIs over your custom handler/transport implementation, but as you say requires also implementing all of the HTTP logic.
2. Add an API like SocketsHttpHandler.ConnectCallback that's a `Func<Uri, Cancellation token, ValueTask<Stream>>` which if non-null SocketsHttpHandler would use instead of its internal ConnectHelper.ConnectAsync method. This in theory would allow SocketsHttpHandler to be used but with you stopping
3. Add

**Comment by simonferquel** [comment]
I think option 2 is indeed the best option. I will open a PR doing that. Thanks!

**Comment by stephentoub** [comment]
> I will open a PR doing that. 

Thanks, but API will need to be agreed upon first.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by simonferquel** [comment]
Sure, I will do it (maintaining the code in my own fork while the design is discussed).

**Comment by simonferquel** [comment]
CoreFX issue opened here: https://github.com/dotnet/corefx/issues/35404

**Comment by simonferquel** [comment]
@davidfowl just played a bit with libuv transport. I managed to use the ListenSocketPath method to create a namedpipe, but any request fails with: 
```
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[0]
      Listener.OnConnection
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4049 ENOTSUP operation not supported on socket
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.write2(UvRequest req, UvStreamHandle handle, uv_buf_t* bufs, Int32 nbufs, UvStreamHandle sendHandle, uv_write_cb cb)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvWriteReq.WriteArraySegmentInternal(UvStreamHandle handle, ArraySegment`1 bufs, UvStreamHandle sendHandle, Action`4 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary.DispatchConnection(UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)
```

**Comment by simonferquel** [comment]
I'll try to make a symetric issue/PR in SocketStream transport to fix that (and without having to rely on libuv)

**Comment by davidfowl** [comment]
@simonferquel Yes I don't think the libuv transport supports named pipes (it needs some tweaks) but it does support unix sockets. We'd need to write another transport for the stream based support. File an issue on https://github.com/aspnet/aspnetcore

**Comment by simonferquel** [comment]
@davidfowl the extension model for kestrel allows to do this in a separate package. should it live within the main kestrel code base then?

**Comment by davidfowl** [comment]
@simonferquel Ah I would start with a separate package for now but still file the issue because we've likely going to add unix socket support to the socket transport. Named pipes is less likely at least for this release.

**Comment by dovholuk** [comment]
Support for HTTP over arbitrary streams would be very much appreciated (by me any way).  I've left a comment on my SO post (https://stackoverflow.com/questions/56550481/parsing-raw-http-in-c-sharp-or-some-better-option)

Is this in-the-works? Any update?

**Comment by carlossanlop** [comment]
Moving to dotnet/corefx for higher visibility.
