### ISSUE TITLE
'DataTime' does not exist in Hello world

### ISSUE THREAD

**Issue by jimigrunge** [dotnet/core#2489]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/modify
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

### Details

On step 4 `Edit your code`. After entering the supplied code into Pages/Index.cshtml, I received the following error on the page after reloading the browser...

### Error

```
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
/Users/jgrundner/Repository/tutorials/myWebApp/Pages/Index.cshtml

The name 'DataTime' does not exist in the current context
+
<p>The time on the server is @DataTime.Now</p>
```

### Command line output

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Page: /Index'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Page: /Index'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
/Users/jgrundner/Repository/tutorials/myWebApp/Pages/Index.cshtml(8,31): error CS0103: The name 'DataTime' does not exist in the current context
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Internal.MvcEndpointDataSource.<>c__DisplayClass21_0.<CreateEndpoint>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.8922ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.ico'. Physical path: '/Users/jgrundner/Repository/tutorials/myWebApp/wwwroot/favicon.ico'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.4234ms 200 image/x-icon
```

### Environment
```
.NET Core SDK (reflecting any global.json):
    Version:   2.2.105
    Commit:    7cecb35b92

Runtime Environment:
    OS Name:     Mac OS X
    OS Version:  10.13
    OS Platform: Darwin
    RID:         osx.10.13-x64
    Base Path:   /usr/local/share/dotnet/sdk/2.2.105/

Host (useful for support):
    Version: 2.2.3
    Commit:  6b8ad509b6

.NET Core SDKs installed:
    2.2.105 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
    Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by peterhuene** [comment]
Hi @jimigrunge.

I believe your code contains a typo.  The sample has this:

```html
<p>The time on the server is @DateTime.Now</p>
```

And your error message suggests you copied this as `... @DataTime.Now...`.

Correcting `@DataTime.Now` to `@DateTime.Now` should resolve your issue.

**Comment by jimigrunge** [comment]
AH, a Fat Finger issue. Thank you
