### ISSUE TITLE
System.Runtime.CompilerServices.IAsyncStateMachine (Linux)

### ISSUE THREAD

**Issue by Bradleyay** [dotnet/core#2584]
## System.Runtime.CompilerServices.IAsyncStateMachine

# General

When I try to test out my dot net program on a Linux Server (Ubuntu 18.04), I receive this error out of no where. I don't know what's causing it and how I can fix it. Help would be highly appreciated, I've been trying to figure out what causes this error for days.

**SDK Version:** 2.2.105

```
System.Reflection.TargetInvocationException: Exception has been thrown by the targe                         t of an invocation. ---> System.TypeLoadException: Could not load type 'System.Runt                         ime.CompilerServices.IAsyncStateMachine' from assembly 'System.Runtime, Version=4.2                         .0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Task MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable<IOBehavior> io                         Behavior, CancellationToken cancellationToken)
   at void MySql.Data.MySqlClient.MySqlConnection.Open() in /home/test/ragemp/C:\p                         rojects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs                         :line 218
   at void Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnect                         ion(bool errorsExpected)
   at bool Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(bool err                         orsExpected)
   at bool Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enume                         rator.BufferlessMoveNext(DbContext _, bool buffer)
   at TResult Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrat                         egy.Execute<TState, TResult>(TState state, Func<DbContext, TState, TResult> operati                         on, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded)
   at bool Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enume                         rator.MoveNext()
   at TResult Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult<TRe                         sult>(IEnumerable<ValueBuffer> valueBuffers, bool throwOnNullResult)
   at IEnumerator<T> Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvi                         der+ResultEnumerable<T>.GetEnumerator()
   at bool Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+Except                         ionInterceptor<T>+EnumeratorExceptionInterceptor.MoveNext()
   at TSource System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> sour                         ce, out bool found)
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at Func<QueryContext, TResult> Microsoft.EntityFrameworkCore.Query.Internal.Quer                         yCompiler.CompileQueryCore<TResult>(Expression query, IQueryModelGenerator queryMod                         elGenerator, IDatabase database, IDiagnosticsLogger<Query> logger, Type contextType                         )+(QueryContext qc) => { }
   at int System.Linq.Queryable.Count<TSource>(IQueryable<TSource> source)
   at void Test.Main.OnResourceStart()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Si                         gnature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[]                          parameters, Object[] arguments)
   at GTANetworkInternals.ScriptingEngine.InvokeVoidMethod(String method, Object[]                          args)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.EventHandler.ParseEx(Event _event, ScriptingEngine engine                         , Object[] arguments)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.GameServer.StartResource(String resourceName, String pare                         nt)
```

If this is the wrong repository to report this issue, I apologize and please point me in the correct direction.

**Comment by leecow** [comment]
@Bradleyay - can you provide a minimal repro so we can get a better sense of where the throw is happening?

**Comment by karelz** [comment]
No response for 1 week, closing. Feel free to reopen once there is actionable info. Thanks!
