### ISSUE TITLE
dotnet tool broken with 3.0-preview4 on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ismail** [dotnet/core#2617]
This works with preview3, hence it's a regression:

```
havana ~ > dotnet tool

Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.100-preview4-011223

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
More about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.CalendarData.NormalizeDatePattern(String input)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarId calendarId)
   at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
   at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
   at System.Globalization.CultureData.DateSeparator(CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.set_Calendar(Calendar value)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
   at System.Globalization.DateTimeFormatInfo.GetInstance(IFormatProvider provider)
   at System.Globalization.TimeSpanFormat.TryFormat(TimeSpan value, Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider formatProvider)
   at System.TimeSpan.TryFormat(Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider formatProvider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.TimeZoneInfo..ctor(Byte[] data, String id, Boolean dstDisabled)
   at System.TimeZoneInfo.GetTimeZoneFromTzData(Byte[] rawData, String id)
   at System.TimeZoneInfo.GetLocalTimeZoneFromTzFile()
   at System.TimeZoneInfo.CachedData.CreateLocal()
   at System.DateTime.get_Now()
   at System.DateTimeOffset.get_Now()
   at Microsoft.AspNetCore.DeveloperCertificates.XPlat.CertificateGenerator.GenerateAspNetHttpsCertificate()
   at Microsoft.DotNet.Cli.AspNetCoreCertificateGenerator.GenerateAspNetCoreDevelopmentCertificate()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Looking at the backtrace, this might be due to ICU, here is the details of ICU packages installed:

```
havana ~ > rpm -qa | grep libicu
libicu64_1-ledata-64.1-1.1.noarch                                                                                                                                                              
libicu-suse64_1-64.1-1.1.x86_64                                                                                                                                                                
libicu-devel-64.1-1.1.x86_64 
```

**Comment by karelz** [comment]
@tarekgh @dagood can you please help route it? Is it a known problem?

**Comment by tarekgh** [comment]
I'll try to look. Is there any more data here can help? like debugger dump or more info about the running environment (e.g. what is the locale on the failed machine)? 

@dagood if we have a machine or image I can use to check that would be helpful if you point me to that. thanks. 

CC @krwq

**Comment by dagood** [comment]
No repro with a from scratch install from tarball on a `opensuse/tumbleweed` container. 😕

```
docker run -it --rm opensuse/tumbleweed bash -c '
  zypper install -y wget tar gzip libicu
  wget https://download.visualstudio.microsoft.com/download/pr/26d4dc1f-f674-4902-9921-f287f65266f9/ef8a67939f0c3e5729b2674a5e013328/dotnet-sdk-3.0.100-preview4-011223-linux-x64.tar.gz
  mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.0.100-preview4-011223-linux-x64.tar.gz -C $HOME/dotnet
  export DOTNET_ROOT=$HOME/dotnet
  export PATH=$PATH:$HOME/dotnet
  dotnet tool'
```

```
...

Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.100-preview4-011223

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
More about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Required command was not provided.
Usage: dotnet tool [options] [command]

Options:
  -h, --help   Show command line help.
...
```

I think it's reasonable to try to repro on that base container if we can get more info, though.

**Comment by ismail** [comment]
Locale is C.UTF-8, if you need more information you have to let me know :-)

**Comment by dagood** [comment]
Apologies, I see now that looks pretty passive aggressive. I was just expressing my hope that @tarekgh can think of more things to ask about to get to the bottom of this. 🙂 I don't know enough about this area to know what other stuff to gather.

**Comment by tarekgh** [comment]
@ismail @dagood  what you have sent both is very useful. I'll try to look more here. Thanks for your help.

**Comment by tarekgh** [comment]
I can repro this now.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/corefx #37098](https://github.com/dotnet/corefx/issues/37098) via [**ZenHub**](https://www.zenhub.com/)
