### ISSUE TITLE
unable to get cpuid by ManagementObjectSearcher

### ISSUE THREAD

**Issue by zhusheping** [dotnet/core#2630]
I wan't get cpuid in a console app with core3.0 preview with

```             
           String processorID = "";
            ManagementObjectSearcher searcher = new ManagementObjectSearcher(
                "Select * FROM WIN32_Processor");
            ManagementObjectCollection mObject = searcher.Get();
            foreach (ManagementObject obj in mObject)
            {
                processorID = obj["ProcessorId"].ToString();
            }
            return processorID;
```
And exception throwed:Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.

**Comment by karelz** [comment]
I assume it is `System.Management` problem? @Anipik can you please help?

**Comment by Anipik** [comment]
Yeah i will take a look

**Comment by Anipik** [comment]
i tried it with the master branch as well core3.0 preview, i am not able to repro the bug.
Its the printing the processor id as ```BFEBFBFF000406F1```

can you give more context on the failure or about the machine where you are running this code ?

**Comment by zhusheping** [comment]
It was throwed when  new a ManagementObjectSearcher. The StackTrace :
  at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   at System.Management.ManagementPath.GetWbemPath(IWbemPath wbemPath)
   at System.Management.ManagementPath.GetWbemPath()
   at System.Management.ManagementPath.get_Path()
   at System.Management.ManagementScope.set_prvpath(ManagementPath value)
   at System.Management.ManagementScope._Clone(ManagementScope scope, IdentifierChangedEventHandler handler)
   at System.Management.ManagementScope._Clone(ManagementScope scope)
   at System.Management.ManagementObjectSearcher..ctor(ManagementScope scope, ObjectQuery query, EnumerationOptions options)
   at System.Management.ManagementObjectSearcher..ctor(String queryString)
   at CustomConfig.HwInfoService.GetMachineCode() in D:\TFlow_Clould\TfrcClould\CustomConfig\HwInfoService.cs:line 20
   at CustomConfig.Config..cctor() in D:\TFlow_Clould\TfrcClould\CustomConfig\Config.cs:line 42

And Its the printing the processor id as BFEBFBFF000506E3 in a core 2.1 console app.

I guess it's related to calling unmanaged DLL.

**Comment by karelz** [comment]
@Anipik any update?
@zhusheping are you still able to reproduce on latest Preview of 3.0?
