### ISSUE TITLE
Fatal error in IL Linker. Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by thangduo** [dotnet/core#2637]
# Issue Title

I am getting a fatal error in IL Linker.

Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

# General

Using .NET Core 3.0 Preview SDK release for Mac to build a new Blazor hello world web application. The application uses System.ServiceModel.Http version="4.5.3" to communicate with another web application (similar to WCF).

The following was installed at /usr/local/share/dotnet 
.NET Core SDK 3.0.100-preview4-011223
.NET Core Runtime 3.0.0-preview4-27615-11
ASP.NET Core Runtime 3.0.0-preview4-19216-03

Error when running the `dotnet build` command:

```Batch
dotnet build
Microsoft (R) Build Engine version 16.1.54-preview+gd004974104 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
 
  Restore completed in 38.26 ms for <redacted path>/WebApplication1/WebApplication1.csproj.
/usr/local/share/dotnet/sdk/3.0.100-preview4-011223/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [<redacted path>/WebApplication1/WebApplication1.csproj]
  WebApplication1 -> <redacted path>/WebApplication1/bin/Debug/netstandard2.0/WebApplication1.dll
  Fatal error in IL Linker
  
  Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
     at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name)
     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(LinkContext context, AssemblyDefinition assembly, RootVisibility rootVisibility)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(AssemblyDefinition assembly)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

**Comment by arivoir** [comment]
Same problem here

**Comment by karelz** [comment]
@sbomer can you please help me route the issue? Should it be moved to https://github.com/mono/linker?

**Comment by sbomer** [comment]
Yes, could you please move it? I don't have permissions to use the GitHub issue move feature.

**Comment by karelz** [comment]
This issue was moved to mono/linker#604

**Comment by karelz** [comment]
@sbomer FYI: YOu can use ZenHub, or https://hubbup.io/Mover ... I don't have other magical powers either ;)

**Comment by sbomer** [comment]
Good to know, thanks!
