### ISSUE TITLE
Server certificate validation failure on docker nanoserver-windows

### ISSUE THREAD

**Issue by VidyaKukke** [dotnet/core#2750]
# Issue Title

I have a dotnet core app that is making httpclient requests to a service. 
The service hosts a https endpoint and during connection presents its certificate.
Even though  i'm bypassing servercert validation my connection fails with the following error message:-

```
Failed to create topic with name <something>. Reason: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The certificate chain was issued by an authority that is not trusted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

My httpClient is created with 

```c#
var httpClientHandler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => 
                {
                    Console.WriteLine("In Validation callback !");
                    return true;
                },
            };
return new HttpClient(httpClientHandler);
```

I do see my message from callback so I know it is invoked  but still end up with the callstack from above. How do I solve this?

This is running as a docker container with base image  mcr.microsoft.com/dotnet/core/runtime:2.1.10-nanoserver-1809

The same piece of code works perfectly in linux environment. What is causing this behavior on windows and how can I fix it? Pointers are much appreciated!

**Comment by karelz** [comment]
Check that your certificate is correctly installed.
Try it on different box - maybe regular Windows OS.

**Comment by karelz** [comment]
Then try to create a simple repro, ideally something you can share.

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is actionable info available. Thanks!
