### ISSUE TITLE
WPF TextBox XamlParseException when culture is not "en-US" (.NET Core 3.0.0 Preview 6)

### ISSUE THREAD

**Issue by vitidev** [dotnet/core#2861]
# WPF TextBox XamlParseException when culture is "ru-RU" (.NET Core 3.0.0 Preview 6)

Empty netcore wpf project and window with textbox

    public MainWindow()
    {
         InitializeComponent(); // System.Windows.Markup.XamlParseException
    }

    <Window
        x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Title="MainWindow"
        Width="800"
        Height="450"
        mc:Ignorable="d">
        <TextBox />
    </Window>

Exception details (localized (ru))

    System.Windows.Markup.XamlParseException
      HResult=0x80131501
      Message="Вызов конструктора для типа "System.Windows.Controls.TextBox", удовлетворяющего указанным ограничениям привязки, привел к выдаче исключения.": номер строки "13" и позиция в строке "10".
      Source=PresentationFramework
      StackTrace:
       at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
       at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
       at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
       at WpfApp1.MainWindow.InitializeComponent() in F:\dev\test\WpfApp1\WpfApp1\MainWindow.xaml:line 1

    Inner Exception 1:
    ArgumentException: Requested value 'УДАЛИТЬ' was not found.

but it works with en-US culture

    public MainWindow()
    {
        Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-us");
        InitializeComponent();
    }

ps: .NET Core 3.0.0 Preview 5 - everything works well

**Comment by 0xd4d** [comment]
Could be https://github.com/dotnet/wpf/issues/913
