### ISSUE TITLE
Changes to dictionary throws "Collection was modified; enumeration operation may not execute." on unmodified dictionary.

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/core#2988]
I had this code block:

```
foreach(string providerName in info.ExternalProfileVisibility.Keys)
{
    if (model.ExternalProfileVisibility.ContainsKey(providerName))
    {
        model.ExternalProfileVisibility[providerName] = info.ExternalProfileVisibility[providerName];
    }
}
```
model and info are instances of **completely different** class objects. Both define `ExternalProfileVisibility` as a `Dictionary<string, CustomEnumType>` where `CustomEnumType` is an `enum`. 

After the loop runs exactly once, it throws the below error:

![image](https://user-images.githubusercontent.com/7371750/60732433-a4fcf580-9f67-11e9-9e11-f2bc9d8754bf.png)

The relevant stack trace is as below:

```
Error message: Collection was modified; enumeration operation may not execute.
Source: System.Private.CoreLib

at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at WebApplication1.AccountController.ContactInfo() in D:\Src\Example\WebApplication1\Controllers\AccountController.cs:line 131
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

When the loop variable collection is `info` and the collection being modified is `model`, both of which are completely different classes, why is the error thrown ?

**Comment by benaadams** [comment]
Would suggest they both are the same dictionary so the data is already the same (as you are updating the dictionary with itself)?

Add a check to test this beforehand and see if it still errors
```csharp
if (!ReferenceEquals(info.ExternalProfileVisibility, model.ExternalProfileVisibility))
{
    foreach(string providerName in info.ExternalProfileVisibility.Keys)
    {
        if (model.ExternalProfileVisibility.ContainsKey(providerName))
        {
            model.ExternalProfileVisibility[providerName] = info.ExternalProfileVisibility[providerName];
        }
    }
}
```

**Comment by sujayvsarma** [comment]
@benaadams As I already said in my original post, they are completely different class declarations. 

`info` - is a business class in a different DLL
`model` - is a Model used in a View (a View Model)

The application is an ASP.NET Core MVC application.

**Comment by sujayvsarma** [comment]
[Sorry, I deleted the previous comment]

Thank you @benaadams  for pointing me in the right direction! Apparently, I had this line before the loop:

```
model.ExternalProfileVisibility = info.ExternalProfileVisibility;
```

This was causing a reference equality that would have been the reason for the exception. 

Closing the issue.
