### ISSUE TITLE
dotnet-diagnostic sockets lingering after crash

### ISSUE THREAD

**Issue by spencercw** [dotnet/core#3099]
.NET Core version: 3.0.0-preview7-27912-14 Linux

My target is an arm64 embedded platform, but I am seeing the same behaviour on my x64 dev machine.

The runtime is leaving these diagnostic sockets with names like `dotnet-diagnostic-28148-23379390-socket` under /tmp if the process exits with an unhandled exception. If the process is repeatedly crashing in this way then these sockets pile up, using more and more memory (/tmp is mounted in RAM on my system), eventually overwhelming the system. Is there a way to prevent these sockets from being created, or ensuring that they are cleaned up properly on an unhandled exception?

How I am running my executable:
```
$ dotnet test.dll
Unhandled exception. [Trim]
Aborted
```

**Comment by carlossanlop** [comment]
Hi @spencercw, can you please provide a code sample so we can help you further?

**Comment by spencercw** [comment]
Hi @carlossanlop, more info below as requested. Thanks.

Program.cs:
```
using System;

namespace maybe_crash
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args[0] == "0")
            {
                Console.WriteLine("Not crashing");
            }
            else
            {
                Console.WriteLine("Crashing...");
                throw new Exception("Crash");
            }
        }
    }
}
```
maybe-crash.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RootNamespace>maybe_crash</RootNamespace>
  </PropertyGroup>

</Project>
```
SDK/runtime info:
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/cws/Downloads/dotnet-sdk-3.0.100-preview7-012821-linux-x64/sdk/3.0.100-preview7-012821/

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  3.0.100-preview7-012821 [/home/cws/Downloads/dotnet-sdk-3.0.100-preview7-012821-linux-x64/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/home/cws/Downloads/dotnet-sdk-3.0.100-preview7-012821-linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/home/cws/Downloads/dotnet-sdk-3.0.100-preview7-012821-linux-x64/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Build:
```
$ dotnet publish
Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 25.18 ms for /home/cws/projects/maybe-crash/maybe-crash.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  maybe-crash -> /home/cws/projects/maybe-crash/bin/Debug/netcoreapp3.0/maybe-crash.dll
  maybe-crash -> /home/cws/projects/maybe-crash/bin/Debug/netcoreapp3.0/publish/
```
I start out with no diagnostic sockets:
```
$ ls -1 /tmp/dotnet-diagnostic-*
ls: cannot access '/tmp/dotnet-diagnostic-*': No such file or directory
```
If I run without crashing then no diagnostic sockets are left behind -- this is good:
```
$ dotnet bin/Debug/netcoreapp3.0/publish/maybe-crash.dll 0
Not crashing
$ ls -1 /tmp/dotnet-diagnostic-*
ls: cannot access '/tmp/dotnet-diagnostic-*': No such file or directory
```
However, if the app crashes then a new diagnostic socket is left behind every time the app runs:
```
$ dotnet bin/Debug/netcoreapp3.0/publish/maybe-crash.dll 1
Crashing...
Unhandled exception. System.Exception: Crash
   at maybe_crash.Program.Main(String[] args) in /home/cws/projects/maybe-crash/Program.cs:line 18
Aborted (core dumped)
$ ls -1 /tmp/dotnet-diagnostic-*
/tmp/dotnet-diagnostic-21170-16711797-socket
$ dotnet bin/Debug/netcoreapp3.0/publish/maybe-crash.dll 1
Crashing...
Unhandled exception. System.Exception: Crash
   at maybe_crash.Program.Main(String[] args) in /home/cws/projects/maybe-crash/Program.cs:line 18
Aborted (core dumped)
$ ls -1 /tmp/dotnet-diagnostic-*
/tmp/dotnet-diagnostic-21170-16711797-socket
/tmp/dotnet-diagnostic-21196-16713903-socket
```

**Comment by carlossanlop** [comment]
Thank you for your detailed answer, @spencercw . This issue seems to be related to CoreCLR, so I will transfer it to that repo where they can help you further.
CC @sywhang
