### ISSUE TITLE
NullReferenceException in Hello World DateTime.

### ISSUE THREAD

**Issue by brainode** [dotnet/core#3101]
# Issue Title
I have OpenSUSE Tumbleweed with Version 2.2.401 and Commit 729b316c13.

When i trying to run Hello World sample:
```using System;

namespace cons
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("The current time is " + DateTime.Now);
        }
    }
}
```
I've got an error:
```
An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'
   at System.Globalization.CalendarData.NormalizeDatePattern(String input)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarId calendarId)
   at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
   at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
   at System.Globalization.CultureData.DateSeparator(CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider)
   at System.String.Concat(Object arg0, Object arg1)
   at cons.Program.Main(String[] args) in /home/rusbaron/Tmp/cs/cons/Program.cs:line 10
```
What's wrong?

**Comment by danmosemsft** [comment]
I am unable to repro with this dockerfile (on docker for windows)
```
FROM opensuse/tumbleweed

RUN zypper update \
  && zypper -n install sudo

RUN sudo zypper update \
  && sudo zypper -n install libicu-suse64_2 \
  && sudo zypper -n install curl \
  && sudo zypper -n install wget

RUN curl https://packages.microsoft.com/keys/microsoft.asc > microsoft.asc \
 && sudo rpm --import microsoft.asc

RUN wget -q https://packages.microsoft.com/config/opensuse/42.2/prod.repo \
  && sudo mv prod.repo /etc/zypp/repos.d/microsoft-prod.repo \
  && sudo chown root:root /etc/zypp/repos.d/microsoft-prod.repo  \
  && sudo zypper -n install aspnetcore-runtime-2.2

RUN sudo zypper update \
  && sudo zypper -n install dotnet-sdk-2.2
```
This has the same commit 729b316c13.

Do you have any more details about the environment? Can you try 3.0 instead? https://dotnet.microsoft.com/download/dotnet-core/3.0
