### ISSUE TITLE
HttpListenerRequestUriBuilder.GetPath throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by zz1231118** [dotnet/core#3134]
# Issue HttpListenerRequestUriBuilder.GetPath throw IndexOutOfRangeException
.net core 
System.Net.HttpListener

# General
AppDomain: UnhandledException:System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.HttpListenerRequestUriBuilder.GetPath(String uriString)
   at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath()
   at System.Net.HttpListenerRequestUriBuilder.Build()
   at System.Net.HttpListenerRequest.FinishInitialization()
   at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
   at System.Net.HttpConnection.OnRead(IAsyncResult ares)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by carlossanlop** [comment]
@zz1231118 , can you provide a code example so we can better understand your problem?

**Comment by zz1231118** [comment]
> @zz1231118 , can you provide a code example so we can better understand your problem?

var httpListener = new HttpListener();
httpListener.Prefixes.Add("xxx");
httpListener.Start();
httpListener.BeginGetContext(new AsyncCallback(ProcessAccept), null);

Then the program crashes and it is difficult to reimplement the exception.

**os:**
CentOS release 6.9 (Final)
Kernel \r on an \m

**.netcore**
Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.2 [/usr/bin/dotnet/dotnet-runtime-2.2.2-rhel.6-x64/shared/Microsoft.NETCore.App]

**Comment by BogdanovKirill** [comment]
Same issue on our production.

**env:**
Docker container

**os:**
Amazon Linux AMI 2018.03.e x86_64 ECS HVM GP2

**.netcore**
.net core 2.2 (runtime)

**Comment by carlossanlop** [comment]
@scalablecory can you help figure out this issue?

**Comment by BogdanovKirill** [comment]
I could also add that AppDomain.CurrentDomain.UnhandledException can help to catch it

**Comment by BogdanovKirill** [comment]
Any news? Today I've got same issue:

{"level": "Critical", "source": "i-0cac7ec58257ae243", "time": "2019-09-26 22:14:42", "message": "Unhandled exception in EventsProcessingService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "exception": "System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.HttpListenerRequestUriBuilder.GetPath(String uriString)
   at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath()
   at System.Net.HttpListenerRequestUriBuilder.Build()
   at System.Net.HttpListenerRequest.FinishInitialization()
   at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
   at System.Net.HttpConnection.OnRead(IAsyncResult ares)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"}

**Comment by davidfowl** [comment]
```C#
var httpListener = new HttpListener();
httpListener.Prefixes.Add("xxx");
httpListener.Start();
httpListener.BeginGetContext(new AsyncCallback(ProcessAccept), null);
```

Is this the literal code you wrote? I'm missing something here but did you actually add the prefix "xxx"?

**Comment by BogdanovKirill** [comment]
My code looks like:
```
_httpListener = new HttpListener();
_httpListener.Prefixes.Add($"http://*:{port}/");
_httpListener.Start();
```
And then I'm using:
`HttpListenerContext context = await _httpListener.GetContextAsync();`
