### ISSUE TITLE
.NET runtime package on rhel6 fails to run 

### ISSUE THREAD

**Issue by winnieryl** [dotnet/core#3150]
# Issue Title

.NET runtime package on rhel6 fails to run dll with ICU error

# General

When I run a program using .NET runtime, it throws an exception:
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
Aborted (core dumped)

Do I still need to install ICU package on official release 2.1.12?

**Comment by carlossanlop** [comment]
@tarekgh do you know what causes this error?

**Comment by tarekgh** [comment]
> Do I still need to install ICU package on official release 2.1.12?

Yes it is required to have ICU package installed to run on all .NET Core versions. 

We have invariant mode can be enabled which will not require ICU https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/Documentation/architecture/globalization-invariant-mode.md but I wouldn't recommend to enable it except if you really don't care about Globalization support.
