### ISSUE TITLE
Trying to connect to TLS 1.2 enabled Sql Server from .Net Core client

### ISSUE THREAD

**Issue by m4masood** [dotnet/core#3154]
Hi,

I have got a client (container application) in .net core and trying to connect to TLS 1.2 enabled Sql server.

When the Sql server was not configured the client can talk to database but after enabling TLS 1.2 it started throwing below error:

Error: The connection is broken and recovery is not possible.  The client driver attempted to recover the connection one or more times and all attempts failed.  Increase the value of ConnectRetryCount to increase the number of recovery attempts.
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown 

Can you please assist on this?

Thanks,
Muhammad Masood

**Comment by carlossanlop** [comment]
@divega is this something where you or someone in your team can provide some help?

**Comment by divega** [comment]
This rather for someone from the SqlClient team to respond. Cc @david-engel @cheenamalhotra. I am not familiar with TLS support in SqlClient. Is this enabled in either System.Data.SqlClient or Microsoft.Data.SqlClient?
