### ISSUE TITLE
.NetCore 3.0 publish to single file fail on Cent OS-7

### ISSUE THREAD

**Issue by deepumi** [dotnet/core#3214]
# Issue Title
.NetCore 3.0 publish to single file fail on Cent OS - 7

# Project settings
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
</Project>
```
# Exception 
```csharp 8/19/2019 11:27:46 AM

System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__205.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

System.Exception: Publishing failed.

**Comment by scalablecory** [comment]
@livarcocc @nguerrera

**Comment by nguerrera** [comment]
Was this publish initiated from Visual Studio? Can you look at the output window and see what errors are there?

**Comment by nguerrera** [comment]
cc @vijayrkn

**Comment by nguerrera** [comment]
What do you get if you use `dotnet publish` on the command line?

**Comment by deepumi** [comment]
> Was this publish initiated from Visual Studio? Can you look at the output window and see what errors are there?

Yes, I am using VS 2019 Professional Version 16.2.1

```
1>------ Build started: Project: LinkCrawler.Net, Configuration: Release Any CPU ------
1>You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>LinkCrawler.Net -> C:\LinkCrawler.Net\bin\Release\netcoreapp3.0\linux-x64\LinkCrawler.Net.dll
2>------ Publish started: Project: LinkCrawler.Net, Configuration: Release Any CPU ------
2>Restore completed in 41.65 ms for C:\LinkCrawler.Net\LinkCrawler.Net\LinkCrawler.Net.csproj.
2>LinkCrawler.Net -> C:\LinkCrawler.Net\LinkCrawler.Net\bin\Release\netcoreapp3.0\linux-x64\LinkCrawler.Net.dll
2>Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
2>Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false.
```
Looks like, I have to change 'PublishReadyToRun ' to 'false' and now its working!

**Comment by nguerrera** [comment]
Heads up that VS 16.2 + 3.0 is not supported. Please use VS 16.3 Preview 2, which includes 3.0 preview 8. cc @livarcocc

**Comment by nguerrera** [comment]
@vijayrkn Is there a tracking issue for VS hiding the real errors behind that ugly System.Exception when the build step of publish fails? If not, I will file one.

**Comment by deepumi** [comment]
> Heads up that VS 16.2 + 3.0 is not supported. Please use VS 16.3 Preview 2, which includes 3.0 preview 8. cc @livarcocc

@nguerrera - Thank for the heads-up, I will update to latest,

**Comment by vijayrkn** [comment]
> @vijayrkn Is there a tracking issue for VS hiding the real errors behind that ugly System.Exception when the build step of publish fails? If not, I will file one.

Yes. We have a bug tracking this already.
