### ISSUE TITLE
MEF on .NET Core 2.1 fails to load plugins from folder , but works well with .NET Framework 4.6.1

### ISSUE THREAD

**Issue by sdg002** [dotnet/core#3376]
# Issue Title
I have 2 plugin class libraries which reference different version of the Newtonsoft.Json package. Console EXE on .NET Fwk has no problems in loading both of the plugins and invoking the 2 different versions of Newtonsoft.Json simultaneously.

However, console EXE on .NET Core 2.1 will fail on the second plugin. It is almost as though .NET Core is unable to load 2 different versions of the same assembly.

My initial view is that this is less to do with Managed Extensibility Framework . The root cause most probably lies with how .NET Core is designed to load multiple versions of referenced assemblies. In this case the referenced assembly is NewtonSoft. 

- Is this a problem with Newtonsoft?  Unlikely, I am able to reproduce the same problem with the package Polly. **Update** -  see further below. I could repro the same problem using **Polly** .
- Are there some additional steps to be taken care of when using .NET Core, e.g. Manually forcing the assembly resolution using Resolving event of AssemblyLoadContext .
- Or something else? **Update** -  I ditched MEF and tried the old fashioned **Assembly.LoadFrom**. I could repro the same behaviour with .NET Core. See further below. Possible indication that .NET Core has a different behavior.  

# General
I have two .NET Standard 20 class libraries (**PluginNewtonsoftv12**) and  (**PluginNewtonsoftv9**) which implement an interface defined in the class library project **Contracts**.

I have two EXE projects - **ConsoleAppNetCore** and **ConsoleAppNETFramework** which use the **DirectoryCatalog** of **Managed Extensibility Framework** to discover and load the plugins.

The output of the projects **PluginNewtonsoftv9** and **PluginNewtonsoftv12** are copied to a plugins folder using a post build step. This is the **out** folder in the project **PluginsDeliveryFolder**.  Both the plugin projects have the attribute **CopyLocalLockFileAssemblies** to ensure that all dependent assemblies get copied over to their respective folders.

What is important that EXE should have no compile time knowledge of the plugin library except for the contractual interfaces.

**Solution structure**

- ConsoleAppNETFramework (EXE, fwk 461)
- ConsoleAppNetCore (EXE, Core 2.1)
- PluginsDeliveryFolder (Dummy class library)
- PluginNewtonsoftv12 (.NET Standard 20)
- PluginNewtonsoftv9 (.NET Standard 20)
- Contracts (.NET Standard 20)

**Steps to reproduce - Framework** 

1. Do a build all.
2. Ensure that the plugins DLLs are copied over to **PluginsDeliveryFolder**
3. Run the project **ConsoleAppNETFramework**.
4. Specify the path to the folder where all the plugins are copied over
4. Specify the MEF meta-data of the plugin to load. newtonv9 and then newtonv12
5. Try the reverse sequence. newtonv12 and then newtonv9
6. Both should work

--------------
**Steps to reproduce - NET Core**
1. Do a build all.
2. Ensure that the plugins DLLs are copied over to **PluginsDeliveryFolder**
3. Run the project **ConsoleAppNetCore**.
4. Specify the path to the folder where all the plugins are copied over
5. Select **newtonv9**  and then **newtonv12**. The plugin **newtonv9** works fine, but **newtonv12** fails because it is unable to load version 12 of Newtonsoft
6. Select **newtonv12** and then **newtonv9**. Both the plugins work fine.

--------------
**Screen capture of failure when using .NET Core**

> ![NetCore_V9_before_V12](https://user-images.githubusercontent.com/20245330/64969617-2b08b700-d89c-11e9-97bb-8a52da19eb0b.PNG)
 
**Exception message when using .NET Core**

> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
> File name: 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
>    at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
>    at PluginNewtonsoftV12.Class1.DoWork()
>    at ConsoleAppNETCore.Program.Main(String[] args) in 
> 

--------------
**Screen capture of success when using .NET Framework**
![NetFwk](https://user-images.githubusercontent.com/20245330/64969977-d1ed5300-d89c-11e9-8a35-0601543c0d8d.PNG)

**Source code**
https://github.com/sdg002/MEFFwkCoreComparison

**Summary**
,NET Framework works as expected. It is able to load the 2 versions of Newtonsoft side by side. However, .NET Core is unable to cope with the 2 versions side by side. Is this a limitation of .NET Core?

**Comment by sdg002** [comment]
Added detailed exception message

**Comment by sdg002** [comment]
As an experiment , I tried the above using the NUGET package **Polly**. I wrote 2 class library plugins. One which is compiled with package reference 6.0 of Polly and the other references version 7.0 of Polly.

**.NET Framework** had no problems in loading both the plugins and also loading both the versions of Polly
![Polly_Framework](https://user-images.githubusercontent.com/20245330/65041131-eb9aa300-d94d-11e9-8c79-3e5fff2e8c04.png)


**.NET Core** however failed when it attempted to execute the plugin with Polly 7 , if the plugin with Polly 6 was loaded first
![Polly_NetCore](https://user-images.githubusercontent.com/20245330/65041138-ee959380-d94d-11e9-8b86-40c3e6fe9a85.png)

**Comment by sdg002** [comment]
## To rule out issues with MEF, I used Assembly.LoadFrom and I was able to repro the above problem on .NET Core

I added a second **Program.cs** to the projects `ConsoleAppNetCore` and `ConsoleAppNETFramework` .

**Code**

```
        static void Main(string[] args)
        {

            try
            {
                string folderNewtonsoftV9 = @"C:\Users\saurabhd\MyTrials\OtherStuff\MEFFwkCoreComparison\PluginsDeliveryFolder\out\PluginNewtonsoftv9\PluginNewtonsoftv9.dll"; //you will need to replace this
                string folderNewtonsoftV12 = @"C:\Users\saurabhd\MyTrials\OtherStuff\MEFFwkCoreComparison\PluginsDeliveryFolder\out\PluginNewtonsoftV12\PluginNewtonsoftv12.dll"; //you will need to replace this
                string[] pathsAssemblies = new string[] { folderNewtonsoftV9, folderNewtonsoftV12 };
                foreach (string pathAssembly in pathsAssemblies)
                {
                    var assembly = System.Reflection.Assembly.LoadFrom(pathAssembly);
                    Type tTarget = assembly.GetTypes().FirstOrDefault(t => t.Name.ToLower() == "class1");
                    var plugin = Activator.CreateInstance(tTarget) as Contracts.ISomePlugin;
                    plugin.DoWork();

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
}

```
**Observations**

**.NET Framework** has no problems in loading the plugin NewtonSoft v9 followed by loading the plugin which references NewtonSoft v12.  

**.NET Core** succeeds loading the plugin which references NewtonSoft v9, but fails when it also tries to load the plugin with NewtonSoft v12.

> Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)


As per my experience with .NET Framework, side by side loading was never so much of an issue. Have things changed with .NET Core? Where am I going wrong?

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/coreclr/issues/26861

**Comment by sdg002** [comment]
Hi @jkotas ,
I noticed that this issue has been Closed because of the duplicate issue https://github.com/dotnet/coreclr/issues/26861

Just wanted to verify with you that the problem in this issue concerns loading of plugin assemblies via lazy loading of **Managed Extensibility Framework** and that you concur that these two issues are indeed connected to the same underlying problem. (I think they are, but I am not the expert here).  

Just to let you know MEF has been working wonderfully for us .NET 4.6.1. We have had no issues in loading plugins and their side by side dependencies from various folders. MEF has indeed been a boon in modularizing our back end document parsing application which was becoming a monolith.

Thank you,
Sau

**Comment by jkotas** [comment]
Your are right. The two issues are related, but not exactly same.
