### ISSUE TITLE
PublishTrimmed - Could not load type 'System.Runtime.CompilerServices.AsyncIteratorMethodBuilder'

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/core#3442]
# Issue Title

PublishTrimmed - Could not load type 'System.Runtime.CompilerServices.AsyncIteratorMethodBuilder'

# General

Not sure if I should open this issue here or on Roslyn or Mono Linker :)

I'm receiving this error when publishing with PublishTrimmed flag on. It seems related to async IAsyncEnumerable.

Idk if the linker is stripping away the type, even though it is reacheable.

The error happens in this method: https://github.com/felipepessoto/FujiyNotepad/blob/master/src/FujiyNotepad.UI/Model/TextSearcher.cs#L24

![image](https://user-images.githubusercontent.com/1336227/65474896-e9f04400-de53-11e9-8be2-6fed4dbe4540.png)

And the &lt;Search&gt;d__6 has a reference to AsyncIteratorMethodBuilder:

![image](https://user-images.githubusercontent.com/1336227/65474931-03918b80-de54-11e9-91d5-ff66dca09e04.png)

Stack Trace:

```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Runtime.CompilerServices.AsyncIteratorMethodBuilder' from assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
  Source=FujiyNotepad.UI
  StackTrace:
   at FujiyNotepad.UI.Model.TextSearcher.Search(Int64 startOffset, Char[] charsToSearch, IProgress`1 progress, CancellationToken token)
   at FujiyNotepad.UI.FujiyTextBox.<GetLengthToFillViewport>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FujiyNotepad.UI.FujiyTextBox.<GoToOffset>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FujiyNotepad.UI.FujiyTextBox.<OpenFile>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at FujiyNotepad.UI.MainWindow.<OpenFile>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at FujiyNotepad.UI.MainWindow.<OpenSample_Click>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at FujiyNotepad.UI.App.Main()

```

**Comment by marek-safar** [comment]
Please open the issue in Mono Linker with steps how to reproduce the issue

**Comment by sbomer** [comment]
Moved to mono/linker, closing here.
