### ISSUE TITLE
error when running as self-contained: The type initializer for 'System.Management.Automation.Runspaces.RunspaceFactory' threw an exception

### ISSUE THREAD

**Issue by agonzalezm** [dotnet/core#3606]
I have a net core 3.0 command line application that runs some powershell commands, when app is run with deployed framework it runs ok, but when running the app as self-contained it fails with error:
```
The type initializer for 'System.Management.Automation.Runspaces.RunspaceFactory' threw an exception. ---    at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at Agent.Helpers.PowerShellHelper.<>c_DisplayClass9_0.<Execute>b_0() in C:\Projects\auditor\Agent\Helpers\PowerShellHelper.cs:line 45
The type initializer for 'System.Management.Automation.Runspaces.RunspaceFactory' threw an exception. ---    at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at Agent.Helpers.PowerShellHelper.<>c_DisplayClass9_0.<Execute>b_0() in C:\Projects\auditor\Agent\Helpers\PowerShellHelper.cs:line 45
The type initializer for 'System.Management.Automation.Runspaces.RunspaceFactory' threw an exception. ---    at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at Agent.Helpers.PowerShellHelper.<>c_DisplayClass9_0.<Execute>b_0() in C:\Projects\auditor\Agent\Helpers\PowerShellHelper.cs:line 45
The type initializer for 'System.Management.Automation.Runspaces.RunspaceFactory' threw an exception. ---    at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at Agent.Helpers.PowerShellHelper.<>c_DisplayClass9_0.<Execute>b_0() in 
```

**Comment by scalablecory** [comment]
Not sure if Powershell or .NET problem. @jeffschwMSFT @livarcocc any ideas?

**Comment by jeffschwMSFT** [comment]
@agonzalezm what settings are you using when publishing for self-contained?

cc @swaroop-sridhar @sbomer

**Comment by swaroop-sridhar** [comment]
@agonzalezm  ... interesting that the failure only shows up in self-contained builds.
What was the exception thrown? The manual for [`RunspaceFactory.CreateRunspace `](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.runspacefactory.createrunspace?view=pscore-6.2.0) says that it only throws `ArgumentNullException`.

**Comment by carlossanlop** [comment]
@agonzalezm no answer in 19 days. Closing. Feel free to reopen if you want to followup.
