### ISSUE TITLE
Bootstrap .NET 1.1 on Fedora 25

### ISSUE THREAD

**Issue by tmds** [dotnet/core#362]
As part of https://github.com/dotnet/core/pull/326 I tried the dotnet.bootstrap.py on Fedora 25.
See instructions at: https://github.com/dotnet/core/pull/326#issuecomment-262479168.
The 'dotnet new' and 'dotnet restore' work, 'dotnet run' hangs.

I create this issue to look at why it is failing on Fedora 25.

\cc @ellismg

**Comment by tmds** [comment]
The compiler process is loading the cpu:
```
/home/tmds/repos/core/tools/dotnet-bootstrap/fedora.25-x64-dotnet/bin/dotnet /home/tmds/repos/core/tools/dotnet-bootstrap/fedora.25-x64-dotnet/bin/sdk/1.0.0-preview2-1-003177/csc.dll -noconfig @/tmp/hwapp/obj/Debug/netcoreapp1.1/dotnet-compile-csc.rsp
```

strace shows continuous calls to sigprocmask:
```
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
```

stacktrace:
```
#0  0x00007f77e4194c20 in sigprocmask () from /lib64/libc.so.6
#1  0x00007f77e29d2475 in _Ux86_64_dwarf_find_proc_info ()
   from /lib64/libunwind-x86_64.so.8
#2  0x00007f77e29cea7d in fetch_proc_info () from /lib64/libunwind-x86_64.so.8
#3  0x00007f77e29d069f in _Ux86_64_dwarf_find_save_locs ()
   from /lib64/libunwind-x86_64.so.8
#4  0x00007f77e29d1959 in _Ux86_64_dwarf_step ()
   from /lib64/libunwind-x86_64.so.8
#5  0x00007f77e29ca2c1 in _Ux86_64_step () from /lib64/libunwind-x86_64.so.8
#6  0x00007f77e36e94bc in PAL_VirtualUnwind ()
   from /home/tmds/repos/core/tools/dotnet-bootstrap/fedora.25-x64-dotnet/bin/shared/Microsoft.NETCore.App/1.1.0/libcoreclr.so
#7  0x00007f77e335da19 in Thread::VirtualUnwindToFirstManagedCallFrame(_CONTEXT*) ()
   from /home/tmds/repos/core/tools/dotnet-bootstrap/fedora.25-x64-dotnet/bin/shared/Microsoft.NETCore.App/1.1.0/libcoreclr.so
#8  0x00007f77e3481843 in DispatchManagedException(PAL_SEHException&, bool) ()
   from /home/tmds/repos/core/tools/dotnet-bootstrap/fedora.25-x64-dotnet/bin/shared/Microsoft.NETCore.App/1.1.0/libcoreclr.so
#9  0x00007f77e350c522 in PreStubWorker ()
   from /home/tmds/repos/core/tools/dotnet-bootstrap/fedora.25-x64-dotnet/bin/shared/Microsoft.NETCore.App/1.1.0/libcoreclr.so
#10 0x00007f77e348f0d8 in ThePreStub ()
```

I ran the coreclr pal testsuite:
```
$ ./build.sh release skipmscorlib skipgenerateversion
...
$ src/pal/tests/palsuite/runpaltests.sh `pwd`/bin/obj/Linux.x64.Release
...
PAL Test Results:
  Passed: 808
  Failed: 0
```

**Comment by stephentoub** [comment]
cc: @janvorli

**Comment by tmds** [comment]
@janvorli I tried to provide some debug info already. Please let me know if you need something else.

**Comment by tmds** [comment]
I am unable to reproduce this. Using the versions listed here: https://github.com/dotnet/core/pull/326#issuecomment-262479168 I now get a working dotnet.
