### ISSUE TITLE
Dotnet Core 3.0 json file not copied to output directory even with CopyToOutputDirectory

### ISSUE THREAD

**Issue by dlevitan6623** [dotnet/core#3697]
# Issue Title

Dotnet Core 3.0 json file not copied to output directory even with CopyToOutputDirectory

# General

Steps to reproduce:
Create a console app with core 3.0 with the following:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.0.0" />
  </ItemGroup>
```

Add an appsettings.json file, and add a name value pair

Add the following boiler plate code to program.cs:
```
      var builder = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
             .AddJsonFile("appsettings.json");

            var config = builder.Build();
```

Hit F5 - Get Error
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Apps\ConApp1\ConApp1\bin\Debug\netcoreapp3.0\appsettings.json'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at ConApp1.Program.Main(String[] args) in C:\Apps\ConApp1\ConApp1\Program.cs:line 17
```

now try adding the following to the csproj file:
```
  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

Hit F5 - Get same error as above

Note that if you go to the output directory, the appsettings.json file is not there

[ConApp1.zip](https://github.com/dotnet/core/files/3774060/ConApp1.zip)

**Comment by scalablecory** [comment]
@livarcocc

**Comment by matterai** [comment]
@dlevitan6623 give a try to the next configuration, please:
`
    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
`

**Comment by carlossanlop** [comment]
@dlevitan6623 seems to be answered.
