### ISSUE TITLE
netcoreapp3.0 PublishSingleFile:true appsettings.json not found

### ISSUE THREAD

**Issue by MetSystem** [dotnet/core#3714]
netcoreapp 3.0 
PublishSingleFile:true

```
2019-10-29 15:12:27.525 +08:00 [INF] Starting web host
2019-10-29 15:12:28.505 +08:00 [DBG] Hosting starting
2019-10-29 15:12:28.645 +08:00 [INF] User profile is available. Using 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2019-10-29 15:12:28.861 +08:00 [DBG] Reading data from file 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys\key-2a7a2e5f-9708-4be1-84e4-330bbc7f272a.xml'.
2019-10-29 15:12:28.923 +08:00 [DBG] Reading data from file 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys\key-3ed9e868-0739-425e-ae5e-a85d606d3be6.xml'.
2019-10-29 15:12:28.924 +08:00 [DBG] Reading data from file 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys\key-7a388851-82e0-4edb-b9a9-34a17e1b3e33.xml'.
2019-10-29 15:12:28.926 +08:00 [DBG] Reading data from file 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys\key-7c095bd0-5f28-47be-ae20-9850e3c0c51a.xml'.
2019-10-29 15:12:28.926 +08:00 [DBG] Reading data from file 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys\key-d0c0dcd7-0410-4ebb-bad9-c3ca3a6ec00b.xml'.
2019-10-29 15:12:28.926 +08:00 [DBG] Reading data from file 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys\key-d4ce2f19-76d7-48e6-a767-5b5832edce47.xml'.
2019-10-29 15:12:28.989 +08:00 [DBG] Found key "2a7a2e5f-9708-4be1-84e4-330bbc7f272a".
2019-10-29 15:12:29.031 +08:00 [DBG] Found key "3ed9e868-0739-425e-ae5e-a85d606d3be6".
2019-10-29 15:12:29.032 +08:00 [DBG] Found key "7a388851-82e0-4edb-b9a9-34a17e1b3e33".
2019-10-29 15:12:29.033 +08:00 [DBG] Found key "7c095bd0-5f28-47be-ae20-9850e3c0c51a".
2019-10-29 15:12:29.033 +08:00 [DBG] Found key "d0c0dcd7-0410-4ebb-bad9-c3ca3a6ec00b".
2019-10-29 15:12:29.036 +08:00 [DBG] Found key "d4ce2f19-76d7-48e6-a767-5b5832edce47".
2019-10-29 15:12:29.058 +08:00 [DBG] Considering key "7a388851-82e0-4edb-b9a9-34a17e1b3e33" with expiration date "2019-12-05T01:23:10.1197730+00:00" as default key.
2019-10-29 15:12:29.095 +08:00 [DBG] Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
2019-10-29 15:12:29.102 +08:00 [DBG] Decrypting secret element using Windows DPAPI.
2019-10-29 15:12:29.107 +08:00 [DBG] Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
2019-10-29 15:12:29.115 +08:00 [DBG] Opening CNG algorithm 'AES' from provider 'null' with chaining mode CBC.
2019-10-29 15:12:29.148 +08:00 [DBG] Opening CNG algorithm 'SHA256' from provider 'null' with HMAC.
2019-10-29 15:12:29.207 +08:00 [DBG] Using key "7a388851-82e0-4edb-b9a9-34a17e1b3e33" as the default key.
2019-10-29 15:12:29.208 +08:00 [DBG] Key ring with default key "7a388851-82e0-4edb-b9a9-34a17e1b3e33" was loaded during application startup.
2019-10-29 15:12:29.555 +08:00 [DBG] Failed to locate the development https certificate at 'null'.
2019-10-29 15:12:29.659 +08:00 [INF] Now listening on: http://[::]:5000
2019-10-29 15:12:29.664 +08:00 [DBG] Loaded hosting startup assembly Wtc.Web
2019-10-29 15:12:29.664 +08:00 [INF] Application started. Press Ctrl+C to shut down.
2019-10-29 15:12:29.667 +08:00 [INF] Hosting environment: Development
2019-10-29 15:12:29.674 +08:00 [INF] Content root path: E:\1.WrokSpace\1.Works\33浙江\湖州市\安吉\安吉生态红线\AJ_APP_Server\后台视频事件对接\Wtc.Web\bin\Release\netcoreapp3.0\publish
2019-10-29 15:12:29.678 +08:00 [DBG] Hosting started
2019-10-29 15:12:30.984 +08:00 [DBG] Connection id "0HLQS7TEGJNFO" received FIN.
2019-10-29 15:12:31.008 +08:00 [DBG] Connection id "0HLQS7TEGJNFO" accepted.
2019-10-29 15:12:31.015 +08:00 [DBG] Connection id "0HLQS7TEGJNFP" accepted.
2019-10-29 15:12:31.015 +08:00 [DBG] Connection id "0HLQS7TEGJNFO" started.
2019-10-29 15:12:31.055 +08:00 [DBG] Connection id "0HLQS7TEGJNFO" sending FIN because: "The client closed the connection."
2019-10-29 15:12:31.063 +08:00 [DBG] Connection id "0HLQS7TEGJNFO" disconnecting.
2019-10-29 15:12:31.073 +08:00 [DBG] Connection id "0HLQS7TEGJNFP" started.
2019-10-29 15:12:31.107 +08:00 [DBG] Connection id "0HLQS7TEGJNFO" stopped.
2019-10-29 15:12:31.380 +08:00 [INF] Request starting HTTP/1.1 POST http://localhost:5000/api/recvfrom application/json 1784
2019-10-29 15:12:31.458 +08:00 [DBG] Wildcard detected, all requests with hosts will be allowed.
2019-10-29 15:12:31.466 +08:00 [DBG] POST requests are not supported
2019-10-29 15:12:31.490 +08:00 [DBG] Initializing Razor view compiler with compiled view: '/Pages/Error.cshtml'.
2019-10-29 15:12:31.491 +08:00 [DBG] Initializing Razor view compiler with compiled view: '/Pages/Index.cshtml'.
2019-10-29 15:12:31.491 +08:00 [DBG] Initializing Razor view compiler with compiled view: '/Pages/Shared/_Layout.cshtml'.
2019-10-29 15:12:31.492 +08:00 [DBG] Initializing Razor view compiler with compiled view: '/Pages/Shared/_ValidationScriptsPartial.cshtml'.
2019-10-29 15:12:31.492 +08:00 [DBG] Initializing Razor view compiler with compiled view: '/Pages/_ViewImports.cshtml'.
2019-10-29 15:12:31.492 +08:00 [DBG] Initializing Razor view compiler with compiled view: '/Pages/_ViewStart.cshtml'.
2019-10-29 15:12:31.624 +08:00 [DBG] 1 candidate(s) found for the request path '/api/recvfrom'
2019-10-29 15:12:31.636 +08:00 [DBG] Endpoint 'Wtc.Web.Controllers.RecvfromController.Post (Wtc.Web)' with route pattern 'api/Recvfrom' is valid for the request path '/api/recvfrom'
2019-10-29 15:12:31.637 +08:00 [DBG] Request matched endpoint 'Wtc.Web.Controllers.RecvfromController.Post (Wtc.Web)'
2019-10-29 15:12:31.642 +08:00 [INF] Executing endpoint 'Wtc.Web.Controllers.RecvfromController.Post (Wtc.Web)'
2019-10-29 15:12:31.695 +08:00 [DBG] Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider"]
2019-10-29 15:12:31.832 +08:00 [INF] Route matched with {action = "Post", controller = "Recvfrom", page = ""}. Executing controller action with signature Void Post() on controller Wtc.Web.Controllers.RecvfromController (Wtc.Web).
2019-10-29 15:12:31.844 +08:00 [DBG] Execution plan of authorization filters (in the following order): ["None"]
2019-10-29 15:12:31.844 +08:00 [DBG] Execution plan of resource filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter"]
2019-10-29 15:12:31.845 +08:00 [DBG] Execution plan of action filters (in the following order): ["Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648)","Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)"]
2019-10-29 15:12:31.845 +08:00 [DBG] Execution plan of exception filters (in the following order): ["None"]
2019-10-29 15:12:31.845 +08:00 [DBG] Execution plan of result filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter"]
2019-10-29 15:12:31.847 +08:00 [DBG] Executing controller factory for controller Wtc.Web.Controllers.RecvfromController (Wtc.Web)
2019-10-29 15:12:31.848 +08:00 [DBG] Executed controller factory for controller Wtc.Web.Controllers.RecvfromController (Wtc.Web)
2019-10-29 15:12:32.045 +08:00 [DBG] Connection id "0HLQS7TEGJNFP", Request id "0HLQS7TEGJNFP:00000001": started reading request body.
2019-10-29 15:12:32.046 +08:00 [DBG] Connection id "0HLQS7TEGJNFP", Request id "0HLQS7TEGJNFP:00000001": done reading request body.
`2019-10-29 15:12:32.049 +08:00 [ERR] AppContext.BaseDirectory=C:\Users\ADMINI~1\AppData\Local\Temp\.net\Wtc.Web\lmy2ywvm.jhm\`

System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\Administrator\AppData\Local\Temp\.net\Wtc.Web\lmy2ywvm.jhm\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Boanda.Core.ConfigManager..ctor(String jsonFile)
   at Boanda.Core.ConfigManager.get_Instance()
   at Boanda.Data.DbConnectionFactory..ctor(String connectionStringName)
   at Boanda.Data.DbContext..ctor(String connectionStringName, UnitOfWork uow)
   at Wtc.Web.Controllers.RecvfromController.get_DbContext()
   at Wtc.Web.Controllers.RecvfromController.Post()
2019-10-29 15:12:33.549 +08:00 [INF] Executed action Wtc.Web.Controllers.RecvfromController.Post (Wtc.Web) in 1684.0857ms
2019-10-29 15:12:33.577 +08:00 [INF] Executed endpoint 'Wtc.Web.Controllers.RecvfromController.Post (Wtc.Web)'
2019-10-29 15:12:33.586 +08:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\Administrator\AppData\Local\Temp\.net\Wtc.Web\lmy2ywvm.jhm\appsettings.json'.
   at Wtc.Web.Controllers.RecvfromController.Post()
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-10-29 15:12:33.739 +08:00 [DBG] Connection id "0HLQS7TEGJNFP" completed keep alive response.
2019-10-29 15:12:33.741 +08:00 [INF] Request finished in 2455.3627ms 500 text/plain
2019-10-29 15:13:10.380 +08:00 [DBG] Hosting stopping
2019-10-29 15:13:10.379 +08:00 [INF] Application is shutting down...
2019-10-29 15:13:10.395 +08:00 [DBG] Connection id "0HLQS7TEGJNFP" disconnecting.
2019-10-29 15:13:10.396 +08:00 [DBG] Connection id "0HLQS7TEGJNFP" stopped.
2019-10-29 15:13:10.397 +08:00 [DBG] Connection id "0HLQS7TEGJNFP" sending FIN because: "The Socket transport's send loop completed gracefully."
2019-10-29 15:13:10.404 +08:00 [DBG] Hosting stopped
```

**Comment by scalablecory** [comment]
@livarcocc @Pilchie

**Comment by Pilchie** [comment]
@rynowak ?

**Comment by rynowak** [comment]
Does the public output contain the `.json` files? 

We had a bug for this during 3.0 and it was fixed here by special-casing these files for single-file publish so that they are still published. https://github.com/aspnet/AspNetCore-Tooling/pull/820/files

**Comment by MetSystem** [comment]
contain the .json files
![image](https://user-images.githubusercontent.com/7943054/68451562-3a680900-022a-11ea-9e58-99184f208382.png)

**Comment by MetSystem** [comment]
contain the .json files

![image](https://user-images.githubusercontent.com/7943054/68451620-6c796b00-022a-11ea-91b0-640a2d2f27cd.png)

**Comment by MetSystem** [comment]
AppContext.BaseDirectory=C:\Users\ADMINI~1\AppData\Local\Temp\.net\Wtc.Web\lmy2ywvm.jhm\`

**Comment by rynowak** [comment]
@MetSystem - that's the VS properties window - are the JSON files present next to the executable?

**Comment by MetSystem** [comment]
There is no json file.
```
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found 
```

**Comment by MetSystem** [comment]
The execution file exists josn, but does the resulting temporary directory not have a json file?

**Comment by swaroop-sridhar** [comment]
The behavior of the bundler is to pack all files in the publish directory -- except PDBs and files explicitly annotated to be left out -- into the bundle. Please see: https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#build-system-interface

So, for appsettings.json to be left beside the published app, is should be marked as <ExcludeFromSingleFile>true</ExcludeFromSingleFile> in the ASP.net project file that copies the content to the publish directory.

This is a dup of https://github.com/dotnet/core-setup/issues/7738
