### ISSUE TITLE
Problems Starting dotnet (First Timer)

### ISSUE THREAD

**Issue by arosado2895** [dotnet/core#3811]
λ dotnet new webApp -o myWebApp --no-https cd myWebApp
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment' threw an exception.
 ---> System.ArgumentException: External component has thrown an exception.
   at System.Globalization.CompareInfo.CompareString(ReadOnlySpan`1 string1, ReadOnlySpan`1 string2, CompareOptions options)
   at System.Globalization.CompareInfo.Compare(String string1, String string2, CompareOptions options)
   at System.Globalization.TextInfo.PopulateIsAsciiCasingSameAsInvariant()
   at System.Globalization.TextInfo.ChangeCaseCommon[TConversion](String source)
   at System.Globalization.TextInfo.ToLower(String str)
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by leecow** [comment]
If I'm reading correctly, it looks like you're running `dotnet new webApp -o myWebApp --no-https cd myWebApp` as a single command line.  If that's the case then you just need to update it a little to `dotnet new webApp -o myWebApp --no-https && cd myWebApp`

**Comment by krussokc** [comment]
I get the same exact error just trying to run "dotnet --info" from the Package Manager Console. It's a brand new Windows 10 Enterprise box with a fresh install of Visual Studio 2019 Enterprise. I can't build anything inside Visual Studio. When I try to build a fresh .NET Core MVC web application (using the UI), I get "rzc discover exited with code -2147450743"
