### ISSUE TITLE
Designer crash when hovering over usercontrol. dotnet core 3.0. 

### ISSUE THREAD

**Issue by ShemJM** [dotnet/core#3815]
I have created a user control with the following XAML:

```
<Button x:Class="MyApp.Controls.Buttons.TileButton"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             mc:Ignorable="d" 
             Height="115" Width="120" Cursor="Hand">
    <Button.Background>
        <LinearGradientBrush EndPoint="0.5,1" StartPoint="0.5,0">
            <GradientStop Color="#FF047E99"/>
            <GradientStop Color="#FF00858B" Offset="1"/>
        </LinearGradientBrush>
    </Button.Background>
    <Canvas>
        <Image Name ="ButtonIcon"  Height="53" Source="board.png" Canvas.Left="-23" Canvas.Top="-37" />
        <Label Name="ButtonLabel" Content="TEXT" Height="26" Foreground="White" HorizontalContentAlignment="Center" Canvas.Left="-14" Canvas.Top="21"/>
    </Canvas>
</Button>
```

I can add it to my pages but when I hover over it, the designer crashes and I get this error: 

```
System.InvalidOperationException
Calculated node path is invalid -- null->Page:Canvas
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.InstanceBuilders.IsolatedSurfaceInstanceManager.GetCorrespondingNodePath(IViewNode viewNode)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetCorrespondingSceneElement(IViewObject viewObject)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.FilterPotentialHit(IViewObject viewObject)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetFilterBehavior(IViewObject potentialHitTestTarget)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.GetFilterBehavior(IViewObject potentialHitTestTarget)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlHitTestHelper.HitTestContext.<PerformHitTest>d__15.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlSceneView.GetElementAtPoint(Point point, HitTestModifier hitTestModifier, InvisibleObjectHitTestModifier invisibleObjectHitTestModifier, ICollection`1 ignoredElements)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlSceneView.HitElementHelper.GetSelectableElementAtPoint(Point point)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.XamlSceneView.GetSelectableElementAtPoint(Point point, SelectionFor3D selectionFor3D, Boolean selectedOnly, Boolean smartInvisiblePanelSelect, Boolean isDrillingEnabled)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Views.SceneView.GetCachedSelectableElementAtPoint(Point point, SelectionFor3D selectionFor3D, Boolean isDrillingEnabled)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.ToolBehavior.CachedHitTest(Point pointerPosition, Boolean allowDrilling)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.Selection.ElementEditorBehavior.OnHoverOverNonAdorner(Point pointerPosition)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.ElementToolBehavior.OnHover(Point pointerPosition)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.EventRouter.ScopeElement_MouseMove_Internal(MouseEventArgs args)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Tools.EventRouter.<>c__DisplayClass59_0.<ScopeElement_MouseMoveCore>b__1()
   at Microsoft.VisualStudio.DesignTools.Utility.ProtectionZone.TrueProtectionZone.Execute(Action action)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

If I don't hover over it I can build my project and use the button as expected. 

It also works fine in .net framework. 

I have also tried with a Stackpanel. I get the same error but instead of canvas it says StackPanel

**Comment by scalablecory** [comment]
This issue was moved to dotnet/wpf#2206
