### ISSUE TITLE
Error migrating 3.1 code first to database get system.text.json error

### ISSUE THREAD

**Issue by vjdietrich** [dotnet/core#3966]
The error I have when attempting to do dotnet ef migrations:
System.MissingMethodException: Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.

Steps I have taken to try to fix: (tried to follow steps in closed issue here also)
I had 3.1 installed and am getting the same error. I uninstalled and reinstalled 3.1. Didn't help. I uninstalled and reinstalled System.Text.Json. Didn't help. I uninstalled all ef 3.1 packages and reinstalled at 3.0.1. I ran the suggested code dotnet tool install -g dotnet-ef --version 3.0.0 it said it was already installed. I tried it at 3.0.1 and it said it was already installed. I did not have dotnet cli tool utils loaded. I loaded it. I ran dotnet tool install --global dotnet-ef some instruction somewhere. Didn't help. Went back to everything in 3.1. Didn't help. I found in the properties that it was set to output type console. change it to windows application. Didn't help. Changed it back to console and removed the property group that changing it in the first place produced.  Please please please can someone help me?!

**Comment by leecow** [comment]
@ajcvickers

**Comment by carlossanlop** [comment]
Tagging area owners @ajcvickers @cheenamalhotra @david-engel to help with this issue.
