### ISSUE TITLE
Template "Console Application" could not be created.

### ISSUE THREAD

**Issue by Alan-Ng-2014** [dotnet/core#3977]
OS- Windows 10 Home version 1909

About Visual Studio Code-
Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Command Prompt-
PS C:\Program Files\Microsoft VS Code\Project folders\HelloWorld> dotnet new console

Error Message-
Template "Console Application" could not be created.
Error while processing file /content/ConsoleApplication-CSharp/Company.ConsoleApplication1.csproj       
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Microsoft VS Code\Project fole 
rs\HelloWorld\HelloWorld.csproj' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)    
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors, IReadOnlyList`1 locOperations)
![Cmd prompt screenshot](https://user-images.githubusercontent.com/58685486/70446835-a911de00-1ad8-11ea-8cd2-91105bb9e9e2.jpg)

**Comment by scalablecory** [comment]
You're trying to create files within "C:\Program Files\Microsoft VS Code\", but your user does not have privileges to that directory.

I'd suggest using a different directory, as Program Files is intended to hold installed apps, not user documents.
