### ISSUE TITLE
dotnet tutorial

### ISSUE THREAD

**Issue by niranjeen** [dotnet/core#4173]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Users\...\2020RegFm\appsettings.json' is denied.
   at System.IO.FileStream.SeekCore(SafeFileHandle fileHandle, Int64 offset, SeekOrigin origin, Boolean closeInvalidHandle)
   at System.IO.FileStream.ReadNativeAsync(Memory`1 destination, Int32 numBufferedBytesRead, CancellationToken cancellationToken)
   at System.IO.FileStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken, Int32& synchronousResult)
   at System.IO.FileStream.ReadAsyncTask(Byte[] array, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at _2020RegFm.Program.Main(String[] args) in C:\Users\.......\2020RegFm\Program.cs:line 16

![Annotation 2020-01-23 130511](https://user-images.githubusercontent.com/60233946/73010773-0b047980-3de1-11ea-90e9-4b54d950ac72.png)

**Comment by scalablecory** [comment]
It looks like you've got some files that your user doesn't have access to. Can you try creating the project in a different path?

**Comment by carlossanlop** [comment]
No response in 1 month. Closing.
