### ISSUE TITLE
dotnetcore2 not found on pip

### ISSUE THREAD

**Issue by joshmeek** [dotnet/core#4177]
# Issue Title

Running `pip install dotnetcore2` fails with the error:
```
ERROR: Could not find a version that satisfies the requirement dotnetcore2 (from versions: none)
ERROR: No matching distribution found for dotnetcore2
```

# General

Full pip traceback:
```
Given no hashes to check 0 links for project 'dotnetcore2': discarding no candidates
ERROR: Could not find a version that satisfies the requirement dotnetcore2 (from versions: none)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-0ams9apg'
ERROR: No matching distribution found for dotnetcore2
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for dotnetcore2
```

Attempting to install any of the `dotnetcore2` versions via pip fails with the same issue.

Environments tried:
MacOS 10.12.6, pip version 20.0.1
`python:3.7` Docker image, pip version 20.0.1

Running a `pip search` shows that the package exists:
```
$ pip search dotnetcore2
dotnetcore2 (2.1.11)  - .Net Core 2.1 runtime
```

**Comment by svick** [comment]
First of all, why are you trying to install .Net Core using pip? [The page for that package](https://pypi.org/project/dotnetcore2/) says that it's not intended for general use. And it seems it's not updated regularly.

Now, I'm no expert on pip, but based on my attempts, the log you posted is not the full log. Can you post the full output of `pip install dotnetcore2 -v`? For me, it starts with "Collecting dotnetcore2" and then goes on to list the locations it searches for that package, which could be the problem here.

**Comment by joshmeek** [comment]
@svick Here's the full `-v` output
```
pip install dotnetcore2 -v
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-sqqvlgld
Created temporary directory: /tmp/pip-req-tracker-wq0aezw4
Initialized build tracking at /tmp/pip-req-tracker-wq0aezw4
Created build tracker: /tmp/pip-req-tracker-wq0aezw4
Entered build tracker: /tmp/pip-req-tracker-wq0aezw4
Created temporary directory: /tmp/pip-install-s9m4l5yu
1 location(s) to search for versions of dotnetcore2:
* https://pypi.org/simple/dotnetcore2/
Fetching project page and analyzing links: https://pypi.org/simple/dotnetcore2/
Getting page https://pypi.org/simple/dotnetcore2/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/dotnetcore2/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/dotnetcore2/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_12_x86_64: https://files.pythonhosted.org/packages/4a/bd/20a47227bc21f1a52ca780abc077f91219eafc14f2597b7499fc17d81323/dotnetcore2-2.1.0-py3-none-macosx_10_12_x86_64.whl#sha256=d442320b454b9d39963c1aed2e7aed6083a667e461b75347dcffd23798ef7860 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/21/2f/eb05a02b10d21966959c32def6ac43cfd0f5f8f6f7441b2a1b6b1ce530db/dotnetcore2-2.1.0-py3-none-manylinux1_x86_64.whl#sha256=8a13bae313d91ed3bf22275288c3a771f074254c5a5a94c5a0a3fb71e422c720 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/c4/7e/9f60e8213eacbf382bfba3b8b72d27fae0c684a307df72e3916325b6d097/dotnetcore2-2.1.0-py3-none-win_amd64.whl#sha256=a4e2063ec92bbb9896cad081e6a92b40c5375ecf9fc1467ab4d02fba2409c6f6 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_12_x86_64: https://files.pythonhosted.org/packages/1d/ac/54ab8deb49912d90e3b3f6eedf9e2aed9ebdfa937db43ec93a1286c3aa60/dotnetcore2-2.1.2-py3-none-macosx_10_12_x86_64.whl#sha256=844b46a1101e57d52ce5f9a11c8565b133d3d78c2c1d07c79ccc96ee85df8632 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/8f/c9/29f668255f2ce1d3284535e6ac9964bf67bba5aa61e6b1c36ab220b7824e/dotnetcore2-2.1.2-py3-none-manylinux1_x86_64.whl#sha256=b1ad3db756ebacaa5841c5a83f9e4089ba926bd511ad00171863a0a27e6cc869 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/23/d0/bf2a0d6f6ab2a33090fd008cd6cb757d0eb8b828913148e426113366ecc4/dotnetcore2-2.1.2-py3-none-win_amd64.whl#sha256=6ca9818de9e6e70613ad4f29ace1b073a7b62eec8d4c95291e6d5112c18714ff (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_12_x86_64: https://files.pythonhosted.org/packages/84/d7/f9c5b14e6f12e47da62972979087c7781246de720129e5a17ce943047421/dotnetcore2-2.1.5-py3-none-macosx_10_12_x86_64.whl#sha256=7ccfe9e75893b7ad360622bf6ea2b687c78212b8ff5572c8e52e7dcb5708805b (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/05/68/bbd6076a04dc386fa463e1f78f605995fb85a04b4603da7b0d6459e645b8/dotnetcore2-2.1.5-py3-none-manylinux1_x86_64.whl#sha256=9d52fce30d7b4e2983168a31ddf7ef31f69f3d4751ea0884a2a5be41e222cc5d (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/70/40/abe38f3f423fe49bc4b26508ebfc2ba485af5b4521a6c9b06a7441458755/dotnetcore2-2.1.5-py3-none-win_amd64.whl#sha256=e86be261ad12fbfa2563ea4036b053511107ba6b8f3e9aa71ae8d31c8e1cba81 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_12_x86_64: https://files.pythonhosted.org/packages/33/a5/edb2312203d316e9df7f1311395eff487d89923165f9f2100bc793780188/dotnetcore2-2.1.6-py3-none-macosx_10_12_x86_64.whl#sha256=b3e7e05e597045c2a2fd1470abdda397d64ab52bf59ce490dd56a5fd1408b633 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/d6/a2/55295847b14eef1470f2103b6bfb5c8029feb471d5f5363376173aaf89be/dotnetcore2-2.1.6-py3-none-manylinux1_x86_64.whl#sha256=26b50ba5b43bbbb0e87cd85e6c512aa11019ec62505548a82bc05065cdfebfce (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/fe/5d/6633ddb4908fcb5919861abcadfacff419342e7bf201981022415b3190ad/dotnetcore2-2.1.6-py3-none-win_amd64.whl#sha256=be3a73ea7b6bbd3d1a1b9c0af3bec84688bd84413709476c2a42c6e00d3a0549 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_12_x86_64: https://files.pythonhosted.org/packages/12/bf/a8a10ea6abe078f2783d102ea77aa9ee884638f095c79a0b5a67fca77919/dotnetcore2-2.1.7-py3-none-macosx_10_12_x86_64.whl#sha256=10a0a098d01b557c0801abe7f44a6df052637d2662a96fb94c1afeabd8757da7 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/5e/ad/563e291f291ddae9967fc6347b5240e5ee5fdb173c33e0780c30ca8cd4c2/dotnetcore2-2.1.7-py3-none-manylinux1_x86_64.whl#sha256=f25639d44e22f246106aa27bc27882453f422a91ea89caed8ceacb658b95fd71 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/2b/68/7e04f181bd322fb4a8190cd03408703b25922229e1ffd407818b5756f70b/dotnetcore2-2.1.7-py3-none-win_amd64.whl#sha256=b55fea1884b9ba655fd2bcd633d06f130326abc718a458f220c4c9dad265dd40 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_12_x86_64: https://files.pythonhosted.org/packages/58/11/0235c4a3fb93de0bad7802607d36f6d1d543cfe03aa5bad76b849e711e73/dotnetcore2-2.1.8-py3-none-macosx_10_12_x86_64.whl#sha256=8dd3fb29b922b0bbec7febbd415d2abf28303e1b7ccb8ea1f4e0e342f0a7014a (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/4f/a1/3224449b9fd886f2be43173d47e8c9d42e2291bd4e6f0a9706ca6d0a4807/dotnetcore2-2.1.8-py3-none-manylinux1_x86_64.whl#sha256=24d6eb368ff15ecec1115a1ac860a9e206ea65b01479be0e2de0d13fbedf931b (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/c5/c3/bc3a19571a7c23ed49becd692511347d77bb069aacea4cbabdedb27e94f9/dotnetcore2-2.1.8-py3-none-win_amd64.whl#sha256=a1ffe2c84974bce5828a5bf6079f403b815cfed745d8db6b7aafe7a47ff6a6ce (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_9_x86_64: https://files.pythonhosted.org/packages/1d/d0/21edd4d5b0951eb4bb7052a29c9a4f63b9aaa7a4ca6e10b71f22d27f3606/dotnetcore2-2.1.8.1-py3-none-macosx_10_9_x86_64.whl#sha256=0b3cf11c69abe9648a891016818a3a07c5a2440c99edb4b5ba56c41a3df67d5d (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/fe/54/8606796e569217b1a48ff88bfdbf8b0babb948100e627d24e445e023a1fd/dotnetcore2-2.1.8.1-py3-none-manylinux1_x86_64.whl#sha256=9a0caf99eb00b8ad8150172997b58d1c090aa53e69d0dc901bed98238b73f98f (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win32: https://files.pythonhosted.org/packages/f0/f7/4117869dd77151f9111c0e0b34cb93abb79d01eecfffd8d3e0c695f4f192/dotnetcore2-2.1.8.1-py3-none-win32.whl#sha256=9014ddfa3cf73548e24ac028c4d1abe4b6099b5aee1aa51bbab2eaa7cc320521 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/f5/46/c3d5a2468ef165cf75c182b4c2cc1c873249d462d4f7997a834d51e7b0ce/dotnetcore2-2.1.8.1-py3-none-win_amd64.whl#sha256=b57546091533311735dbba057ad56b129cde25f5fe92850b9f61e9c072948338 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_9_x86_64: https://files.pythonhosted.org/packages/7d/25/bc3c4cb7f4c4acc72c5ab95c5e782864cf11624dfe5966df2ace0a13245f/dotnetcore2-2.1.9-py3-none-macosx_10_9_x86_64.whl#sha256=efdcf1aa464939fa1b1072b5eafe50889b53064348e1fa1b490ddf08dd904662 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/e7/11/699ec6c3ec5e73437834203e4b530fdc760517498208eaa0b37a7f1e10af/dotnetcore2-2.1.9-py3-none-manylinux1_x86_64.whl#sha256=2b37900bc423b38e38ff0546007b6ea591384ddb41f2773e32ad12347b7c3140 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win32: https://files.pythonhosted.org/packages/a5/e8/fd628f8355018500c2b0c1f38f5184a6f7024c5a5210a86cefada269aafa/dotnetcore2-2.1.9-py3-none-win32.whl#sha256=a72dfa4f48b63e2b0b027f39d4f4755076d678896a45b3866186a08296c35f41 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/0d/4f/00c4199f823eed390ad24bdc1ce779ce62b33ba87fe92541310a40818452/dotnetcore2-2.1.9-py3-none-win_amd64.whl#sha256=66759f18dc38752572c031211b17cda3296425e800ada04650da686c2e658da3 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_9_x86_64: https://files.pythonhosted.org/packages/3f/9a/aba7b77dd0b4a956cc2b443e11e24cd60d9c0703336ce54998984d66296a/dotnetcore2-2.1.10-py3-none-macosx_10_9_x86_64.whl#sha256=fee8aa9801018061ba287efeadb535fb3b7a0961ba248edccc1f739dcd3ca9f4 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/44/7f/b15ea4de647c35c49a4c1b2ae8d581ced3abf00c4edc4851e5c35a56fcc5/dotnetcore2-2.1.10-py3-none-manylinux1_x86_64.whl#sha256=d50c8d42cdf755f479d7ab15d61ad7d0fd2cf1512796ec96d391257447436e3f (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win32: https://files.pythonhosted.org/packages/81/17/cf74b4785a4628d153f3abe7073778248700d21e192e08af83081a2bd32a/dotnetcore2-2.1.10-py3-none-win32.whl#sha256=1b9629bd0c3ca731297195ff15016bb0bc80e89d974ab034956b0cd58d8e7eb5 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/88/83/f26e8c979dcc8e6e2a1c36f25741b33cc55f9c76cd6d20ae61c4b1ba1a03/dotnetcore2-2.1.10-py3-none-win_amd64.whl#sha256=40135abe6988da703d442bfc2f5d711d3349669123c2d68fa291dd11e1ff8e13 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_9_x86_64: https://files.pythonhosted.org/packages/13/67/fe266abfc8c6d9ff6fd767d5939bd39fd7415b7acaae331eef57c59408fd/dotnetcore2-2.1.11-py3-none-macosx_10_9_x86_64.whl#sha256=a335fb0abdaaeee7ba128b81b5350adfc5d2b2adf6a64cbc4d1a3b7cdf8560da (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/f7/25/72c743e07c5f251fb49b8a1a4a494145254d33e421ee116863deeef7865b/dotnetcore2-2.1.11-py3-none-manylinux1_x86_64.whl#sha256=632db1f5074d16093935576f4afcc711b272d0640f5a079cf82c922f17491762 (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win32: https://files.pythonhosted.org/packages/3c/10/acb59563843eec1e5bdb7eab2a4fd986824379a2c8cc4cc52c9171953ad5/dotnetcore2-2.1.11-py3-none-win32.whl#sha256=748334cd1b02e931d4ab75793bac15048faf18447de7a6228726cbe652c1c9cc (from https://pypi.org/simple/dotnetcore2/)
  Skipping link: none of the wheel's tags match: py3-none-win_amd64: https://files.pythonhosted.org/packages/7f/45/ef5f5609711f6e976ab1e39d03d0c246b6e03cc56942b5e324f58a34bf9b/dotnetcore2-2.1.11-py3-none-win_amd64.whl#sha256=15e42a98ddfe7bdc87f2b4995ab8cfd1bdadd3439e5d751464e52c1c21f4ce0f (from https://pypi.org/simple/dotnetcore2/)
Given no hashes to check 0 links for project 'dotnetcore2': discarding no candidates
ERROR: Could not find a version that satisfies the requirement dotnetcore2 (from versions: none)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-wq0aezw4'
ERROR: No matching distribution found for dotnetcore2
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for dotnetcore2
```

**Comment by joshmeek** [comment]
Closing. Looks to be directly related with the version of pip https://github.com/pypa/pip/issues/7626

**Comment by svick** [comment]
@joshmeek I'm glad to hear that you figured out where the problem was.
