### ISSUE TITLE
attempt to create "Hello World" app

### ISSUE THREAD

**Issue by acnicholls** [dotnet/core#4519]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: debian10
architecture:ARM64

manual install of dotnet-sdk-3.1.201
attempt to create "Hello World" app

################
root@debian10:~# dotnet new console -o myApp
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
Aborted

**Comment by scalablecory** [comment]
Take a look at the [Linux Prerequirements](https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md) to ensure you've got everything needed. Specifically, it looks like you need to install libicu.

**Comment by acnicholls** [comment]
Thanks for the link.  I think I can handle that.

**Comment by acnicholls** [comment]
installing the libicu63 for debian10 package worked.  Thanks @scalablecory
