### ISSUE TITLE
Couldn't find a valid ICU package installed on the system. 

### ISSUE THREAD

**Issue by qyangaa** [dotnet/core#5019]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: linux

I followed  https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md#troubleshooting
to install the package and change library path. But still doesn't work. 

dotnet run
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at System.Text.EncodingHelper.GetCharset()
   at System.Text.EncodingHelper.GetEncodingFromCharset()
   at System.ConsolePal.GetConsoleEncoding()
   at System.Console+<>c.<get_OutputEncoding>b__19_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Console.get_OutputEncoding()
   at System.Console.CreateOutputWriter(System.IO.Stream)
   at System.Console+<>c.<get_Out>b__26_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Console.get_Out()
   at System.Console.WriteLine(System.String)
   at myApp.Program.Main(System.String[])

**Comment by mairaw** [comment]
@dagood @leecow can you help with this issue?

**Comment by dagood** [comment]
@tarekgh may be able to help.

**Comment by tarekgh** [comment]
@qyangaa this means the ICU library is not correctly installed on your system. 

could you please send the output of the execution steps https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md?rgh-link-date=2020-08-04T23%3A33%3A28Z#troubleshooting?

**Comment by jmp75** [comment]
@tarekgh  If I may; I encountered the very same problem, using  Debian 11 (currently the 'testing' version). This is following installation instructions as close as possible, using "snap"  as per the [debian dotnet install doc](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian). I would have preferred using debian packages but this does not yet work for Debian 11 (actually, complained about not being able to find the libicu dependency to install).

```
~/src/myApp$ dotnet --version
3.1.402
~/src/myApp$ which dotnet
/snap/bin/dotnet
~/src/myApp$ snap list
Name               Version    Rev   Tracking       Publisher    Notes
core               16-2.46.1  9993  latest/stable  canonical✓   core
core18             20200724   1885  latest/stable  canonical✓   base
dotnet-runtime-31  3.1.8      9     latest/stable  dotnetcore✓  -
dotnet-sdk         3.1.402    98    3.1/stable     dotnetcore✓  classic
```

`locate libicu | grep snap` shows the presence of "libicu" files such as "/snap/dotnet-sdk/98/usr/lib/x86_64-linux-gnu/libicudata.so.60". Not sure this is what we are after, or if the debian package manager.

`aptitude search libicu` shows that `libicu-dev` and `libicu67` are installed, and I appear to have all the right dependencies as per [the dotnet install on debian - dependencies](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#dependencies). 

FWIW ss a longtime .NET/mono developer but not active with it for a few years, I am a bit confused by the experience re-acquainting myself with the latest ecosystem.

**Comment by tarekgh** [comment]
@qyangaa @jmp75 could you please follow the issue https://github.com/dotnet/runtime/issues/43052 which is tracking fixing same issue (I guess)?

**Comment by dagood** [comment]
https://github.com/dotnet/runtime/issues/43052 is specifically about this:

> I would have preferred using debian packages but this does not yet work for Debian 11 (actually, complained about not being able to find the libicu dependency to install).

The rest of the comment seems to be about an issue with the .NET Snap, which I'm not very familiar with.

**Comment by tarekgh** [comment]
> The rest of the comment seems to be about an issue with the .NET Snap, which I'm not very familiar with.

Do you know who can help with it? 

CC @safern

**Comment by jmp75** [comment]
I got an installation working with the ICU working after noticing [that reply](https://github.com/dotnet/source-build/issues/782#issuecomment-700835197) and prior discussions. I thought at first read what was referred to was compilation from source but this is not and much simpler a process, so may be worth expanding here. This refers to the [Manual Install](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#manual-install) option. 

Steps:

Downloading the "Binaries" tarball for the SDK x64 of [.NET core 3.1](https://dotnet.microsoft.com/download/dotnet-core/3.1)
`tar zxf dotnet-sdk-3.1.402-linux-x64.tar.gz -C "$HOME/dotnet"`

`nano ~/.bashrc` then adding 

```sh
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
``` 

All seem to work well this way, `dotnet run` or direct binary invocation. I am actually unclear as to exactly why the 'missing ICU' goes away installing this way, but will take it as is.

**Comment by dagood** [comment]
> I am actually unclear as to exactly why the 'missing ICU' goes away installing this way

As long as you have some version of the libicu binaries installed ([from version 50 to 255 currently](https://github.com/dotnet/runtime/blob/ee20c571b3079b77382cbeae537b37a744b1b469/src/libraries/Native/Unix/System.Globalization.Native/pal_icushim.c#L169-L171)), .NET Core will find it and use it. The Debian package is just more restrictive because it has a list of specific package dependencies rather than a numeric range.

**Comment by xiangzhai** [comment]
:mips-interest

**Comment by xiangzhai** [comment]
Hi @qyangaa

export CLR_ICU_VERSION_OVERRIDE="50.1"

If your RHEL icu version is 50.1, it is able to run `yum info icu` about the version.

We met [the similar issue](https://github.com/dotnet/runtime/issues/13527) when porting to MIPS64.

Thanks,
Leslie Zhai
