### ISSUE TITLE
System.DivideByZero exception in System.Threading.FastRandom.Next(Int32 maxValue)

### ISSUE THREAD

**Issue by torqdev** [dotnet/core#5032]
# Issue Title

A DivideByZeroException was thrown by the FastRandom.Next method in the System.Threading dll on dotnet Core 3.1

# General

This is kind of a one-off, I don't know what the value passed in as maxValue since the symbols weren't loaded when the exception was thrown but after loading the exception was thrown with this information:

```
System.DivideByZeroException
  HResult=0x80020012
  Message=Attempted to divide by zero.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.FastRandom.Next(Int32 maxValue) in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 723
   at System.Threading.ThreadPoolWorkQueue.Dequeue(ThreadPoolWorkQueueThreadLocals tl, Boolean& missedSteal) in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 513
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 605
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /_/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
```

At the following code:

```c#
    // Simple random number generator. We don't need great randomness, we just need a little and for it to be fast.
    internal struct FastRandom // xorshift prng
    {
        private uint _w, _x, _y, _z;

        public FastRandom(int seed)
        {
            _x = (uint)seed;
            _w = 88675123;
            _y = 362436069;
            _z = 521288629;
        }

        public int Next(int maxValue)
        {
            Debug.Assert(maxValue > 0);

            uint t = _x ^ (_x << 11);
            _x = _y; _y = _z; _z = _w;
            _w = _w ^ (_w >> 19) ^ (t ^ (t >> 8));

            return (int)(_w % (uint)maxValue); // System.DivideByZero exception thrown here
        }
    }
```

**Comment by benaadams** [comment]
Its the count of ThreadPool queues, which should be at least 1 🤔

https://github.com/dotnet/runtime/blob/89af52b01bb3b24e2b7b97bd6343ceb7d330c4e3/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs#L485-L491
```csharp
// finally try to steal from another thread's local queue
WorkStealingQueue[] queues = WorkStealingQueueList.Queues;
int c = queues.Length;
Debug.Assert(c > 0, "There must at least be a queue for this thread.");
int maxIndex = c - 1;
int i = tl.random.Next(c);
```

/cc @stephentoub

**Comment by IronSean** [comment]
The debug asserts also there to verify it. We we running our code in debug mode with the debugger attached, but since symbols weren't loaded for external code I'm not sure if those dlls would be running in debug more or would just be compiled production code?

We were doing a multi-day test of a system with a fair amount of spawning and orchestrating of small, short lived tasks. I'm not sure if that made the error more likely to happen or just gave us the volume necessary to hit it.

**Comment by svick** [comment]
@benaadams If there is one queue, then `c` will be 1, so `maxIndex` will be 0, which means `FastRandom.Next()` will throw `DivideByZeroException`. Or am I missing something?

@IronSean Debug asserts in the runtime are only triggered if you use debug build of the runtime. And that usually only happens if you compile it yourself.

**Comment by benaadams** [comment]
> Or am I missing something?

It passes `c` into the method, not `maxIndex` which is used to avoid a mod `%` per loop
