### ISSUE TITLE
Windows authentication in HttpClient not working over https in .NET 5

### ISSUE THREAD

**Issue by igor-tk** [dotnet/core#5042]
# Windows authentication in HttpClient not working over https in .NET 5

Windows authentication (NTLM or Kerberos) in HttpClient doesn't work over https in .NET 5 although in .NET Core 3.1 it does.

Software versions:
Windows 10 Pro
IIS Express 10
.NET - dotnet-sdk-5.0.100-preview.7.20366.6-win-x64

Simple table that describes what works and what doesn't:
```
Url                                 |  Has auth (NTLM/Kerberos)   | Https  |  Works?
----------------------------------------------------------------------------------------------
http://localhost:44388/api/values   |                          No |    No   |     Yes  
http://localhost:44388/api/values   |                         Yes |    No   |     Yes  
https://localhost:44388/api/values  |                          No |   Yes   |     Yes  
https://localhost:44388/api/values  |                         Yes |   Yes   |      No  
```

# Sample code and error

```
var httpClientHandler = new HttpClientHandler
            {
                Credentials = CredentialCache.DefaultNetworkCredentials
            };
var httpClient = new HttpClient(httpClientHandler, true);     
var url = "https://localhost:44388/api/values";
var res = httpClient.GetAsync(url).Result;
```

Error:
System.ComponentModel.Win32Exception "The token supplied to the function is invalid"} 

   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.<SendWithNtAuthAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__66.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.AuthenticationHelper.<SendWithAuthAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__76.MoveNext()

For server app I created simple "Hello world" application from Visual Studio 2019 - Web Application (.NET Framework 4.8) with Windows authentication and https.

If I use production web server (apache in my case), I get the same error.

**Comment by oxABA** [comment]
I have the same problem with WebClient with .net5 Preview7. Works when switch project to .net Core 3.1.

```
    System.Net.WebClient client = new System.Net.WebClient();
    client.Credentials = new System.Net.NetworkCredential("User", "PW", "Domain");
    byte[] data = client.DownloadData("https://xxxxxxx");
```

An exception occurred during a WebClient request.
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)

Win32Exception: Das Token, das der Funktion übergeben wurde, ist ungültig
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)

**Comment by wfurt** [comment]
This should be fixed with https://github.com/dotnet/runtime/pull/40222 in next preview and daily builds.
