### ISSUE TITLE
.NET 5 Preview 8 - Nuget Certificate issue on dotnet restore

### ISSUE THREAD

**Issue by Siberis** [dotnet/core#5134]
# Command `dotnet restore` fails with Nuget certificate issue after migration to .NET Preview 8

I wish to try new awesome functionalities from .NET 5 Preview 8 in Blazor WebAssembly. After performing normal installation (download installer and run it) I try to generate new blazorwasm project but it ends with following error:

```
PS C:\projects> dotnet new blazorwasm -o test83
The template "Blazor WebAssembly App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/5.0-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on C:\projects\test83\test83.csproj...
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\projects\test83\test83.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [C:\projects\test83\test83.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\projects\test83\test83.csproj]
Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

I try to perform suggested `dotnet restore` but it also fails with following error (logs with `-v d`)

```

       Task "RestoreTask"
         (in) RestoreGraphItems Count '8'
         (in) RestoreDisableParallel 'False'
         (in) RestoreNoCache 'False'
         (in) RestoreIgnoreFailedSources 'False'
         (in) RestoreRecursive 'True'
         (in) RestoreForce 'False'
         (in) HideWarningsAndErrors 'False'
         (in) RestoreForceEvaluate 'False'
         (in) RestorePackagesConfig 'False'
         Running restore with 8 concurrent jobs.
         Reading project file C:\projects\test8\test8.csproj.
         The restore inputs for 'test8' have changed. Continuing restore.
         Restoring packages for C:\projects\test8\test8.csproj...
         Restoring packages for net5.0...
         Resolving conflicts for net5.0...
     1>C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\projects\test8\test8.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [C:\projects\test8\test8.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\projects\test8\test8.csproj]
         NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json.
          ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
          ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
            at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|184_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
            at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
            at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
            at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
            --- End of inner exception stack trace ---
            at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, Boolean allowHttp2, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
            at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at NuGet.Protocol.ServerWarningLogHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            at NuGet.Protocol.HttpSourceAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
            at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass2_1.<<SendAsync>b__0>d.MoveNext()
         --- End of stack trace from previous location ---
            at NuGet.Protocol.TimeoutUtility.StartWithTimeout[T](Func`2 getTask, TimeSpan timeout, String timeoutMessage, CancellationToken token)
            at NuGet.Protocol.HttpRetryHandler.SendAsync(HttpRetryHandlerRequest request, String source, ILogger log, CancellationToken cancellationToken)
            at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Boolean isRetry, Boolean isLastAttempt, Guid sessionId, ILogger log, CancellationToken cancellationToken)
            at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
         --- End of stack trace from previous location ---
            at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
            at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
            at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
            at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
            --- End of inner exception stack trace ---
            at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
            at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
            at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
            at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
            at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
            at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
            at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
            at NuGet.Commands.SourceRepositoryDependencyProvider.EnsureResource()
            at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
            at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
         --- End of stack trace from previous location ---
            at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
            at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass9_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
         --- End of stack trace from previous location ---
            at NuGet.DependencyResolver.ResolverUtility.FindLibraryFromSourcesAsync(LibraryRange libraryRange, IEnumerable`1 providers, Func`2 action)
            at NuGet.DependencyResolver.ResolverUtility.FindLibraryByVersionAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 providers, SourceCacheContext cacheContext, ILogger logger, CancellationToken token)
            at NuGet.DependencyResolver.ResolverUtility.FindPackageLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
            at NuGet.DependencyResolver.ResolverUtility.ResolvePackageLibraryMatchAsync(LibraryRange libraryRange, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
            at NuGet.Commands.ProjectRestoreCommand.ResolveDownloadDependencies(RemoteWalkContext context, ConcurrentDictionary`2 downloadDependenciesCache, TargetFrameworkInformation targetFrameworkInformation, CancellationToken token)
            at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable`1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity)
            at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
            at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
            at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
            at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken)
            at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)
       Done executing task "RestoreTask" -- FAILED.
     1>Done building target "Restore" in project "test8.csproj" -- FAILED.
     1>Done Building Project "C:\projects\test8\test8.csproj" (Restore target(s)) -- FAILED.

Build FAILED.

       "C:\projects\test8\test8.csproj" (Restore target) (1) ->
       (Restore target) ->
         C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\projects\test8\test8.csproj]
       C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [C:\projects\test8\test8.csproj]
       C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\projects\test8\test8.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:03:08.00
```

I tried many installation of Preview 7 and Preview 8 and I receive the same results on Preview7 `dotnet restore` works fine and on Preview8 I receive errors. So it looks like internal problem of Preview8. It is some breaking change or my misconfiguration which I missed or real issue with Preview8.

**Comment by rdiazconcha** [comment]
I have this same issue with any package in any project.

For example, after creating a new webapi project by using `dotnet new webapi -n testapi`, I run the following command: 

`dotnet add package Microsoft.EntityFrameworkCore --version 5.0.0-preview.8.20407.4`

and after 4+ minutes, I receive the following output:

```
  Determining projects to restore...
  Writing C:\Users\rdiaz\AppData\Local\Temp\tmpA80D.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore' into project 'D:\testapi\testapi.csproj'.
info : Restoring packages for D:\testapi\testapi.csproj...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   The SSL connection could not be established, see inner exception.
error:    Received an unexpected EOF or 0 bytes from the transport stream.
```

**Comment by rdiazconcha** [comment]
I'm using Windows 10 Insiders too.  I fixed this issue by disabling TLS 1.3 under the following registry key: HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client  (Enable=0 [DWORD]) 

Hope this helps!

**Comment by Siberis** [comment]
I do not have registry key like that. Under Protocols I have only one key: SSL 2.0, Adding TLS key does not help

**Comment by rdiazconcha** [comment]
I didn't have it as well.  I created it by hand.

**Comment by Siberis** [comment]
Confirmed, adding key resolve this problem. Question is why this issue happened. What changed in dotnet?

**Comment by rdiazconcha** [comment]
.NET Preview 8 now uses the configured TLS version in the operating system, and on Windows Insiders they changed the default to 1.3.  I think is more related with Windows 10 insiders.  I'm glad this helped you.  Cheers!
