### ISSUE TITLE
Dont work linux Postgres connection on net core

### ISSUE THREAD

**Issue by alexandrlagun1** [dotnet/core#5388]
When i try connection on postgres server in ubuntu 18.4, throw exception.
My connection string: "Server=10.0.0.10;Port=5432;Database=UIGMI5;User id=postgres;password=P@ssw0rd"

Unhandled exception. Npgsql.PostgresException (0x80004005): 28000: � pg_hba.conf ��� ������ ��� ���������� "10.0.0.117", ������������ "postgres", ���� "UIGMI5", SSL ����.
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnection.Open()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at BlazorUigmi.DB.ApplicationPGContext.EnsureCreated() in C:\Users\Alexander.Lagun\source\repos\BlazorUigmi\ubunta2\BlazorUigmi_1.2\BlazorUigmi\BlazorUigmi\DB\ApplicationPGContext.cs:line 141
   at BlazorUigmi.DB.MainContext.EnsureCreated() in C:\Users\Alexander.Lagun\source\repos\BlazorUigmi\ubunta2\BlazorUigmi_1.2\BlazorUigmi\BlazorUigmi\DB\MainContext.cs:line 56
   at BlazorUigmi.CommonClasses.DBExtensions.AddDbContext(IServiceCollection services) in C:\Users\Alexander.Lagun\source\repos\BlazorUigmi\ubunta2\BlazorUigmi_1.2\BlazorUigmi\BlazorUigmi\CommonClasses\DbExtansions.cs:line 18
   at BlazorUigmi.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Alexander.Lagun\source\repos\BlazorUigmi\ubunta2\BlazorUigmi_1.2\BlazorUigmi\BlazorUigmi\Startup.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at BlazorUigmi.Program.Main(String[] args) in C:\Users\Alexander.Lagun\source\repos\BlazorUigmi\ubunta2\BlazorUigmi_1.2\BlazorUigmi\BlazorUigmi\Program.cs:line 23
  Exception data:
    Severity: �����
    SqlState: 28000
    MessageText: � pg_hba.conf ��� ������ ��� ���������� "10.0.0.117", ������������ "postgres", ���� "UIGMI5", SSL ����.
    File: d:\pginstaller_12.auto\postgres.windows-x64\src\backend\libpq\auth.c
    Line: 520
    Routine: ClientAuthentication
Aborted (core dumped)

**Comment by carlossanlop** [comment]
We don't own `NpgsqlConnection`. Please open an issue in the appropriate place to log bugs for that database manager.
