### ISSUE TITLE
Issue with standard steps

### ISSUE THREAD

**Issue by campbep** [dotnet/core#5390]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: Ubuntu 10.04 focal

dotnet run
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.StringComparer.get_OrdinalIgnoreCase()
   at Microsoft.Extensions.Configuration.ConfigurationProvider..ctor()
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder..ctor(Microsoft.Extensions.Hosting.IHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)
   at wwwnet.Program.CreateHostBuilder(System.String[])
   at wwwnet.Program.Main(System.String[])

**Comment by carlossanlop** [comment]
> Couldn't find a valid ICU package installed on the system

Have you tried installing the ICU package for Ubuntu?

**Comment by carlossanlop** [comment]
No reply in 9 days. Closing.
