### ISSUE TITLE
Unable to run dotnet core in AWS ARM based instance (e.g. A1, C6g)

### ISSUE THREAD

**Issue by yb101** [dotnet/core#5417]
# Issue Title

Unable to run dotnet core in AWS ARM based instance (e.g. A1, C6g)

# General

I was trying to run ".NET Core 3.1 SDK (v3.1.403) - Linux ARM64 Binaries" in AWS ARM based instance, e.g. A1, C6g. But get below error msg. Does anyone else experience it? Is there a resolution? 

[ec2-user@ip-172-31-27-186 dotnet_3]$ ./dotnet -h
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])

**Comment by yb101** [comment]
To add EC2 AMI name

 amzn2-ami-hvm-2.0.20200917.0-arm64-gp2

**Comment by yb101** [comment]
Oh. I found the way. Should add below

 "configProperties": {
      "System.Globalization.Invariant": true
    }

to sdk/3.1.403/dotnet.runtimeconfig.json file. 
To make final content like:

{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.9"
    },
    "configProperties": {
      "System.Globalization.Invariant": true
    }
  }
}

**Comment by carlossanlop** [comment]
> Couldn't find a valid ICU package installed on the system

Have you tried installing ICU for your specific Linux distro?

**Comment by carlossanlop** [comment]
No reply in 9 days. Closing.
