### ISSUE TITLE
Template "Blazor WebAssembly App" could not be created.

### ISSUE THREAD

**Issue by tomtom1992** [dotnet/core#5868]
I have the following issue when running

dotnet new blazorwasm

or any other template:

Template "Blazor WebAssembly App" could not be created.
Error while processing file /content/ComponentsWebAssembly-CSharp/Client/App.razor
System.IO.FileNotFoundException: Could not find file 'C:\Users\Thomas\Documents\Projects\CMSTest\App.razor'.
File name: 'C:\Users\Thomas\Documents\Projects\CMSTest\App.razor'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors, IReadOnlyList`1 locOperations)

**Comment by tomtom1992** [comment]
I already tried to:

- Repair my Installation of .NET 5 SDK
