### ISSUE TITLE
Unable to add workflow in .NET 5.0 even after installing uipath.workflow package .

### ISSUE THREAD

**Issue by srvkmr130** [dotnet/core#5936]
### Description :
Currently using .NET 5.0 and used uipath.workflow as it ports WF runtime to .NET 5 .Even after this I am unable to create a workflow in .NET 5.0 .

_System.ServiceModel and System.Activities cannot be referenced in any .NET 5.0 application_ 

**On opening the activity.xaml file:**
```
System.InvalidOperationException: The framework identifier '.NETCoreApp' is not supported in the workflow designer. Please use '.NET Framework' or '.NETFramework' as identifier.
Server stack trace: 
   at System.Activities.Presentation.DesignerConfigurationService.set_TargetFrameworkName(FrameworkName value)
   at Microsoft.VisualStudio.Activities.AddIn.WorkflowDesignerAddIn.SetDesignerEventsSink(IProcessDesignerEventsAddInView designerEventsSink, Boolean overriding)
   at Microsoft.VisualStudio.Activities.AddInAdapter.IDesignerContractToViewAddInAdapter.SetDesignerEventsSink(IProcessDesignerEventsContract designerEventsContract, Boolean overriding)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.Activities.DesignerContract.IDesignerContract.SetDesignerEventsSink(IProcessDesignerEventsContract designerEventsContract, Boolean overriding)
   at Microsoft.VisualStudio.Activities.HostAdapter.IDesignerViewToContractHostAdapter.SetDesignerEventsSink(IProcessDesignerEventsHostView designerEventsHostView, Boolean overriding)
   at Microsoft.VisualStudio.Activities.EditorPane.CreateWorkflowDesignerInIsolatedMode()

```

### Regression? 
In Previous .NET Frameworks we are able to use this .

Is there any way to use Workflow in .NET 5 ?

**Comment by carlossanlop** [comment]
uipath.workflow looks to be a third party tool. Please consider asking them for guidance. This seems to be their repo: https://github.com/UiPath/CoreWF

AFAIK WF is not officially supported in .NET Core.
