### ISSUE TITLE
double value in appsettings can't be read

### ISSUE THREAD

**Issue by juliengomes** [dotnet/core#608]
Not sure where to put this issue so I just put it here.

In my appsetting.json file, I have a double value in dictionnary, something like 
```
{
    "A": {
        "B": {
            "EUR": 0.5,
            "USD": 0.5
        }
   }
}
```

This is the code I have in my Startup.cs file 

```
services.Configure<MyOptions>(options => Configuration.GetSection("A").Bind(options));
```

And this is MyOptions
```
namespace Options
{
    public class MyOptions
    {
        public Dictionary<string,double> B { get; set; }
    }
}
```

When I try to run this, I get the following error
```
Unhandled Exception: System.InvalidOperationException: Failed to convert '0,5' to type 'System.Double'. ---> System.Exception: 0,5 is not a valid value for Double. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, String value)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, String value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindDictionary(Object dictionary, Type dictionaryType, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at LOL.Startup.<ConfigureServices>b__5_0(MyOptions options) in /Users/LOL/Startup.cs:line 41
```

This is my dotnet version `1.0.0-preview2-1-003177` and I run it on a french macbook pro. I say french because in french "0,5" is the right string conversion for 0.5, so it might be the cause, but it's still a bug because I need double there, even if I go through casting.

**Comment by Petermarcu** [comment]
@gkhanna79

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/corefx #19175](https://github.com/dotnet/corefx/issues/19175) via [**ZenHub**](https://www.zenhub.com/)
