### ISSUE TITLE
.NET April 2021 Update - .NET 5.0.5, .NET Core 3.1.14 and .NET Core 2.1.27

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#6129]
Release Notes 
[5.0.5](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.5/5.0.5.md)
[3.1.14](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.14/3.1.14.md)
[2.1.27](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.27/2.1.27.md)

Please report any issues you find with .NET 5.0.5 either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

-----
Status of availability of SDK on Microsoft's Linux feeds: 

| Distro | 5.0.5 | 3.1.14 | 2.1.27 | 
|--|--|--|--|
| Ubuntu 16.04   |  ✅  |  ✅  |  ✅  | 
| Ubuntu 18.04    | ✅  | ✅  | ✅   | 
| Ubuntu 20.04   |  ✅ | ✅  |  ✅  | 
| Ubuntu 20.10    |  ✅ | ✅  | ✅   | 
| Centos 7       |✅ | ✅  | ✅   | 
| Debian 9   |   ✅ | ✅  | ✅   | 
| Debian 10  |    ✅ | ✅  | ✅   | 
| Fedora 32  |   ✅ | ✅  | ✅   | 
| Fedora 33  |   ✅ | ✅  | ✅   | 
| OpenSUSE 15 |     ✅ | ✅  | ✅   | 
| SLES 12   |     ✅ | ✅  | ✅   | 
| SLES15  |   ✅ | ✅  | ✅   | 

Note: This list refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

- [x] .NET SDK 5.0.202 fails to compile netcoreapp3.1 projects https://github.com/dotnet/sdk/issues/16758 https://github.com/dotnet/sdk/issues/16765 - We have pushed NuGet packages for 3.1.14 and 2.1.27 to resolve this issue.
- [ ] There is known issue https://github.com/dotnet/core/issues/6161 with snaps while running a .NET Core 3.1 applications on Ubuntu 20.04 and Ubuntu 20.10. We recommend to follow the [install steps using package manager](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.14/3.1.14-install-instructions.md#install-using-a-package-manager) for these Distros

**Comment by fuchanghao** [comment]
Can't get ".NET Desktop Runtime 5.0.5"  by windows update and My Visual Studio 16.9 still install ".NET SDK 5.0.201"

**Comment by QHQuach** [comment]
I am getting below unit test execution error both in Visual Studio IDE 2019 (16.9.3) and command line through vstest.console.exe (16.9.1). This happens even after installing the latest .NET 5.0.5 (5.0.202 SDK). Any idea?

I even tried to debug into the Newtonsoft 13.0.1 but only to find the constructor just quits and throws the exception. The module runs fine during runtime.

The failing unit test project is using the following:
- xunit (2.4.1)
- xunit.runner.visualstudio (2.4.3)
- NSubstitute (4.2.2)
- mstest.testframework (2.2.3)
- Mircrosoft.NET.Test.Sdk (16.9.4)
- Microsoft.QualityTools.Testing.Fakes (16.7.4-beta.20330.2)

It is testing components/apps that are .NET Core 2.1 targeting .NET FW 4.6.2. Below is the stack trace from the unit test command line execution

  Error Message:
   System.InvalidProgramException : Common Language Runtime detected an invalid program.
  Stack Trace:
     at Newtonsoft.Json.Linq.JContainer..ctor(JContainer other)
   at Newtonsoft.Json.Linq.JObject..ctor(JObject other)
   at Newtonsoft.Json.Linq.JObject.CloneToken()
   at Newtonsoft.Json.Linq.JContainer.EnsureParentToken(JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.TryAddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JArray.Add(JToken item)
   at MyUnitTests.<MyTest_HasNeededData_ReturnsData>d__45.MoveNext() in XXXXXXXXXXXXXXXXXXXXXXX:line 643
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by XieJJ99** [comment]
Version 3.1.14 is missing in the release json: [https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.1/releases.json] .

**Comment by rbhanda** [comment]
Hello @XieJJ99 releases.json is updated for 3.1

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/6247
