### ISSUE TITLE
Cannot run dotnet watch on Fedora 33 after upgrading to dotnet 5.0

### ISSUE THREAD

**Issue by GeeWee** [dotnet/core#6134]
### Description
For some reason the .NET that is bundled with Fedora does not work properly. I wasn't sure whether to report it here or not, but seeing as #5596 was tracked here, I figured this might be as well.

It seems like all the commands from "bundled tools" do not work, but the "regular" commands do.

E.g. `dotnet run` and `dotnet build` work fine, but other commands do not:

```shell
$ dotnet watch
Cannot find command 'dotnet watch', run the following command to install

dotnet tool install --global dotnet-watch

$ dotnet csi
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-csi does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
The commands that do not work seem to correlate with the commands listed under
`Additional commands from bundled tools:` when calling `dotnet --info`

This behaviour only exists when installing dotnet5.0-sdk from the fedora `updates` repository.

### Dotnet info
```shell
.NET SDK (reflecting any global.json):
 Version:   5.0.104
 Commit:    ca6b6acadb

Runtime Environment:
 OS Name:     fedora
 OS Version:  33
 OS Platform: Linux
 RID:         fedora.33-x64
 Base Path:   /usr/lib64/dotnet/sdk/5.0.104/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.108 [/usr/lib64/dotnet/sdk]
  5.0.104 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Installed packages
```shell
$ sudo dnf list installed "*dotnet*"                                                                                        
Installed Packages
dotnet-apphost-pack-3.1.x86_64                                              3.1.8-1.fc33                                              @fedora 
dotnet-apphost-pack-5.0.x86_64                                              5.0.4-1.fc33                                              @updates
dotnet-host.x86_64                                                          5.0.4-1.fc33                                              @updates
dotnet-hostfxr-3.1.x86_64                                                   3.1.8-1.fc33                                              @fedora 
dotnet-hostfxr-5.0.x86_64                                                   5.0.4-1.fc33                                              @updates
dotnet-runtime-3.1.x86_64                                                   3.1.8-1.fc33                                              @fedora 
dotnet-runtime-5.0.x86_64                                                   5.0.4-1.fc33                                              @updates
dotnet-sdk-3.1.x86_64                                                       3.1.108-1.fc33                                            @fedora 
dotnet-sdk-5.0.x86_64                                                       5.0.104-1.fc33                                            @updates
dotnet-targeting-pack-3.1.x86_64                                            3.1.8-1.fc33                                              @fedora 
dotnet-targeting-pack-5.0.x86_64                                            5.0.4-1.fc33                                              @updates
dotnet-templates-3.1.x86_64                                                 3.1.108-1.fc33                                            @fedora 
dotnet-templates-5.0.x86_64                                                 5.0.104-1.fc33                                            @updates
```

### Configuration
This is on a Fedora 33 on x86.
```shell
$ uname -a
Linux localhost.localdomain 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Regression?

This seems like an obvious regression to me. However I can find no one else with this problem which seems strange, so I suspect there are some other factors at play here.

If I uninstall dotnet 5.0 it works instantly
```shell
$ sudo dnf remove dotnet-sdk-5.0
$ dotnet watch
Microsoft DotNet File Watcher 3.1.8-servicing.20461.1

Usage: dotnet watch [options] [[--] <arg>...]
...
```

### Other information
If I run dotnet watch on .NET 5 with the -d flag enabled I get the following output
```
Telemetry is: Disabled
projectfactory: MSBUILD_EXE_PATH = /usr/lib64/dotnet/sdk/5.0.104/MSBuild.dll
projectfactory: MSBuild project path = /home/geewee/programming/swiss-army-knife/Source/SCM.SwissArmyKnife/SCM.SwissArmyKnife.csproj
projecttoolscommandresolver: resolving commandspec from 0 Tool Libraries.
projecttoolscommandresolver: failed to resolve commandspec from library.
Microsoft.DotNet.Cli.Utils.CommandAvailableAsDotNetToolException: Cannot find command 'dotnet watch', run the following command to install

dotnet tool install --global dotnet-watch
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by omajid** [comment]
Thanks for reporting this!

This was a mistake on our part.

We are tracking the fix here: https://github.com/dotnet/source-build/issues/2109

We are also looking at ways to make sure we test for this (via [gating tests in Fedora](https://src.fedoraproject.org/rpms/dotnet5.0/c/2eade32a3739a78fda898b0a23c5596d96c5e74d?branch=rawhide)) and block updates if tests fails.

**Comment by omajid** [comment]
This should be fixed now. Please let us know if you are still seeing this.
