### ISSUE TITLE
watch : Exited with error code 134

### ISSUE THREAD

**Issue by avikdutta111191** [dotnet/core#6172]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: linux

**$ dotnet watch run**
watch : Started
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.StringComparer.get_OrdinalIgnoreCase()
   at Microsoft.Extensions.Configuration.ConfigurationProvider..ctor()
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder..ctor(Microsoft.Extensions.Hosting.IHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)
   at CouponWeb.Program.CreateHostBuilder(System.String[])
   at CouponWeb.Program.Main(System.String[])
watch : Exited with error code 134
watch : Waiting for a file to change before restarting dotnet...

**Comment by mairaw** [comment]
Seems a duplicate of #5019

@tarekgh can you help?

**Comment by tarekgh** [comment]
@avikdutta111191 what Linux distro you are using? and did you install ICU on this distro?

**Comment by avikdutta111191** [comment]
ubuntu 20.04lts

Fixed it by adding



<PropertyGroup>
<InvariantGlobalization>true</InvariantGlobalization>
</PropertyGroup>

**Comment by avikdutta111191** [comment]
**ubuntu 20.04lts**

Fixed it by adding
 ```
 <PropertyGroup>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
```

**Comment by tarekgh** [comment]
@avikdutta111191 enabling the Invariant mode as you did is going to limit the globalization support in your app. I think the right fix for you is to install `ICU` library there.

**Comment by avikdutta111191** [comment]
Which package do i need to  install for  ICU library .

**Comment by tarekgh** [comment]
try the command:

```
sudo apt-get install libicu-dev
```

**Comment by mairaw** [comment]
Is your problem solved @avikdutta111191?

**Comment by TheDevelolper** [comment]
I installed libicu-dev but still the problem persists for me
