### ISSUE TITLE
.NET 5 TLS 1.3 AuthenticationException

### ISSUE THREAD

**Issue by BazInTheAZ** [dotnet/core#6274]
### Description

```c#
public class Program
    {
        public static async Task Main(string[] args)
        {
            var client = new HttpClient();

            var response = await client.GetStringAsync("https://www.google.com");

            Console.WriteLine(response);
        }
    }
```

Throws:
{"An error occurred while sending the request."} | System.Net.Http.HttpRequestException
-> {"The read operation failed, see inner exception."} | System.Exception {System.IO.IOException}
--> {"Authentication failed, see inner exception."} | System.Exception {System.Security.Authentication.AuthenticationException}
---> {"The message received was unexpected or badly formatted."} | System.Exception {System.ComponentModel.Win32Exception}

Deepest Stack Trace:
```
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__171`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Security.SslStream.<ReplyOnReAuthenticationAsync>d__170`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Security.SslStream.<ReadAsyncInternal>d__181`1.MoveNext()
```

### Configuration

Runtime: Microsoft.NETCore.App 5.0.6
OS: Windows 10 Version 20H2 Build 19042.985
x64 (don't think bitness is an the issue)

### Other information

This  occurs with the following registry entries in place:
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
```
Disabling TLS 1.3 by reversing the values and running the repro does not throw an exception.

**Comment by wfurt** [comment]
The Windows build seems pretty old. There were several important fixes in Insider Preview builds. They also do not need the registry and TLS 1.3 is enabled by default e.g. is ready for real use.  
I did check on build 21376 and it works fine. So any fix is likely to come from Windows update.

**Comment by wfurt** [comment]
https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-

20H2 is explicitly listed as not supported.

**Comment by BazInTheAZ** [comment]
> https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-
> 
> 20H2 is explicitly listed as not supported.

Ah, understood.  Thank you, @wfurt.
