### ISSUE TITLE
"docker build -t mymicroservice ." returned error message

### ISSUE THREAD

**Issue by aaron-pedigo-eii** [dotnet/core#6354]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello,

So far I had went through each step without issues and when I got to the "docker build -t mymicroservice ." step, it returned the following error message:

error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.

The powershell prompt I am using was "Run as administrator".

**Comment by michaelgsharp** [comment]
If you run `docker --version` what happens?

**Comment by aaron-pedigo-eii** [comment]
I switched back to the Linux containers, and now when I try to start the *Docker Desktop* from the desktop shortcut it actually starts up.  I have not rebooted in between switching to Linux and starting the *Docker Desktop*.

When I run `docker --version` I get `Docker version 20.10.7, build f0df350`

**Comment by michaelgsharp** [comment]
Now that docker desktop starts up, can you try running the build command again?

**Comment by aaron-pedigo-eii** [comment]
I am now retrying the `docker build -t mymicroservice .` command to see what it does this time.
So far it has been on `Step 4/10 : RUN dotnet restore` for a couple minutes.

**Comment by michaelgsharp** [comment]
I would try a couple different things.

1 - Rerun it. the CreateComputeSystem call it is doing is an Async call. Could just be a transient error.
2 - Restart the computer, then make sure that docker is running and run the command again.

Let me know what happens.

**Comment by aaron-pedigo-eii** [comment]
Re-running the command had the same effect.
After rebooting my PC and running `Docker Desktop`, it seems to have 2 things listed in `Containers / Apps` and two things listed in `Images`.

Both `Containers / Apps` have strange names with a sha256 hash next to them and they say created under them.
The `Images` have the following:
<none>, IN USE, <none> .....
mcr.microsoft.com/dotne..., , 5.0

Should I still try the command again?

**Comment by aaron-pedigo-eii** [comment]
I just noticed that when I right click on the whale icon in system tray it lists `Switch to Linux containers...`.  Could that be causing problems?

**Comment by michaelgsharp** [comment]
So docker likes to give their containers strange names. I believe you can manually name them at creation time if you want, but if you don't they do it for you. 

I would delete the 2 in `Containers / Apps`. That is where all the created docker images go. Images you can leave.

It doesn't look like it switched correctly back to the linux containers last time. I would switch back to linux and then try again.

**Comment by aaron-pedigo-eii** [comment]
I deleted the 2 in `Containers / Apps`, then did the switch to Linux thing.
I had a toast message saying it was switching and would take some time.
The whale icon in the lower left of the docker dialog went orange then red and the following appeared in an error dialog:

> System.InvalidOperationException:
> Failed to deploy distro docker-desktop to C:\Users\aaron.pedigo\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: Data supplied is of wrong type.
> 
> 
>  stderr: 
>    at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
>    at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
>

**Comment by michaelgsharp** [comment]
What version of WSL are you running? In powershell run ` wsl -l -v`

**Comment by aaron-pedigo-eii** [comment]
> PS C:\Users\aaron.pedigo> wsl -l -v
> Windows Subsystem for Linux has no installed distributions.
> Distributions can be installed by visiting the Microsoft Store:
> https://aka.ms/wslstore
> PS C:\Users\aaron.pedigo>

**Comment by aaron-pedigo-eii** [comment]
If I go to that URL it opens the Microsoft Store and shows an option to get Ubuntu, openSUSE, Kali, Debian, and Alpine.
Should I get one of those and try to restart the docker desktop?

**Comment by aaron-pedigo-eii** [comment]
The same thing happened when I tried again.
Does it matter which version of Linux I get?

> PS C:\Development\Source\git\temp\MyMicroservice> docker build -t mymicroservice .
> Sending build context to Docker daemon  15.87kB
> Step 1/10 : FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
>  ---> 43de3c2be15a
> Step 2/10 : WORKDIR /src
>  ---> Using cache
>  ---> a96d6f40ec50
> Step 3/10 : COPY MyMicroservice.csproj .
>  ---> Using cache
>  ---> 9b8ac4e145d9
> Step 4/10 : RUN dotnet restore
>  ---> Running in 7563b80bc4d9
> hcsshim::CreateComputeSystem 7563b80bc4d97b70c46595ff312b2df4b53082e772b228e75976ec527296d539: hcsshim: timeout waiting for notification
> PS C:\Development\Source\git\temp\MyMicroservice>

**Comment by michaelgsharp** [comment]
I use the Ubuntu one, so I know that one works. It probably doesn't matter too much is my guess. Though I am not positive about that.

**Comment by aaron-pedigo-eii** [comment]
I installed the Ubuntu one, and then ran `wsl -l -v` in powershell and it still shows that I have no installed distros.
I even rebooted then ran the command.
But the Windows store says `This product is installed.`
There is a Launch button though now instead of install in the store.
Should I click that to make it really install or something?

**Comment by michaelgsharp** [comment]
You may have to restart your current powershell session.

**Comment by michaelgsharp** [comment]
Try launching it once.

**Comment by aaron-pedigo-eii** [comment]
I decided to try clicking on the `Launch` button for Ubuntu in the Windows Store and a command prompt appeared and had this error message:

> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x8007065d
> Error: 0x8007065d Data supplied is of wrong type.
> 
> Press any key to continue...

That is the same error message when I try to flip docker to use linux instead of windows...

**Comment by michaelgsharp** [comment]
See if this thread helps https://github.com/Microsoft/WSL/issues/3815

**Comment by aaron-pedigo-eii** [comment]
Before following guidance on that link, I ran `sc query LxssManager` and it showed the service as not running.
I then ran the `sc config LxssManager start=auto` and it succeeded.
I then rebooted and reran the `sc query LxssManager` and it showed the following:

> C:\Users\aaron.pedigo>sc query LxssManager
> 
> SERVICE_NAME: LxssManager
>         TYPE               : 30  WIN32
>         STATE              : 4  RUNNING
>                                 (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x0


I then tried to switch docker back to WSL from Windows and got this again:

> System.InvalidOperationException:
> Failed to deploy distro docker-desktop to C:\Users\aaron.pedigo\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: Data supplied is of wrong type.
> 
> 
>  stderr: 
>    at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
>    at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15906\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
>

**Comment by aaron-pedigo-eii** [comment]
I then ran `wsl -l -v` in a command prompt again and got this again:

> C:\Users\aaron.pedigo>wsl -l -v
> Windows Subsystem for Linux has no installed distributions.
> Distributions can be installed by visiting the Microsoft Store:
> https://aka.ms/wslstore

I then went to the store, clicked the Launch button and still got this:

> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x8007065d
> Error: 0x8007065d Data supplied is of wrong type.

**Comment by aaron-pedigo-eii** [comment]
I am not sure what this means, but I did find I have 2 of the LxssManager services installed on my PC.
They have the same description, but different names:

- LxssManager
- LxssManagerUser_37a6ce

The normal one is Running with a startup type of automatic.
The "user" one is not running and has a startup type of Manual (Trigger Start)

I don't know if this stuff matters, but this web page showed the services, and the user one wasn't there:
https://appuals.com/wslregisterdistribution-failed-with-error-0x8007019e/

**Comment by aaron-pedigo-eii** [comment]
I found the last reply on this page, and since I used to have VMWare on this PC I tried `bcdedit /set hypervisorlaunchtype off`.
That did not help.
https://answers.microsoft.com/en-us/windows/forum/windows_other-winapps/wslregisterdistribution-error-0x80370102/e51a15f1-1f60-445e-b15a-8a6a0562cea9
