### ISSUE TITLE
dotnet new console error when edit environment

### ISSUE THREAD

**Issue by CUTFYSH1101** [dotnet/core#6377]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

I was trying to create a hello world in vs code.
But it failed.

`PS D:\公用\01.暫存\新增資料夾 (2)> dotnet new console -o myApp
即將就緒...
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources, Boolean debugAllowDevInstall, Boolean interactive) 
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources, Boolean debugAllowDevInstall, Boolean interactive) 
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests)
   at Microsoft.DotNet.Tools.New.NewCommandShim.FirstRun(IEngineEnvironmentSettings environmentSettings, IInstaller installer)
   at Microsoft.TemplateEngine.Cli.New3Command.ConfigureEnvironment()
   at Microsoft.TemplateEngine.Cli.New3Command.Initialize()
   at Microsoft.TemplateEngine.Cli.New3Command.ExecuteAsync()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass104_0.<<OnExecute>b__0>d.MoveNext()`
![螢幕擷取畫面 2021-06-16 143912](https://user-images.githubusercontent.com/45134799/122170035-b1f32500-ceb0-11eb-8ea5-99024f3c011b.png)

   I had just edit environment > path
   And it had caused the error. And I cannot come back to the last version.

   `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;%HOME_GRADLE%\bin;%HOME_JAVA%\bin;%HOME_ANDROID_ADB%;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\Git\cmd;D:\Program Files\TortoiseGit\bin;D:\Program Files\Language\nodejs\;%HOME_DOTNET_CORE%;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Progra;C:\Program Files\dotnet\`
![螢幕擷取畫面 2021-06-16 143818](https://user-images.githubusercontent.com/45134799/122169922-8ff9a280-ceb0-11eb-9343-60d293fbd837.png)
And In Environment > Path
![螢幕擷取畫面 2021-06-16 143700](https://user-images.githubusercontent.com/45134799/122169766-59238c80-ceb0-11eb-963f-a564893e1243.png)
![螢幕擷取畫面 2021-06-16 143645](https://user-images.githubusercontent.com/45134799/122169779-5f196d80-ceb0-11eb-9f8b-6e847853d830.png)

**Comment by michaelgsharp** [comment]
When you were editing your path what were you trying to change?

**Comment by mairaw** [comment]
And if you run the same command outside of VS Code, do you get the same error?
