### ISSUE TITLE
.Net 6p5, Trimming apps versus Windows Forms

### ISSUE THREAD

**Issue by Betaminos** [dotnet/core#6405]
### Description

I am currently building a very basic application using Windows Forms.

My initial code looks like this (unchanged from template):
```
using System;
using System.Windows.Forms;

namespace WinFormsApp
{
	static class Program
	{
		/// <summary>
		///  The main entry point for the application.
		/// </summary>
		[STAThread]
		static void Main()
		{
			Application.SetHighDpiMode(HighDpiMode.SystemAware);
			Application.EnableVisualStyles();
			Application.SetCompatibleTextRenderingDefault(false);
			Application.Run(new MainView());
		}
	}
}
```

Whenver I try to run it, while trimming (regardless of trimming mode) is activated in the .csproj, my Debugger will instantly run into an unhandled exception when hitting the last line of code:
```
System.NotSupportedException
  HResult=0x80131515
  Message=Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
  Source=System.Private.CoreLib
  StackTrace:
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr& ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at System.Windows.Forms.UnsafeNativeMethods.CreateStdAccessibleObject(HandleRef hWnd, Int32 objID, Guid& refiid, Object& pAcc)
   at System.Windows.Forms.AccessibleObject.UseStdAccessibleObjects(IntPtr handle, Int32 objid)
   at System.Windows.Forms.Control.ControlAccessibleObject.set_Handle(IntPtr value)
   at System.Windows.Forms.Control.ControlAccessibleObject.InitHandle(Control ownerControl)
   at System.Windows.Forms.Control.ControlAccessibleObject..ctor(Control ownerControl)
   at System.Windows.Forms.TextBoxBase.TextBoxBaseAccessibleObject..ctor(TextBoxBase owner)
   at System.Windows.Forms.TextBoxBase.CreateAccessibilityInstance()
   at System.Windows.Forms.Control.get_AccessibilityObject()
   at System.Windows.Forms.TextBoxBase.SelectInternal(Int32 start, Int32 length, Int32 textLen)
   at System.Windows.Forms.TextBox.SelectInternal(Int32 start, Int32 length, Int32 textLen)
   at System.Windows.Forms.TextBox.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

My expectation would have been that Windows Forms is not trimmed (or affected by activating trimming) as it is referenced by a using-statement.
After some experimenting, I am only able to get around this unhandled exception by completely disabling trimming on this project.
The program starts up and works as expected, once I set trimming to false:
`<PublishTrimmed>false</PublishTrimmed>`

### Configuration

* Which version of .NET is the code running on? .Net 6 preview 5
* What OS and version, and for Linux, what distro? Windows 10, 21H1 (19043.1055)
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I'd assume that it is not specific to my setup

**Comment by krwq** [comment]
cc: @eerhardt

**Comment by eerhardt** [comment]
WinForms isn't trim compatible. See

https://github.com/dotnet/winforms/issues/4649
https://github.com/dotnet/sdk/pull/16892

You should have gotten a warning saying:

> NETSDK1164: Windows Forms is not supported or recommended with trimming enabled. Please go to https://aka.ms/dotnet-illink/windows-forms for more details.

@agocke @LakshanF @vitek-karas @merriemcgaw @JeremyKuhne  @RussKie - maybe we should change this from a warning to an error, since it is basically guaranteed not to work?

**Comment by vitek-karas** [comment]
@Betaminos Did you see the warning "Windows Forms is not supported or recommended with trimming enabled."?

We didn't want to completely disable it - and the current idea is that showing the warning is "enough" to notify the developer. Developer can choose to ignore the warning.
If it were an error, we would have to introduce some other mechanism (probably a new property) how to say "I know, but I want to do it anyway".

**Comment by vitek-karas** [comment]
There's an issue that the warning is not reported when building the app - so it's possible for users to never see the warning, but the app is still broken. Filed an issue for that: https://github.com/dotnet/sdk/issues/18474

**Comment by vitek-karas** [comment]
Playing with this a bit more - I agree that we should actually fail the build in this case - since it's pretty much guaranteed to break the app (simple text box does that). But that means we need to have a way to override the error (or turn it into a warning instead).

Going to move this to the SDK repo where all these changes would take place.
