### ISSUE TITLE
typeof({primitive}).GetMethods() does not return operator overloads

### ISSUE THREAD

**Issue by mchandschuh** [dotnet/core#6463]
### Description

In the full netframework, calling

``` csharp
typeof(int).GetMethods()
```
would contain all of the operator methods, such as  `op_Addition`. Currently in netcoreapp3.1, this same call comes back without **any** operator methods. What's _really_ confusing me is that I can get the operators for all custom types and a handful of primitives. It seems to be **_all_** integral primitives (including bool) aren't exposing their operator overloads.

### Configuration
$ dotnet --version
5.0.301

csproj: netcoreapp3.1

### Regression?
I haven't been this deep into reflection in many years, but I do distinctly remember it working in .NET framework 4.5+ (and likely much earlier versions)

### Other information

The discrepancy between primitives got me curious so I checked various types and am now totally lost.

``` csharp
[Test]
[TestCase(typeof(bool))]
[TestCase(typeof(byte))]
[TestCase(typeof(short))]
[TestCase(typeof(ushort))]
[TestCase(typeof(int))]
[TestCase(typeof(uint))]
[TestCase(typeof(long))]
[TestCase(typeof(ulong))]
[TestCase(typeof(float))]
[TestCase(typeof(double))]
[TestCase(typeof(decimal))]
[TestCase(typeof(string))]
[TestCase(typeof(DateTime))]
public void CheckOperators(Type type)
{
    var ops = type.GetMethods().Where(m => m.Name.StartsWith("op_")).ToList();
    if (ops.Count > 0)
    {
        var str = string.Join(Environment.NewLine, ops.OrderBy(m => m.Name));
        Console.WriteLine($"{type} has {ops.Count} operators:
{str}");
    }
    else
    {
        Assert.Fail($"{type} has no operators.");
    }
}
```
Here's the results:

<details>

``` text
    CheckOperators (13 tests) Failed: One or more child tests had errors: 8 tests failed
One or more child tests had errors
  Exception doesn't have a stacktrace


     CheckOperators(System.Boolean) Failed: System.Boolean has no operators.
System.Boolean has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74



     CheckOperators(System.Byte) Failed: System.Byte has no operators.
System.Byte has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74



     CheckOperators(System.DateTime) Success
System.DateTime has 9 operators:
System.DateTime op_Addition(System.DateTime, System.TimeSpan)
Boolean op_Equality(System.DateTime, System.DateTime)
Boolean op_GreaterThan(System.DateTime, System.DateTime)
Boolean op_GreaterThanOrEqual(System.DateTime, System.DateTime)
Boolean op_Inequality(System.DateTime, System.DateTime)
Boolean op_LessThan(System.DateTime, System.DateTime)
Boolean op_LessThanOrEqual(System.DateTime, System.DateTime)
System.DateTime op_Subtraction(System.DateTime, System.TimeSpan)
System.TimeSpan op_Subtraction(System.DateTime, System.DateTime)

     CheckOperators(System.Decimal) Success
System.Decimal has 37 operators:
System.Decimal op_Addition(System.Decimal, System.Decimal)
System.Decimal op_Decrement(System.Decimal)
System.Decimal op_Division(System.Decimal, System.Decimal)
Boolean op_Equality(System.Decimal, System.Decimal)
System.Decimal op_Explicit(Single)
System.Decimal op_Explicit(Double)
Byte op_Explicit(System.Decimal)
SByte op_Explicit(System.Decimal)
Char op_Explicit(System.Decimal)
Int16 op_Explicit(System.Decimal)
UInt16 op_Explicit(System.Decimal)
Int32 op_Explicit(System.Decimal)
UInt32 op_Explicit(System.Decimal)
Int64 op_Explicit(System.Decimal)
UInt64 op_Explicit(System.Decimal)
Single op_Explicit(System.Decimal)
Double op_Explicit(System.Decimal)
Boolean op_GreaterThan(System.Decimal, System.Decimal)
Boolean op_GreaterThanOrEqual(System.Decimal, System.Decimal)
System.Decimal op_Implicit(Byte)
System.Decimal op_Implicit(SByte)
System.Decimal op_Implicit(Int16)
System.Decimal op_Implicit(UInt16)
System.Decimal op_Implicit(Char)
System.Decimal op_Implicit(Int32)
System.Decimal op_Implicit(UInt32)
System.Decimal op_Implicit(Int64)
System.Decimal op_Implicit(UInt64)
System.Decimal op_Increment(System.Decimal)
Boolean op_Inequality(System.Decimal, System.Decimal)
Boolean op_LessThan(System.Decimal, System.Decimal)
Boolean op_LessThanOrEqual(System.Decimal, System.Decimal)
System.Decimal op_Modulus(System.Decimal, System.Decimal)
System.Decimal op_Multiply(System.Decimal, System.Decimal)
System.Decimal op_Subtraction(System.Decimal, System.Decimal)
System.Decimal op_UnaryNegation(System.Decimal)
System.Decimal op_UnaryPlus(System.Decimal)

     CheckOperators(System.Double) Success
System.Double has 6 operators:
Boolean op_Equality(Double, Double)
Boolean op_GreaterThan(Double, Double)
Boolean op_GreaterThanOrEqual(Double, Double)
Boolean op_Inequality(Double, Double)
Boolean op_LessThan(Double, Double)
Boolean op_LessThanOrEqual(Double, Double)

     CheckOperators(System.Int16) Failed: System.Int16 has no operators.
System.Int16 has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74



     CheckOperators(System.Int32) Failed: System.Int32 has no operators.
System.Int32 has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74



     CheckOperators(System.Int64) Failed: System.Int64 has no operators.
System.Int64 has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74



     CheckOperators(System.Single) Success
System.Single has 6 operators:
Boolean op_Equality(Single, Single)
Boolean op_GreaterThan(Single, Single)
Boolean op_GreaterThanOrEqual(Single, Single)
Boolean op_Inequality(Single, Single)
Boolean op_LessThan(Single, Single)
Boolean op_LessThanOrEqual(Single, Single)

     CheckOperators(System.String) Success
System.String has 3 operators:
Boolean op_Equality(System.String, System.String)
System.ReadOnlySpan`1[System.Char] op_Implicit(System.String)
Boolean op_Inequality(System.String, System.String)

     CheckOperators(System.UInt16) Failed: System.UInt16 has no operators.
System.UInt16 has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74



     CheckOperators(System.UInt32) Failed: System.UInt32 has no operators.
System.UInt32 has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74



     CheckOperators(System.UInt64) Failed: System.UInt64 has no operators.
System.UInt64 has no operators.
   at reflection.ReflectTests.CheckOperators(Type type) in src\tests\reflection\ReflectTests.cs:line 74
```

</details>

### Questions

* Is there any rhyme or reason as to why operator overloads are accessible for some but not other primitive types?
* How can I get access to `MethodInfo` instances for integral types' overloaded operators?

Thanks!

**Comment by wfurt** [comment]
any idea @jkotas ?

**Comment by jkotas** [comment]
> In the full netframework, calling `typeof(int).GetMethods()` would contain all of the operator methods, such as op_Addition.

It is not what I see. Here is output of `foreach (var m in typeof(int).GetMethods()) Console.WriteLine(m);`

for .NET Framework:

```
Int32 CompareTo(System.Object)
Int32 CompareTo(Int32)
Boolean Equals(System.Object)
Boolean Equals(Int32)
Int32 GetHashCode()
System.String ToString()
System.String ToString(System.String)
System.String ToString(System.IFormatProvider)
System.String ToString(System.String, System.IFormatProvider)
Int32 Parse(System.String)
Int32 Parse(System.String, System.Globalization.NumberStyles)
Int32 Parse(System.String, System.IFormatProvider)
Int32 Parse(System.String, System.Globalization.NumberStyles, System.IFormatProvider)
Boolean TryParse(System.String, Int32 ByRef)
Boolean TryParse(System.String, System.Globalization.NumberStyles, System.IFormatProvider, Int32 ByRef)
System.TypeCode GetTypeCode()
System.Type GetType()
```

for .NET Core 3.1:

```
Int32 CompareTo(System.Object)
Int32 CompareTo(Int32)
Boolean Equals(System.Object)
Boolean Equals(Int32)
Int32 GetHashCode()
System.String ToString()
System.String ToString(System.String)
System.String ToString(System.IFormatProvider)
System.String ToString(System.String, System.IFormatProvider)
Boolean TryFormat(System.Span`1[System.Char], Int32 ByRef, System.ReadOnlySpan`1[System.Char], System.IFormatProvider)
Int32 Parse(System.String)
Int32 Parse(System.String, System.Globalization.NumberStyles)
Int32 Parse(System.String, System.IFormatProvider)
Int32 Parse(System.String, System.Globalization.NumberStyles, System.IFormatProvider)
Int32 Parse(System.ReadOnlySpan`1[System.Char], System.Globalization.NumberStyles, System.IFormatProvider)
Boolean TryParse(System.String, Int32 ByRef)
Boolean TryParse(System.ReadOnlySpan`1[System.Char], Int32 ByRef)
Boolean TryParse(System.String, System.Globalization.NumberStyles, System.IFormatProvider, Int32 ByRef)
Boolean TryParse(System.ReadOnlySpan`1[System.Char], System.Globalization.NumberStyles, System.IFormatProvider, Int32 ByRef)
System.TypeCode GetTypeCode()
```

No operators in either one.

**Comment by jkotas** [comment]
> there any rhyme or reason as to why operator overloads are accessible for some but not other primitive types?

The operators are not exposed as methods for primitive integral types. One reason behind that is that the C# compiler has checked and unchecked variant of these operators, but there is no syntax to capture this difference in an explicit implementations.

> How can I get access to MethodInfo instances for integral types' overloaded operators?

You cannot. These methods do not exist and never existed.
