### ISSUE TITLE
dotnet restore gives "The repository primary signature validity period has expired". 

### ISSUE THREAD

**Issue by bobleujr** [dotnet/core#6595]
### Description
It's been almost 3 weeks that my CI/CDs fail intermittently when restoring the nuget packages.  Here's one example

  ```
   1>C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error : The given key '(Hangfire.Core, 1.6.19)' was not present in the dictionary. [D:\a\1\s\MyProject.Api.sln]
         System.Collections.Generic.KeyNotFoundException: The given key '(Hangfire.Core, 1.6.19)' was not present in the dictionary.
            at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
            at NuGet.Commands.LockFileBuilder.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetGraphs, IReadOnlyList`1 localRepositories, RemoteWalkContext context)
            at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
            at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
            at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken)
            at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)
       Done executing task "RestoreTask" -- FAILED.
     1>Done building target "Restore" in project "MyProject.Api.sln" -- FAILED.
     1>Done Building Project "D:\a\1\s\MyProject.Api.sln" (Restore target(s)) -- FAILED.

Build FAILED.

       "D:\a\1\s\MyProject.Api.sln" (Restore target) (1) ->
       (Restore target) -> 
         D:\a\1\s\src\sites\MyProject.Api\MyProject.Api.csproj : error NU3037: Package 'System.Threading.Thread 4.0.0-rc2-24027' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [D:\a\1\s\MyProject.Api.sln]
         D:\a\1\s\src\sites\MyProject.Api\MyProject.Api.csproj : error NU3028: Package 'System.Threading.Thread 4.0.0-rc2-24027' from source 'https://api.nuget.org/v3/index.json': **The repository primary signature's timestamping certificate is not trusted by the trust provider. [**D:\a\1\s\MyProject.Api.sln]
         D:\a\1\s\src\lib\MyProject.Core\MyProject.Core.csproj : error NU3037: Package 'Microsoft.NETCore.Windows.ApiSets 1.0.1-rc2-24027' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [D:\a\1\s\MyProject.Api.sln]
         D:\a\1\s\src\lib\MyProject.Core\MyProject.Core.csproj : error NU3028: Package 'Microsoft.NETCore.Windows.ApiSets 1.0.1-rc2-24027' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider. [D:\a\1\s\MyProject.Api.sln]
         D:\a\1\s\src\lib\MyProject.Core\MyProject.Core.csproj : error NU3037: Package 'System.IO.FileSystem.Watcher 4.0.0-rc2-24027' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [D:\a\1\s\MyProject.Api.sln]
         D:\a\1\s\src\lib\MyProject.Core\MyProject.Core.csproj : error NU3028: Package 'System.IO.FileSystem.Watcher 4.0.0-rc2-24027' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider. [D:\a\1\s\MyProject.Api.sln]
         C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error : The given key '(Hangfire.Core, 1.6.19)' was not present in the dictionary. [D:\a\1\s\MyProject.Api.sln]

```

It fails with different packages in the retry restore right after, and eventually, it passes.

### Configuration
My .csproj / .sln files are very straightforward. I will paste an example .csproj from one of the projects failing here
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Responses\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="wkhtmlx32\libwkhtmltox.dll" />
    <None Remove="wkhtmlx64\libwkhtmltox.dll" />
    <None Remove="wkhtmlx64\libwkhtmltox.dylib" />
    <None Remove="wkhtmlx64\libwkhtmltox.so" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wkhtmlx32\libwkhtmltox.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="wkhtmlx64\libwkhtmltox.dll" />
    <Content Include="wkhtmlx64\libwkhtmltox.dylib" />
    <Content Include="wkhtmlx64\libwkhtmltox.so" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HangFire.Redis.StackExchange" Version="1.7.2" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.15.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.9" />
  </ItemGroup>


  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet>..\..\..\root\default.ruleset</CodeAnalysisRuleSet>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="wkhtmlx64\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>

```
I am using VSTS agents (Microsoft-hosted) via Azure DevOps, so I don't have control over the dotnet installation.

**Comment by mairaw** [comment]
@omajid posted this on the first issue:

> Sounds like NuGet/Home#10712
> What OS and .NET version are you using?

**Comment by bobleujr** [comment]
The agent running the job is specified as 
<img width="310" alt="Screen Shot 2021-08-16 at 5 55 34 PM" src="https://user-images.githubusercontent.com/6935646/129634337-29d93a20-4abf-4fef-9527-c506471ac261.png">

Which should contain [these sdks](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md#net-core-sdk)

the agent OS is
<img width="715" alt="Screen Shot 2021-08-16 at 5 57 07 PM" src="https://user-images.githubusercontent.com/6935646/129634458-d13f1f01-07ab-431b-8b04-d00eb8167fef.png">

As the .csproj file shows, it's targeting 

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
```

**Comment by richlander** [comment]
I cannot reproduce those errors using the 5.0.302 SDK (using docker) with the given project.

Are you using that the signature validation nuget.config file you shared? That's not clear from what you wrote.

**Comment by bobleujr** [comment]
thank you for the answer @richlander. In one of the projects, we don't have a nuget.config file. In the other, on the other hand, it looks like (it's also failing from time to time):

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="Nuget" value="https://api.nuget.org/v3/index.json" />
    <add key="privatefeed" value="our private feed" />
  </packageSources>
</configuration>
```
Do you think adding the certificate's fingerprint to a nuget.config explicitly could solve the problem? Shouldn't not having a nuget.config yield the same behavior?

**Comment by richlander** [comment]
For kicks, can you try moving to a later version of the SDK? 5.0.302 is now old.

**Comment by richlander** [comment]
Another thing I noticed is that you are using a VS2017 image with .NET 5. .NET 5 is supported with VS2019+. You should also upgrade your image to VS 2019. That may be the bigger issue at play.

**Comment by jeromelaban** [comment]
I'm getting this error on CI on macOS specifically, since a few hours. 

Here's an example: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=32328&view=logs&j=eb40ee8c-c15a-5b86-e8f8-c957f416d765&t=7b4a93a7-f0fb-5b1e-a9ea-609a25e9f0ec&l=17980

There are two errors, in fact:
```
The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
```

and 

```
error NU3037: Package 'System.Security.Cryptography.Csp 4.0.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
```

**Comment by richlander** [comment]
Your SDK is too old. I recommend jumping up to 5.0.400.

This is happening on Linux, macOS, and Windows for a series of reasons. If you upgrade to the latest .NET 5 or .NET 6 SDK, it will likely resolved. I'll explain.

- In [January](https://github.com/dotnet/announcements/issues/173) Debian made a certificate change to distrust Symantec certificates (which nuget.org uses pervasively). We asked Debian to revert this, which they did.
- In [April](https://github.com/dotnet/announcements/issues/180) the same change became pervasive and we changed .NET 5 and 6 at that time to no longer validate packages (which was super unfortunate). As long as you are using .NET 5.0.202 or higher, then you should not be seeing this issue.
- In August (today), we saw that macOS made the same change as we saw on Linux. Again, you are using .NET 5.0.202 or higher, you should not experience this.
- Very separately, there is an issue on Windows where certificates are not updated correctly on boot. We are working with the Windows team on that. It has no affinity to the Symantec certificates. Certificate validation is still in force on Windows since the Symantec certificates we need are still trusted.
- We are working on a plan to re-enable certificate validation on Linux and macOS and will soon share a spec on that. It is somewhat complex.

As a result of today's certificate changes on macOS, .NET 5.0.100 series SDKs are now unsupported (on macOS).

**Comment by dtivel** [comment]
> there is an issue on Windows where certificates are not updated correctly

This is tracked via https://github.com/NuGet/Home/issues/11099.  Note that this is Windows only and intermittent.

**Comment by jeromelaban** [comment]
@richlander thanks for the update and explanations, upgrading to 5.0.400 fixed it for me.

**Comment by mario-galindo** [comment]
> Your SDK is too old. I recommend jumping up to 5.0.400.
> 
> This is happening on Linux, macOS, and Windows for a series of reasons. If you upgrade to the latest .NET 5 or .NET 6 SDK, it will likely resolved. I'll explain.
> 
> * In [January](https://github.com/dotnet/announcements/issues/173) Debian made a certificate change to distrust Symantec certificates (which nuget.org uses pervasively). We asked Debian to revert this, which they did.
> * In [April](https://github.com/dotnet/announcements/issues/180) the same change became pervasive and we changed .NET 5 and 6 at that time to no longer validate packages (which was super unfortunate). As long as you are using .NET 5.0.202 or higher, then you should not be seeing this issue.
> * In August (today), we saw that macOS made the same change as we saw on Linux. Again, if you are using .NET 5.0.202 or higher, you should not experience this.
> * Very separately, there is an issue on Windows where certificates are not updated correctly on boot. We are working with the Windows team on that. It has no affinity to the Symantec certificates. NuGet package validation is still in force on Windows since the Symantec certificates we need are still trusted.
> * We are working on a plan to re-enable certificate validation on Linux and macOS and will soon share a spec on that. It is somewhat complex.
> 
> As a result of today's certificate changes on macOS, .NET 5.0.100 series SDKs are now unsupported (on macOS).

This save my life, thanks!
