### ISSUE TITLE
Unhandled exception. System.IO.DirectoryNotFoundException:    .nuget\packages\dg.signalr\2.2.2021.918-beta09\staticwebassets\

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/core#6713]
Unhandled exception. System.IO.DirectoryNotFoundException: C:\Users\berin\.nuget\packages\dg.signalr\2.2.2021.918-beta09\staticwebassets\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by tannergooding** [comment]
Can you please provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Just the exception message doesn't give enough details for us to triage or reproduce the issue.
