### ISSUE TITLE
dotnet run of simple 'hello world' runs into error - first try

### ISSUE THREAD

**Issue by fiversen-1234** [dotnet/core#6766]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Run the simple  'hello world' program runs into:
dotnet run
/home/shell/wedding/dotnet/sdk/5.0.401/Roslyn/Microsoft.CSharp.Core.targets(71,5): error : Failed to create CoreCLR, HRESULT: 0x80004005 [/home/www/wedding/public_html/myApp/myApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by fiversen-1234** [comment]
wedding@kudu:~$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /home/shell/wedding/dotnet/sdk/5.0.401/

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [/home/shell/wedding/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [/home/shell/wedding/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/home/shell/wedding/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
wedding@kudu:~$ 

--
I hope it is possible to install dotnet only in my account on the server.
Because it is a server for a lot of user.
--
Frank I.

**Comment by fiversen-1234** [comment]
this works.
thanks a lot.
..
frank i.

**Comment by vitek-karas** [comment]
I'm just curious: So `dotnet build` and running the app directly works, but `dotnet run` fails (repeatedly)?

**Comment by fiversen-1234** [comment]
You are right - it runs one time.
Now I have the situation as before.

I start again:
dotnet new console --output sample1

...
wedding@kudu:~/sample1$ dotnet build
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/home/shell/wedding/dotnet/sdk/5.0.401/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB3883: Unexpected exception:  [/home/shell/wedding/sample1/sample1.csproj]
/home/shell/wedding/dotnet/sdk/5.0.401/Roslyn/Microsoft.CSharp.Core.targets(71,5): error : Resource temporarily unavailable [/home/shell/wedding/sample1/sample1.csproj]

Build FAILED.

/home/shell/wedding/dotnet/sdk/5.0.401/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB3883: Unexpected exception:  [/home/shell/wedding/sample1/sample1.csproj]
/home/shell/wedding/dotnet/sdk/5.0.401/Roslyn/Microsoft.CSharp.Core.targets(71,5): error : Resource temporarily unavailable [/home/shell/wedding/sample1/sample1.csproj]
    0 Warning(s)
    2 Error(s)
...

**Comment by fiversen-1234** [comment]
Build 'hello world' on my local linux - it works.
Then I copy it to the server.
The program runs.

On the server - I want to rebuild it.

Then I got a lot of errors:
wedding@kudu:~/websites/public_html/myApp$ dotnet build
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Unhandled exception. Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: MSB0001: Internal MSBuild Error: Failure during engine shutdown.  Exception: System.AggregateException: One or more errors occurred. (An exception was thrown by a TaskScheduler.)
 ---> System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal()
   at System.Threading.Thread.Start()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.InjectThread()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.RequestThread()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task`1.StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler)
   at System.Threading.Tasks.TaskFactory.StartNew[TResult](Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at Microsoft.Build.BackEnd.RequestBuilder.StartBuilderThread()
   at Microsoft.Build.BackEnd.RequestBuilder.BuildRequest(NodeLoggingContext loggingContext, BuildRequestEntry entry)
   at Microsoft.Build.BackEnd.BuildRequestEngine.ActivateBuildRequest(BuildRequestEntry entry)
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass42_0.<SubmitBuildRequest>b__0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass72_0.<QueueAction>b__0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c.<InitializeForBuild>b__40_0(Action action)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass6_0.<.ctor>b__0(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Build.BackEnd.BuildRequestEngine.CleanupForBuild()
=============
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Failure during engine shutdown.  Exception: System.AggregateException: One or more errors occurred. (An exception was thrown by a TaskScheduler.)
 ---> System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal()
   at System.Threading.Thread.Start()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.InjectThread()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.RequestThread()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task`1.StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler)
   at System.Threading.Tasks.TaskFactory.StartNew[TResult](Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at Microsoft.Build.BackEnd.RequestBuilder.StartBuilderThread()
   at Microsoft.Build.BackEnd.RequestBuilder.BuildRequest(NodeLoggingContext loggingContext, BuildRequestEntry entry)
   at Microsoft.Build.BackEnd.BuildRequestEngine.ActivateBuildRequest(BuildRequestEntry entry)
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass42_0.<SubmitBuildRequest>b__0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass72_0.<QueueAction>b__0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c.<InitializeForBuild>b__40_0(Action action)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass6_0.<.ctor>b__0(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Build.BackEnd.BuildRequestEngine.CleanupForBuild()
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.BackEnd.BuildRequestEngine.CleanupForBuild()
   at Microsoft.Build.BackEnd.InProcNode.HandleShutdown(Exception& exception)
   at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)


 ---> Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Failure during engine shutdown.  Exception: System.AggregateException: One or more errors occurred. (An exception was thrown by a TaskScheduler.)
 ---> System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal()
   at System.Threading.Thread.Start()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.InjectThread()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.RequestThread()
   at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task`1.StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler)
   at System.Threading.Tasks.TaskFactory.StartNew[TResult](Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at Microsoft.Build.BackEnd.RequestBuilder.StartBuilderThread()
   at Microsoft.Build.BackEnd.RequestBuilder.BuildRequest(NodeLoggingContext loggingContext, BuildRequestEntry entry)
   at Microsoft.Build.BackEnd.BuildRequestEngine.ActivateBuildRequest(BuildRequestEntry entry)
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass42_0.<SubmitBuildRequest>b__0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass72_0.<QueueAction>b__0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c.<InitializeForBuild>b__40_0(Action action)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass6_0.<.ctor>b__0(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Build.BackEnd.BuildRequestEngine.CleanupForBuild()
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.BackEnd.BuildRequestEngine.CleanupForBuild()
   at Microsoft.Build.BackEnd.InProcNode.HandleShutdown(Exception& exception)
   at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
   at Microsoft.Build.BackEnd.NodeProviderInProc.<>c__DisplayClass29_0.<InstantiateNode>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by vitek-karas** [comment]
To me this looks like some OS limits on the server. I'm no Linux expert, maybe @janvorli would know something more.
I assume this is not running in container, right?
