### ISSUE TITLE
System.Drawing.EnableUnixSupport runtime switch has no effect

### ISSUE THREAD

**Issue by makealeft** [dotnet/core#7048]
### Description
According to https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only System.Drawing.Common is no longer supported under on non-windows OS UNLESS a runtime configuration switch is set. 

To test how to setup the switch I've setup a simple console app to and setup runtimeconfig.template.json with the following as per link above:

{
  "runtimeOptions": {
    "configProperties": {
      "System.Drawing.EnableUnixSupport": true
    }
  }
}

Inside the file <applicationName>.runtimeconfig.json in bin/Debug/net6.0 I see the options copied in there

The app has a single line of code that just creates a Bitmap object :
Bitmap bitmap = new Bitmap(10, 10);

However when I run the app in a linux box using 'dotnet exec app.dll' I still get PlatformNotSupportedException
 
### Configuration
.NET 6.0
Virtualization: microsoft
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 5.0.0-1032-azure
Architecture: x86-64

### Other information
Stack Trace:
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, IntPtr scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   at Program.<Main>$(String[] args) in C:\Users.....

**Comment by makealeft** [comment]
As a further note, this simple application works fine on .NetCore 3.1 with System.Drawing.Common 4.7.3  According to the breaking change report it should continue to work for now if the switch is used
