### ISSUE TITLE
Unable to run .netcore in mac os High sierra 10.13.6

### ISSUE THREAD

**Issue by velmaniAngular** [dotnet/core#7482]
I have installed  .netcore sdk and when i run the folllowing cmd i get this error

**Command:** dotnet new console -o hello

**Error:** Unhandled exception. System.DllNotFoundException: Unable to load shared library 'System.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSystem.Native, 1): image not found
   at System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform osPlatform)
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.GetRuntimeDataRootPathString()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
zsh: abort      dotnet new console -o hello

**Comment by michaelgsharp** [comment]
What version of dotnet are you running?

**Comment by mairaw** [comment]
Supported versions of dotnet are only supported on 10.15+
https://docs.microsoft.com/en-us/dotnet/core/install/macos#supported-releases
