### ISSUE TITLE
Uri constructor cannot parse http://hostname:port/  when hostname is * or +

### ISSUE THREAD

**Issue by chuacw** [dotnet/core#7656]
### Description

* The Uri constructor cannot parse http://hostname:port/ when hostname is * or +, ie, http://*:9999/ or http://+:9999 will cause an exception to be thrown.
`
            httpListener = new HttpListener();
            string url = "http://*:1234/";
            Uri uri = new Uri(url); 
            // do something here... then pass the url (not uri) to the httpListener
            httpListener.Prefixes.Add(url);
`
* On the "new Uri(url)" line, the following exception occurred
System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The hostname could not be parsed.
  Source=System.Private.Uri
  StackTrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at HttpListenerSegments.Program..ctor() in K:\Development\CSharp\HttpListenerSegments\Program.cs:line 18
   at HttpListenerSegments.Program.Main(String[] args) in K:\Development\CSharp\HttpListenerSegments\Program.cs:line 79

* The Uri constructor should parse * or + into the DnsSafeHost, Host and IdnHost properties/fields (and whatever fields that currently holds the hostname).

* .NET Core 2.1
* Windows 11
* x64

**Comment by svick** [comment]
As far as I can tell, those are not valid HTTP URIs, so I think it's correct that the `Uri` constructor rejects them. They are valid `HttpListener` URI prefixes, but that's not the same thing as URIs.

Why do you think the current behavior is incorrect?

**Comment by chuacw** [comment]
I didn't say it's incorrect, I say it should parse it. While it's true that * and + are not valid in a URI, I need the Uri class to support parsing of this, so that I don't have to parse it on my own, or duplicate an entire class just to parse * and + into the host field.

**Comment by buyaa-n** [comment]
Tagging the area experts @dotnet/ncl for proper response, please  move to runtime if needed
