### ISSUE TITLE
Unable to load shared library 'libSystem.Native' or one of its dependencies.

### ISSUE THREAD

**Issue by WvW-AvA** [dotnet/core#7737]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create
Operating System: archlinux
I just install dotnet-sdk dotnet-runtime from pacman 
It seems OK when I test dotnet and dotnet --list
but when i test dotnet -h, there are some libs unable to load..
```
➜  opentabletdriver git:(master) dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
➜  opentabletdriver git:(master) dotnet --list-sdks
6.0.108 [/usr/share/dotnet/sdk]
➜  opentabletdriver git:(master) dotnet --list-runtimes
Microsoft.NETCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
➜  opentabletdriver git:(master) dotnet -h             
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libSystem.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSystem.Native: cannot open shared object file: No such file or directory
   at System.DateTime.get_UtcNow()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
[1]    8690 IOT instruction  dotnet -h
➜  opentabletdriver git:(master) 

```

**Comment by omajid** [comment]
cc @alucryd who maintains (or used to maintain?) .NET package for Arch.

**Comment by wfurt** [comment]
Do you have `libSystem.Native.so` under `shared/Microsoft.NETCore.App` directory? If so can you run `ldd libSystem.Native.so`.
cc: @ManickaP for any other Arch Linux recommendations.

**Comment by WvW-AvA** [comment]
The problem has been solved after I update system.
```
sudo pacman -Syu
```
