### ISSUE TITLE
System.IO.IOException “The parameter is incorrect” in function "Directory.EnumerateFiles"

### ISSUE THREAD

**Issue by VladisS-Vostok2000** [dotnet/core#8083]
### Description
I build my app in .net3.1. I'm accessing the files in current folder using Directory.EnumerateFiles, but looks like its corrupt.
I tryed .net 5.0 assembly doing the same. The build is release and debugging.
I attached my builds in .zip file.

### Configuration

* Which version of .NET is the code running on?
* .core 3.1
* What OS and version, and for Linux, what distro?
* Windows 10
* What is the architecture (x64, x86, ARM, ARM64)
* x64
* Do you know whether it is specific to that configuration?
* im not sure

```
Unhandled exception. System.IO.IOException: Параметр задан неверно. : Unhandled exception. System.IO.IOException: Параметр задан неверно. : 'G:\Programs\C#\MindustyDraftToFunctionTranslator\bin\Release\netcoreapp3.1\MindustyDraftToFunctionTranslator.dll'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at MindustyDraftToFunctionTranslator.Program.FinishAllDraftsInFolder() in G:\Programs\C#\MindustyDraftToFunctionTranslator\Program.cs:line 52
   at MindustyDraftToFunctionTranslator.Program.Main(String[] args) in G:\Programs\C#\MindustyDraftToFunctionTranslator\Program.cs:line 24
```
There is problem function:
```
        private static void FinishAllDraftsInFolder() {
            var temp1 = System.Reflection.Assembly.GetExecutingAssembly().Location;
            var temp2 = "*" + OldFilenameExtension;
            var temp3 = SearchOption.TopDirectoryOnly;
            foreach (var filePath in Directory.EnumerateFiles(temp1, temp2, temp3)) { // line 52
                try {
                    FinishFile(filePath);
                }
                catch (Exception e) { Console.WriteLine(GetFileName(filePath + ":")); Console.WriteLine(e.Message); Console.WriteLine(e.StackTrace); }
            }
        }
```
Where is OldFilenameExtension = `public const string OldFilenameExtension = ".minfndft";`

[bin.zip](https://github.com/dotnet/core/files/10369220/bin.zip)

**Comment by VladisS-Vostok2000** [comment]
I'm note there is was wrong path:
`var temp1 = "G:\\Programs\\C#\\MindustyDraftToFunctionTranslator\\bin\\Debug\\netcoreapp3.1\\MindustyDraftToFunctionTranslator.dll"`
Thought it gives me current execution folder not assembly.
