### ISSUE TITLE
.NETにおけるアプリ作成チュートリアル

### ISSUE THREAD

**Issue by Tsuna16** [dotnet/core#8402]
Problem encountered on https://dotnet.microsoft.com/ja-jp/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet new console -o MyApp -f net7.0
このコードをターミナルで打ち込んでもエラーが出てしまう。
System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at NuGet.Common.Migrations.MigrationRunner.Run()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by mairaw** [comment]
I'm sorry we missed your earlier issue. I'd give a try on the latest versions. It seems some fixes were made related to this:
https://github.com/dotnet/runtime/issues/80619

Please feel free to reopen this if this continues to happen with .NET.
