### ISSUE TITLE
XslCompiledTransform BadImageFormatException - Bad Method Token

### ISSUE THREAD

**Issue by ThuCommix** [dotnet/core#845]
# XslCompiledTransform BadImageFormatException

When using XslCompiledTransform.Transform the framework throws a BadImageFormatException - Bad Method Token. It works fine with the full framework.

# General

I'm using the newest dot net core sdk available in combination with Visual Studio 2017.3 and Windows10.

Steps to reproduce:

1. Adjust the directories in the attached project to point to the xsl and xml which are also in the zip.
2. Debug to transform.Transform
-> Exception

   at System.Xml.Xsl.CompiledQuery.Query.{urn:schemas-microsoft-com:xslt-debug}init(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime)
   at System.Xml.Xsl.CompiledQuery.Query.Execute(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlSequenceWriter results)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlWriter writer)
   at System.Xml.Xsl.XslCompiledTransform.Transform(XmlReader input, XsltArgumentList arguments, Stream results)

[Sample Project.zip](https://github.com/dotnet/core/files/1228103/Sample.Project.zip)

**Comment by leecow** [comment]
Moving issue to corefx repo

**Comment by leecow** [comment]
Issue moved to [dotnet/corefx #23343](https://github.com/dotnet/corefx/issues/23343) via [**ZenHub**](https://www.zenhub.com/)
