### ISSUE TITLE
.NET 8.0 RC1

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#8759]
[Release Notes](https://github.com/dotnet/core/blob/main/release-notes/8.0/preview/8.0.0-rc.1.md)

Please report any issues you find with [.NET 8 RC 1](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc-1/), either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) - for ASP.NET Core questions
* [dotnet/efcore](https://github.com/dotnet/efcore/issues) - for Entity Framework Core questions
* [dotnet/sdk](https://github.com/dotnet/sdk/issues) - for CLI tools and questions
* [dotnet/runtime](https://github.com/dotnet/runtime/issues) - for runtime, API, or installer issues and questions
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for WinForms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

### Known Issues
If there are any issues with this release we will track them here and check issues off as they're resolved. See the linked issues for details on progress and resolution details.

**Comment by gordysc** [comment]
FYI I think you want this link for the RC1 announcement: https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc1/

**Comment by nZeus** [comment]
May I ask why you released a `8.0` tag for Docker images? The version is still in preview, it is now confusing people as it seems like a final version.
Also, renovate bot tries to upgrade our docker files:
<img width="931" alt="image" src="https://github.com/dotnet/core/assets/2727326/44aff422-52c9-4441-a5e3-e47aec9a015e">

May I ask if it is possible to deregister the `8.0` tag (and `8.0-alpine`, etc.)?
<img width="1092" alt="image" src="https://github.com/dotnet/core/assets/2727326/89242f30-9a77-42d7-ada7-99d8466691d8">

**Comment by amerkoleci** [comment]
After updating to latest net8.0 RC I'm getting issue with Unsafe.AsRef call:
`Argument 1 must be passed with the 'ref' keyword`

Example code:
`static Guid* INativeGuid.NativeGuid => (Guid*)Unsafe.AsPointer(ref Unsafe.AsRef(in IID_IUnknown))`

What changed in Unsafe class part?

**Comment by KubaGluszkiewicz** [comment]
After changing from DotNet 7 to DotNet 8 RC1 for webassembly browser project (not blazor), we are unable to run our application on Tizen (Samsung) and WebOS (LG) devices. 
Those devices are serving host environment based on Chromium. usually those are older versions like 85,
WebAssembly portability is crucial feature for us, as we can ship our application to the users on wide range of systems.

After migrating to DotNet 8 RC1 we are not able to instantinate dotnet runtime at all,
we are getting bunch of errors just at the begining of creating dotnet runtime like this:
```
logging.ts:32 MONO_WASM: TypeError: Cannot read property 'mono_wasm_abort' of undefined
    at Object.Module._mono_wasm_abort [as mono_wasm_abort] (http://127.0.0.1:9000/_framework/dotnet.native.js:8:127389)
    at Object.Ll.l.abort (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:214656)
    at w (http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:1229)
    at http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201358
    at async http://127.0.0.1:9000/_framework/dotnet.runtime.js:3:201217
```

do you have plans to maintain high compatibility for wasm projects in DotNet 8 or it's designed to work only with newest modern browsers?

**Comment by AceSyntax** [comment]
Having created a new Blazor Web App and running it (F5), I get...

System.ExecutionEngineException
  HResult=0x80131506
  Message=Exception of type 'System.ExecutionEngineException' was thrown

This appears to be happening on line 1263 of Process.cs

The first time I run it, it works as expected.  However, if I kill the browser (Edge) and then F5 again, I get the above error.

Doing a clean on the sln seems to fix it.

**Comment by nZeus** [comment]
Thank you for the links. 
IMHO, it could be supported in Production as RC tags, there was no need to release 8.0. Current approach brings confusion to many people.
But thank you anyways

**Comment by richlander** [comment]
We previously published the stable tag (for all releases before .NET 8) starting with preview 1. That was, in retrospect, the wrong approach. We want to help people get ready for GA day. We believe that flushing the `-preview` tag out of the system well before that day is the best approach and that's what we're doing with the `8.0` tag in the RC releases. It's a tradeoff, but we think a good one.

**Comment by melotic** [comment]
There is no .NET 8 ASP.NET Runtime RC Package for `Microsoft.AspNetCore.App.Runtime.win-arm` : https://www.nuget.org/packages/Microsoft.AspNetCore.App.Runtime.win-arm/#versions-body-tab

Is this intended?

**Comment by babenkovitaliy** [comment]
After I installed this version, I cannot compile applications anymore on MacOS. A project that was previously built cannot be built anymore. 

To be more specific, I click on the Rebuild Solution and it processes everything. But when I click on the "Run" button, I get a "The application has not been built" error. 

Current specs:

- MacBook Air M2, 2022
- MacOS Ventura 13.5.2
- Visual Studio for Mac 17.6.4

```
.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/8.0.100-rc.1.23463.5/Sdks
SDK Versions:
	8.0.100-rc.1.23463.5
	8.0.100-preview.7.23376.3
	7.0.308
	7.0.307
	7.0.306
	7.0.304
	7.0.302
	7.0.203
	7.0.102
	6.0.414
	6.0.413
	6.0.412
	6.0.410
	6.0.408
	6.0.405
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks
```
When I try to compile .NET 7.0 application, it does that normally.

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/8828
