### ISSUE TITLE
There is no safe round-trip for System.Enum values

### ISSUE THREAD

**Issue by bradwilson** [dotnet/core#8842]
### Description

I am trying to round-trip enum values to string and back in a way that is safe and guaranteed to always succeed, for any legal (or semi-legal) value.

As you know, since an enum value can store any integral value (with limitations based on the enum's definition), the safest and most compact way to round-trip those values would be via their integral value. This also allows users to round trip enum values which are not explicitly defined, which is of course legal in .NET.

The problem comes when the framework attempts to round-trip negative values. It appears to do so using the current culture and not the invariant culture. Some cultures (like `fo-FO`) use character U+2212 ("Minus Sign") when printing negative numbers, rather than U+002D ("Hyphen-Minus"). The Enum parsing functions, when presented with such a string, fail to parse.

Here is an example of tests that illustrate the problem (using .NET 6):

```csharp
using System;
using System.Globalization;
using Xunit;

enum MyEnum
{
    NegativeOne = -1
}

public class UnitTest
{
    [Fact]
    public void Passing()
    {
        var expected = MyEnum.NegativeOne;

        var actual = Enum.Parse(typeof(MyEnum), expected.ToString("d"));

        Assert.Equal(expected, actual);
    }

    [Fact]
    public void Failing()
    {
        var culture = CultureInfo.CreateSpecificCulture("fo-FO");
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;

        var expected = MyEnum.NegativeOne;

        var actual = Enum.Parse(typeof(MyEnum), expected.ToString("d"));

        Assert.Equal(expected, actual);
    }
}
```

The failing test results in the following stack trace:

```
at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
at System.Enum.Parse(Type enumType, String value)
```

It appears that it misidentifies the string as being a named enum value because of the U+2212 minus sign.

### Configuration

I am able to reproduce this with .NET 6.0.23 on both Windows and Linux (Ubuntu 22.04 in WSL2). The machine is x64.

### Regression?

I am unable to reproduce this with .NET Framework 4.8.1 on Windows. It appears that the `fo-FO` culture does not use U+2212 for printing minus signs on .NET Framework. This means the parse bug probably exists there as well but isn't as likely to be trigger-able. (There may be a culture on .NET Framework that uses U+2212 for minus signs, but `fo-FO` does not appear to. It may also be the case that support for Unicode minus signs in integral `ToString()` is new to .NET Core/.NET.)

### Other information

This was reported against xUnit.net in https://github.com/xunit/xunit/issues/2796.

**Comment by bradwilson** [comment]
It looks like the source has shifted since 6.0, but here is the likely offender in the old source:

https://github.com/dotnet/runtime/blob/v6.0.23/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L965

And here are two more in the new source:

https://github.com/dotnet/runtime/blob/c0584b920ce33b0a32ac4c7e8f469b6b4085409f/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L936
https://github.com/dotnet/runtime/blob/c0584b920ce33b0a32ac4c7e8f469b6b4085409f/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L994

**Comment by bradwilson** [comment]
Personally I think the better alternative would be to just use `CultureInfo.InvariantCulture` when printing integral Enum values, because that seems easier to support.
