### ISSUE TITLE
Importing the FedEx WSDL as a WCF Connected Service has some issues...

### ISSUE THREAD

**Issue by palodequeso** [dotnet/core#895]
This is on .net core 1.1.2, and on Windows 10 Pro 64-bit. I'm using Visual Studio 2017 and this is a C# project.

It's a dotnet core asp.net MVC app that connects to UPS and FedEx and provides a unified shipping service. UPS has a JSON API, easy enough. But FedEx distributes WSDLs. So I learned that with WCF and dotnet core, you have to use a Connected Service. So I imported the WSDL for Address Validation and it went fine. I was able to make that request. Then I imported the WSDL for requesting shipping rates. It compiled fine, but when I go to use it, I get the following exception message:

```Count = error CS0103: The name 'InnerExceptionCount' does not exist in the current context	System.AggregateException```

I googled around and saw issues relating to this same error before, but nothing in the given context, and I'm not quite familiar enough yet with what dotnet core and Connected Service is doing under the hood. I dug through the generated reference source, but I didn't see anything alarming.

I'd be happy to provide more information, I'm just not sure what to show?

**Comment by palodequeso** [comment]
Here's a stack-trace from the cmd line:
```
System.AggregateException: One or more errors occurred. (Fault) ---> System.ServiceModel.FaultException: Fault
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at BoxingAndShipping.Logic.Shipping.FedEx.GetRate(Service service, List`1 packedBoxes, Address sourceAddress, Address destinationAddress) in C:\Users\username\Projects\boxpack\BoxingAndShipping\Logic\Shipping\FedEx.cs:line 214
   at BoxingAndShipping.Controllers.ShippingController.Post(RateRequest request) in C:\Users\username\Projects\boxpack\BoxingAndShipping\Controllers\ShippingController.cs:line 69
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
---> (Inner Exception #0) System.ServiceModel.FaultException: Fault
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
```

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/wcf #2333](https://github.com/dotnet/wcf/issues/2333) via [**ZenHub**](https://www.zenhub.com/)
