### ISSUE TITLE
dotnet(blazor) debugger in lnux(ubuntu)

### ISSUE THREAD

**Issue by Oguidan** [dotnet/core#9026]
### Description

When I debug a dotnet projet on linux ubuntu with the command "dotnet watch run" the debugger is going to run with no end.
When I debug it with "dotnet run" is not going to lunch the project but rather show this in the terminal:
at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ApplyDefaultAppConfiguration(HostBuilderContext hostingContext, IConfigurationBuilder appConfigBuilder, String[] args)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in /home/archangelmichael/Documents/Projects/Compta/MaTontine/Program.cs:line 8

You can try it in linux ubuntu (I don't know about other systems windows, MacOs, etc ...) by creating a new project like "dotnet new blazorserver -o newProject" then "dotnet watch run" or "dotnet run"

Normally with any of this command the project must be lunch

### Configuration

* .Net version 7.0.114
* Ubuntu 23.04
* x86
* I don't know if it's specific to this configuration

**Comment by wfurt** [comment]
can you use `dotnet publish` and run the app directly? When you get to the point running under debugger should not be any different than other native apps.

**Comment by wfurt** [comment]
BTW it may be helpful if you past whole and exact command sequence.

**Comment by Oguidan** [comment]
@wfurt the command sequence! Ok
I said that if error occur whatever you use the cmd "dotnet watch run" or "dotnet run"
