### ISSUE TITLE
what i have done wrong 

### ISSUE THREAD

**Issue by boksv** [dotnet/core#9116]
Hi just trying to follow a tutorial on .net 

getting this error 

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.DotNet.Cli.ParseResultExtensions.GetSubArguments(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

can someone help ?

**Comment by steveharter** [comment]
What is the command or tutorial step that this is occurring on?
