### ISSUE TITLE
dotnet run MVC error:  Can not find compilation library location for package 'Microsoft.NETCore.App'

### ISSUE THREAD

**Issue by foo-baar** [dotnet/core#955]
Hello Team,

I am trying to execute the dotnet mvc project, (created too using mvc) and after fixing all the build error I get this error in browser at run:

```
System.InvalidOperationException: Can not find compilation library location for package 'Microsoft.NETCore.App'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
```

Scanned the complete web to find a possible solution but no luck.
I am using on Mac Sierra dotnet sdk 2.0.0.

Please point me to the solution ✌️

**Comment by Petermarcu** [comment]
Can you share your project? Are you still stuck?

**Comment by foo-baar** [comment]
Hello @Petermarcu ,

I sorted most of the issues, this one gets sorted when you rather use dotnet core commands from terminal (instead of executing form IDE\vscode).

As the dotnet command points to the right location of libraries, so dotnet clean, build, run works fine.
We can close this issue.

Thanks much,
✌️

**Comment by Petermarcu** [comment]
Thanks for confirming!
