### ISSUE TITLE
IL Linker issue with asp.net core

### ISSUE THREAD

**Issue by mig42** [dotnet/core#978]
I've followed the instructions on how to apply the mono IL linker to a .NET core 2.0 application (an ASP.NET core project), but I'm getting runtime exceptions telling me there's no parameterless constructor for one of my model classes

**_TL;DR_**
I can't make the IL linker include the parameterless constructor of one of my model classes in my ASP.NET Core 2.0 app, even if I specifically include it as root. Is it my fault or the linker's?

This is the exception trace:

```Unhandled Exception: System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Hashtable table, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance)
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at tts2.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at tts2.Program.Main(String[] args)
```

The exception is triggered here (only relevant code):
```c#
namespace tts2
{
    public class Program()
    {
        public static void Main(string[] args)
        {
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
        }
    }

    public class Startup
    {
        public IConfiguration Configuration { get; }

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            // stuff

            // The following line throws the exception when published with the IL linker
            MicrosoftLoginSettings loginSettings = new MicrosoftLoginSettings();
            Configuration.GetSection("MicrosoftLoginSettings").Bind(loginSettings);

            // stuff
        }
    }
}

namespace Tts.Settings
{
    public class MicrosoftLoginSettings
    {
        public MicrosoftLoginSettings()
        {
        }

        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
    }
}
```

I added the linker step as required. My nuget.config file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
  <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
 </packageSources>
</configuration>
```

And my tts2.csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RootNamespace>Tts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ILLink.Tasks" Version="0.1.4-preview-981901" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <!-- more PackageReferences... -->
  </ItemGroup>
 <!-- more ItemGroups... -->
</Project>
```

I'm guessing this has something to do with the linker not seeing through reflection, as expected. However, I decided to try the advanced options and explicitly set the assembly as root. This is what I added in my tts2.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- stuff -->
  <ItemGroup>
    <LinkerRootAssemblies Include="tts2" />
  </ItemGroup>
</Project>
```

That didn't change the outcome, so I tried targeting the MicrosoftLoginSettings type specifically. This is what my tts2.csproj looked like then:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- stuff -->
  <ItemGroup>
    <LinkerRootDescriptors Include="linker.xml" />
  </ItemGroup>
</Project>
```

And this is my `linker.xml` file:
```xml
<linker>
  <assembly fullname="tts2">
    <type fullname="Tts.Settings.MicrosoftLoginSettings" required="false" />
  </assembly>
</linker>
```

I also tried without the `required="false"` attribute: same result.

It seems that nothing I do prevents the linker from removing that parameterless constructor. I'm not quite sure I'm doing the right thing, so please feel free to correct me if anything above isn't right!

**Comment by Petermarcu** [comment]
@sbomer @russellhadley

**Comment by sbomer** [comment]
@mig42, thank you for the write-up and the detailed repro info. I haven't been able to reproduce this yet. Here are the sources I'm using: [tts2.zip](https://github.com/dotnet/core/files/1322166/tts2.zip).

Repro steps I'm trying:
- `dotnet publish -r <RID>`
- `./bin/Debug/netcoreapp2.0/<RID>/tts2`

Could you let me know whether you see the issue with these sources?

**Comment by mig42** [comment]
Thank you for your quick answer @sbomer! I can't reproduce the issue with your attached sources 😕 There might be something else I'm doing in my project that causes the issue... Let me build a sample project to reproduce it (I can't share the whole project with you right now 😞) and I'll attach it here!

**Comment by Petermarcu** [comment]
Hi All, I'm going to close this issue for now to help with tracking. @mig42 if you get a repro of the issue, feel free to reopen this issue.
