### ISSUE TITLE
Cannot use DBDataReader as Structured SQL Parameter with 2.0 Update

### ISSUE THREAD

**Issue by Coder3333** [dotnet/core#983]
This article details how to use a DBDataReader as a Structured input parameter to a SQL query:

https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters

This worked just fine with Core 1.1, but since I updated to Core 2.0, it no longer works.  If I use DataTable as input, instead of a DBDataReader, the exact same code works.

The error I get is: 
"Specified method is not supported"
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(_SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()

**Comment by nil4** [comment]
Confirmed, same here.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #24502](https://github.com/dotnet/corefx/issues/24502) via [**ZenHub**](https://www.zenhub.com/)
